package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Adverseeventtype generated by hbm2java
 */
public class Adverseeventtype  implements java.io.Serializable {


     private int id;
     private String adverseEventName;

    public Adverseeventtype() {
    }

	
    public Adverseeventtype(int id) {
        this.id = id;
    }
    public Adverseeventtype(int id, String adverseEventName) {
       this.id = id;
       this.adverseEventName = adverseEventName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getAdverseEventName() {
        return this.adverseEventName;
    }
    
    public void setAdverseEventName(String adverseEventName) {
        this.adverseEventName = adverseEventName;
    }




}


