package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Basicvitals generated by hbm2java
 */
public class Basicvitals  implements java.io.Serializable {


     private Integer id;
     private Float height;
     private String opdnumber;
     private Float temperature;
     private String bloodPressure;
     private Float weight;
     private Integer functionalStatus;
     private Date visitDate;
     private String basicvitalscol;
     private Byte test;

    public Basicvitals() {
    }

    public Basicvitals(Float height, String opdnumber, Float temperature, String bloodPressure, Float weight, Integer functionalStatus, Date visitDate, String basicvitalscol, Byte test) {
       this.height = height;
       this.opdnumber = opdnumber;
       this.temperature = temperature;
       this.bloodPressure = bloodPressure;
       this.weight = weight;
       this.functionalStatus = functionalStatus;
       this.visitDate = visitDate;
       this.basicvitalscol = basicvitalscol;
       this.test = test;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Float getHeight() {
        return this.height;
    }
    
    public void setHeight(Float height) {
        this.height = height;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public Float getTemperature() {
        return this.temperature;
    }
    
    public void setTemperature(Float temperature) {
        this.temperature = temperature;
    }
    public String getBloodPressure() {
        return this.bloodPressure;
    }
    
    public void setBloodPressure(String bloodPressure) {
        this.bloodPressure = bloodPressure;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }
    public Integer getFunctionalStatus() {
        return this.functionalStatus;
    }
    
    public void setFunctionalStatus(Integer functionalStatus) {
        this.functionalStatus = functionalStatus;
    }
    public Date getVisitDate() {
        return this.visitDate;
    }
    
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }
    public String getBasicvitalscol() {
        return this.basicvitalscol;
    }
    
    public void setBasicvitalscol(String basicvitalscol) {
        this.basicvitalscol = basicvitalscol;
    }
    public Byte getTest() {
        return this.test;
    }
    
    public void setTest(Byte test) {
        this.test = test;
    }




}


