package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * CbsSetuptestkittypes generated by hbm2java
 */
public class CbsSetuptestkittypes  implements java.io.Serializable {


     private Integer id;
     private String description;
     private Integer progId;

    public CbsSetuptestkittypes() {
    }

    public CbsSetuptestkittypes(String description, Integer progId) {
       this.description = description;
       this.progId = progId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getProgId() {
        return this.progId;
    }
    
    public void setProgId(Integer progId) {
        this.progId = progId;
    }




}


