package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * CbsSetupserviceaccess generated by hbm2java
 */
public class CbsSetupserviceaccess  implements java.io.Serializable {


     private Integer id;
     private String description;
     private int isHiv;
     private int isSyphilis;
     private int isArvtherapy;

    public CbsSetupserviceaccess() {
    }

    public CbsSetupserviceaccess(String description, int isHiv, int isSyphilis, int isArvtherapy) {
       this.description = description;
       this.isHiv = isHiv;
       this.isSyphilis = isSyphilis;
       this.isArvtherapy = isArvtherapy;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getIsHiv() {
        return this.isHiv;
    }
    
    public void setIsHiv(int isHiv) {
        this.isHiv = isHiv;
    }
    public int getIsSyphilis() {
        return this.isSyphilis;
    }
    
    public void setIsSyphilis(int isSyphilis) {
        this.isSyphilis = isSyphilis;
    }
    public int getIsArvtherapy() {
        return this.isArvtherapy;
    }
    
    public void setIsArvtherapy(int isArvtherapy) {
        this.isArvtherapy = isArvtherapy;
    }




}


