package com.vmmc.entities;
// Generated Mar 25, 2021 10:43:50 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CbsTests generated by hbm2java
 */
public class CbsTests  implements java.io.Serializable {


     private Integer id;
     private String opdnumber;
     private String htcnumber;
     private String recencyTesting;
     private String recencyTesterName;
     private Date recencyTestingDate;
     private String recencyTestingResult;
     private String recencyTestingNotDone;
     private Date dateHivDiagnosed;
     private String firstTestMethod;
     private String firstTestResult;
     private String secondTestMethod;
     private String secondTestResult;
     private String whoStageAtNotification;
     private String whoStage;
     private String cdCountTest;
     private Integer cdCountResult;
     private Integer cdCountPercentage;
     private Date cdCountTestDate;
     private String motherViralloadFirstTest;
     private Integer motherViralloadFirstTestResult;
     private Date motherViralloadFirstTestDate;
     private String motherViralloadSecondTest;
     private Integer motherViralloadSecondTestResult;
     private Date motherViralloadSecondTestDate;
     private Date dateFormCompleted;

    public CbsTests() {
    }

	
    public CbsTests(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public CbsTests(String opdnumber, String htcnumber, String recencyTesting, String recencyTesterName, Date recencyTestingDate, String recencyTestingResult, String recencyTestingNotDone, Date dateHivDiagnosed, String firstTestMethod, String firstTestResult, String secondTestMethod, String secondTestResult, String whoStageAtNotification, String whoStage, String cdCountTest, Integer cdCountResult, Integer cdCountPercentage, Date cdCountTestDate, String motherViralloadFirstTest, Integer motherViralloadFirstTestResult, Date motherViralloadFirstTestDate, String motherViralloadSecondTest, Integer motherViralloadSecondTestResult, Date motherViralloadSecondTestDate, Date dateFormCompleted) {
       this.opdnumber = opdnumber;
       this.htcnumber = htcnumber;
       this.recencyTesting = recencyTesting;
       this.recencyTesterName = recencyTesterName;
       this.recencyTestingDate = recencyTestingDate;
       this.recencyTestingResult = recencyTestingResult;
       this.recencyTestingNotDone = recencyTestingNotDone;
       this.dateHivDiagnosed = dateHivDiagnosed;
       this.firstTestMethod = firstTestMethod;
       this.firstTestResult = firstTestResult;
       this.secondTestMethod = secondTestMethod;
       this.secondTestResult = secondTestResult;
       this.whoStageAtNotification = whoStageAtNotification;
       this.whoStage = whoStage;
       this.cdCountTest = cdCountTest;
       this.cdCountResult = cdCountResult;
       this.cdCountPercentage = cdCountPercentage;
       this.cdCountTestDate = cdCountTestDate;
       this.motherViralloadFirstTest = motherViralloadFirstTest;
       this.motherViralloadFirstTestResult = motherViralloadFirstTestResult;
       this.motherViralloadFirstTestDate = motherViralloadFirstTestDate;
       this.motherViralloadSecondTest = motherViralloadSecondTest;
       this.motherViralloadSecondTestResult = motherViralloadSecondTestResult;
       this.motherViralloadSecondTestDate = motherViralloadSecondTestDate;
       this.dateFormCompleted = dateFormCompleted;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public String getHtcnumber() {
        return this.htcnumber;
    }
    
    public void setHtcnumber(String htcnumber) {
        this.htcnumber = htcnumber;
    }
    public String getRecencyTesting() {
        return this.recencyTesting;
    }
    
    public void setRecencyTesting(String recencyTesting) {
        this.recencyTesting = recencyTesting;
    }
    public String getRecencyTesterName() {
        return this.recencyTesterName;
    }
    
    public void setRecencyTesterName(String recencyTesterName) {
        this.recencyTesterName = recencyTesterName;
    }
    public Date getRecencyTestingDate() {
        return this.recencyTestingDate;
    }
    
    public void setRecencyTestingDate(Date recencyTestingDate) {
        this.recencyTestingDate = recencyTestingDate;
    }
    public String getRecencyTestingResult() {
        return this.recencyTestingResult;
    }
    
    public void setRecencyTestingResult(String recencyTestingResult) {
        this.recencyTestingResult = recencyTestingResult;
    }
    public String getRecencyTestingNotDone() {
        return this.recencyTestingNotDone;
    }
    
    public void setRecencyTestingNotDone(String recencyTestingNotDone) {
        this.recencyTestingNotDone = recencyTestingNotDone;
    }
    public Date getDateHivDiagnosed() {
        return this.dateHivDiagnosed;
    }
    
    public void setDateHivDiagnosed(Date dateHivDiagnosed) {
        this.dateHivDiagnosed = dateHivDiagnosed;
    }
    public String getFirstTestMethod() {
        return this.firstTestMethod;
    }
    
    public void setFirstTestMethod(String firstTestMethod) {
        this.firstTestMethod = firstTestMethod;
    }
    public String getFirstTestResult() {
        return this.firstTestResult;
    }
    
    public void setFirstTestResult(String firstTestResult) {
        this.firstTestResult = firstTestResult;
    }
    public String getSecondTestMethod() {
        return this.secondTestMethod;
    }
    
    public void setSecondTestMethod(String secondTestMethod) {
        this.secondTestMethod = secondTestMethod;
    }
    public String getSecondTestResult() {
        return this.secondTestResult;
    }
    
    public void setSecondTestResult(String secondTestResult) {
        this.secondTestResult = secondTestResult;
    }
    public String getWhoStageAtNotification() {
        return this.whoStageAtNotification;
    }
    
    public void setWhoStageAtNotification(String whoStageAtNotification) {
        this.whoStageAtNotification = whoStageAtNotification;
    }
    public String getWhoStage() {
        return this.whoStage;
    }
    
    public void setWhoStage(String whoStage) {
        this.whoStage = whoStage;
    }
    public String getCdCountTest() {
        return this.cdCountTest;
    }
    
    public void setCdCountTest(String cdCountTest) {
        this.cdCountTest = cdCountTest;
    }
    public Integer getCdCountResult() {
        return this.cdCountResult;
    }
    
    public void setCdCountResult(Integer cdCountResult) {
        this.cdCountResult = cdCountResult;
    }
    public Integer getCdCountPercentage() {
        return this.cdCountPercentage;
    }
    
    public void setCdCountPercentage(Integer cdCountPercentage) {
        this.cdCountPercentage = cdCountPercentage;
    }
    public Date getCdCountTestDate() {
        return this.cdCountTestDate;
    }
    
    public void setCdCountTestDate(Date cdCountTestDate) {
        this.cdCountTestDate = cdCountTestDate;
    }
    public String getMotherViralloadFirstTest() {
        return this.motherViralloadFirstTest;
    }
    
    public void setMotherViralloadFirstTest(String motherViralloadFirstTest) {
        this.motherViralloadFirstTest = motherViralloadFirstTest;
    }
    public Integer getMotherViralloadFirstTestResult() {
        return this.motherViralloadFirstTestResult;
    }
    
    public void setMotherViralloadFirstTestResult(Integer motherViralloadFirstTestResult) {
        this.motherViralloadFirstTestResult = motherViralloadFirstTestResult;
    }
    public Date getMotherViralloadFirstTestDate() {
        return this.motherViralloadFirstTestDate;
    }
    
    public void setMotherViralloadFirstTestDate(Date motherViralloadFirstTestDate) {
        this.motherViralloadFirstTestDate = motherViralloadFirstTestDate;
    }
    public String getMotherViralloadSecondTest() {
        return this.motherViralloadSecondTest;
    }
    
    public void setMotherViralloadSecondTest(String motherViralloadSecondTest) {
        this.motherViralloadSecondTest = motherViralloadSecondTest;
    }
    public Integer getMotherViralloadSecondTestResult() {
        return this.motherViralloadSecondTestResult;
    }
    
    public void setMotherViralloadSecondTestResult(Integer motherViralloadSecondTestResult) {
        this.motherViralloadSecondTestResult = motherViralloadSecondTestResult;
    }
    public Date getMotherViralloadSecondTestDate() {
        return this.motherViralloadSecondTestDate;
    }
    
    public void setMotherViralloadSecondTestDate(Date motherViralloadSecondTestDate) {
        this.motherViralloadSecondTestDate = motherViralloadSecondTestDate;
    }
    public Date getDateFormCompleted() {
        return this.dateFormCompleted;
    }
    
    public void setDateFormCompleted(Date dateFormCompleted) {
        this.dateFormCompleted = dateFormCompleted;
    }




}


