package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Circumcisionreasontype generated by hbm2java
 */
public class Circumcisionreasontype  implements java.io.Serializable {


     private int id;
     private String circumcisionReasonName;

    public Circumcisionreasontype() {
    }

	
    public Circumcisionreasontype(int id) {
        this.id = id;
    }
    public Circumcisionreasontype(int id, String circumcisionReasonName) {
       this.id = id;
       this.circumcisionReasonName = circumcisionReasonName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCircumcisionReasonName() {
        return this.circumcisionReasonName;
    }
    
    public void setCircumcisionReasonName(String circumcisionReasonName) {
        this.circumcisionReasonName = circumcisionReasonName;
    }




}


