package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Complainttype generated by hbm2java
 */
public class Complainttype  implements java.io.Serializable {


     private int id;
     private String complaintName;

    public Complainttype() {
    }

	
    public Complainttype(int id) {
        this.id = id;
    }
    public Complainttype(int id, String complaintName) {
       this.id = id;
       this.complaintName = complaintName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getComplaintName() {
        return this.complaintName;
    }
    
    public void setComplaintName(String complaintName) {
        this.complaintName = complaintName;
    }




}


