package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Diagnosistype generated by hbm2java
 */
public class Diagnosistype  implements java.io.Serializable {


     private Integer id;
     private String diagnosisName;

    public Diagnosistype() {
    }

    public Diagnosistype(String diagnosisName) {
       this.diagnosisName = diagnosisName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDiagnosisName() {
        return this.diagnosisName;
    }
    
    public void setDiagnosisName(String diagnosisName) {
        this.diagnosisName = diagnosisName;
    }




}


