package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * District generated by hbm2java
 */
public class District  implements java.io.Serializable {


     private int id;
     private Integer provinceId;
     private String districtName;
     private String districtCode;

    public District() {
    }

	
    public District(int id) {
        this.id = id;
    }
    public District(int id, Integer provinceId, String districtName, String districtCode) {
       this.id = id;
       this.provinceId = provinceId;
       this.districtName = districtName;
       this.districtCode = districtCode;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getProvinceId() {
        return this.provinceId;
    }
    
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }
    public String getDistrictName() {
        return this.districtName;
    }
    
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }
    public String getDistrictCode() {
        return this.districtCode;
    }
    
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }




}


