package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Facilityconfig generated by hbm2java
 */
public class Facilityconfig  implements java.io.Serializable {


     private Integer idfacilityConfig;
     private int provinceId;
     private String districtId;
     private String facilityId;

    public Facilityconfig() {
    }

    public Facilityconfig(int provinceId, String districtId, String facilityId) {
       this.provinceId = provinceId;
       this.districtId = districtId;
       this.facilityId = facilityId;
    }
   
    public Integer getIdfacilityConfig() {
        return this.idfacilityConfig;
    }
    
    public void setIdfacilityConfig(Integer idfacilityConfig) {
        this.idfacilityConfig = idfacilityConfig;
    }
    public int getProvinceId() {
        return this.provinceId;
    }
    
    public void setProvinceId(int provinceId) {
        this.provinceId = provinceId;
    }
    public String getDistrictId() {
        return this.districtId;
    }
    
    public void setDistrictId(String districtId) {
        this.districtId = districtId;
    }
    public String getFacilityId() {
        return this.facilityId;
    }
    
    public void setFacilityId(String facilityId) {
        this.facilityId = facilityId;
    }




}


