package com.vmmc.entities;
// Generated Jul 7, 2020 1:49:54 PM by Hibernate Tools 4.3.1



/**
 * Facilities generated by hbm2java
 */
public class Facilities  implements java.io.Serializable {


     private Integer facilityId;
     private int provinceCode;
     private String districtCode;
     private String facilityCode;
     private String facilityName;
     private String fullFacilityCode;
     private String fullFacilityCodeDashes;

    public Facilities() {
    }

    public Facilities(int provinceCode, String districtCode, String facilityCode, String facilityName, String fullFacilityCode, String fullFacilityCodeDashes) {
       this.provinceCode = provinceCode;
       this.districtCode = districtCode;
       this.facilityCode = facilityCode;
       this.facilityName = facilityName;
       this.fullFacilityCode = fullFacilityCode;
       this.fullFacilityCodeDashes = fullFacilityCodeDashes;
    }
   
    public Integer getFacilityId() {
        return this.facilityId;
    }
    
    public void setFacilityId(Integer facilityId) {
        this.facilityId = facilityId;
    }
    public int getProvinceCode() {
        return this.provinceCode;
    }
    
    public void setProvinceCode(int provinceCode) {
        this.provinceCode = provinceCode;
    }
    public String getDistrictCode() {
        return this.districtCode;
    }
    
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }
    public String getFacilityCode() {
        return this.facilityCode;
    }
    
    public void setFacilityCode(String facilityCode) {
        this.facilityCode = facilityCode;
    }
    public String getFacilityName() {
        return this.facilityName;
    }
    
    public void setFacilityName(String facilityName) {
        this.facilityName = facilityName;
    }
    public String getFullFacilityCode() {
        return this.fullFacilityCode;
    }
    
    public void setFullFacilityCode(String fullFacilityCode) {
        this.fullFacilityCode = fullFacilityCode;
    }
    public String getFullFacilityCodeDashes() {
        return this.fullFacilityCodeDashes;
    }
    
    public void setFullFacilityCodeDashes(String fullFacilityCodeDashes) {
        this.fullFacilityCodeDashes = fullFacilityCodeDashes;
    }




}


