package com.vmmc.entities;
// Generated May 24, 2021 11:43:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Highviralload generated by hbm2java
 */
public class Highviralload  implements java.io.Serializable {


     private int id;
     private String patientId;
     private String firstSession;
     private Date firstSessionDate;
     private String firstSessionSummary;
     private String secondSession;
     private String arvIntake;
     private Date assessmentDate;
     private String counsellorName;
     private Date secondSessionDate;
     private String secondSessionSummary;
     private String arvIntake2;
     private String extraSession;
     private Date extraSessionDate;
     private String extraSessionSummary;
     private String arvIntake3;
     private Date repeatedVlDate;
     private String viralLoadResult;
     private String arvRegimenValuation;
     private String nurseName;
     private Date nurseAssessmentDate;
     private String regimenValuation;
     private String comments;
     private String doctorName;
     private Date doctorDate;

    public Highviralload() {
    }

	
    public Highviralload(int id) {
        this.id = id;
    }
    public Highviralload(int id, String patientId, String firstSession, Date firstSessionDate, String firstSessionSummary, String secondSession, String arvIntake, Date assessmentDate, String counsellorName, Date secondSessionDate, String secondSessionSummary, String arvIntake2, String extraSession, Date extraSessionDate, String extraSessionSummary, String arvIntake3, Date repeatedVlDate, String viralLoadResult, String arvRegimenValuation, String nurseName, Date nurseAssessmentDate, String regimenValuation, String comments, String doctorName, Date doctorDate) {
       this.id = id;
       this.patientId = patientId;
       this.firstSession = firstSession;
       this.firstSessionDate = firstSessionDate;
       this.firstSessionSummary = firstSessionSummary;
       this.secondSession = secondSession;
       this.arvIntake = arvIntake;
       this.assessmentDate = assessmentDate;
       this.counsellorName = counsellorName;
       this.secondSessionDate = secondSessionDate;
       this.secondSessionSummary = secondSessionSummary;
       this.arvIntake2 = arvIntake2;
       this.extraSession = extraSession;
       this.extraSessionDate = extraSessionDate;
       this.extraSessionSummary = extraSessionSummary;
       this.arvIntake3 = arvIntake3;
       this.repeatedVlDate = repeatedVlDate;
       this.viralLoadResult = viralLoadResult;
       this.arvRegimenValuation = arvRegimenValuation;
       this.nurseName = nurseName;
       this.nurseAssessmentDate = nurseAssessmentDate;
       this.regimenValuation = regimenValuation;
       this.comments = comments;
       this.doctorName = doctorName;
       this.doctorDate = doctorDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public String getFirstSession() {
        return this.firstSession;
    }
    
    public void setFirstSession(String firstSession) {
        this.firstSession = firstSession;
    }
    public Date getFirstSessionDate() {
        return this.firstSessionDate;
    }
    
    public void setFirstSessionDate(Date firstSessionDate) {
        this.firstSessionDate = firstSessionDate;
    }
    public String getFirstSessionSummary() {
        return this.firstSessionSummary;
    }
    
    public void setFirstSessionSummary(String firstSessionSummary) {
        this.firstSessionSummary = firstSessionSummary;
    }
    public String getSecondSession() {
        return this.secondSession;
    }
    
    public void setSecondSession(String secondSession) {
        this.secondSession = secondSession;
    }
    public String getArvIntake() {
        return this.arvIntake;
    }
    
    public void setArvIntake(String arvIntake) {
        this.arvIntake = arvIntake;
    }
    public Date getAssessmentDate() {
        return this.assessmentDate;
    }
    
    public void setAssessmentDate(Date assessmentDate) {
        this.assessmentDate = assessmentDate;
    }
    public String getCounsellorName() {
        return this.counsellorName;
    }
    
    public void setCounsellorName(String counsellorName) {
        this.counsellorName = counsellorName;
    }
    public Date getSecondSessionDate() {
        return this.secondSessionDate;
    }
    
    public void setSecondSessionDate(Date secondSessionDate) {
        this.secondSessionDate = secondSessionDate;
    }
    public String getSecondSessionSummary() {
        return this.secondSessionSummary;
    }
    
    public void setSecondSessionSummary(String secondSessionSummary) {
        this.secondSessionSummary = secondSessionSummary;
    }
    public String getArvIntake2() {
        return this.arvIntake2;
    }
    
    public void setArvIntake2(String arvIntake2) {
        this.arvIntake2 = arvIntake2;
    }
    public String getExtraSession() {
        return this.extraSession;
    }
    
    public void setExtraSession(String extraSession) {
        this.extraSession = extraSession;
    }
    public Date getExtraSessionDate() {
        return this.extraSessionDate;
    }
    
    public void setExtraSessionDate(Date extraSessionDate) {
        this.extraSessionDate = extraSessionDate;
    }
    public String getExtraSessionSummary() {
        return this.extraSessionSummary;
    }
    
    public void setExtraSessionSummary(String extraSessionSummary) {
        this.extraSessionSummary = extraSessionSummary;
    }
    public String getArvIntake3() {
        return this.arvIntake3;
    }
    
    public void setArvIntake3(String arvIntake3) {
        this.arvIntake3 = arvIntake3;
    }
    public Date getRepeatedVlDate() {
        return this.repeatedVlDate;
    }
    
    public void setRepeatedVlDate(Date repeatedVlDate) {
        this.repeatedVlDate = repeatedVlDate;
    }
    public String getViralLoadResult() {
        return this.viralLoadResult;
    }
    
    public void setViralLoadResult(String viralLoadResult) {
        this.viralLoadResult = viralLoadResult;
    }
    public String getArvRegimenValuation() {
        return this.arvRegimenValuation;
    }
    
    public void setArvRegimenValuation(String arvRegimenValuation) {
        this.arvRegimenValuation = arvRegimenValuation;
    }
    public String getNurseName() {
        return this.nurseName;
    }
    
    public void setNurseName(String nurseName) {
        this.nurseName = nurseName;
    }
    public Date getNurseAssessmentDate() {
        return this.nurseAssessmentDate;
    }
    
    public void setNurseAssessmentDate(Date nurseAssessmentDate) {
        this.nurseAssessmentDate = nurseAssessmentDate;
    }
    public String getRegimenValuation() {
        return this.regimenValuation;
    }
    
    public void setRegimenValuation(String regimenValuation) {
        this.regimenValuation = regimenValuation;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getDoctorName() {
        return this.doctorName;
    }
    
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }
    public Date getDoctorDate() {
        return this.doctorDate;
    }
    
    public void setDoctorDate(Date doctorDate) {
        this.doctorDate = doctorDate;
    }




}


