package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Hivresulttype generated by hbm2java
 */
public class Hivresulttype  implements java.io.Serializable {


     private int id;
     private String resultName;

    public Hivresulttype() {
    }

	
    public Hivresulttype(int id) {
        this.id = id;
    }
    public Hivresulttype(int id, String resultName) {
       this.id = id;
       this.resultName = resultName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getResultName() {
        return this.resultName;
    }
    
    public void setResultName(String resultName) {
        this.resultName = resultName;
    }




}


