package com.vmmc.entities;
// Generated Mar 25, 2021 10:43:50 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Htc generated by hbm2java
 */
public class Htc  implements java.io.Serializable {


     private String htcnumber;
     private String opdnumber;
     private Date dateofRegistration;
     private String coupleTo;
     private String isCouple;
     private String htcapproach;
     private Integer htcmodelId;
     private String counselingRecieved;
     private String optedOut;
     private String nameofCounselor;
     private String recievedResult;
     private String postTestCounseled;
     private Date postTestCounselDate;
     private String refferedforService;
     private Integer testPurposeTypeId;
     private Integer referredFromTypeId;
     private String testedBefore;
     private String currentPregnancyLactation;
     private Date dateTestedBefore;
     private Integer entryPointId;
     private String finalResultType;
     private String performedBy;
     private String notified;

    public Htc() {
    }

	
    public Htc(String htcnumber) {
        this.htcnumber = htcnumber;
    }
    public Htc(String htcnumber, String opdnumber, Date dateofRegistration, String coupleTo, String isCouple, String htcapproach, Integer htcmodelId, String counselingRecieved, String optedOut, String nameofCounselor, String recievedResult, String postTestCounseled, Date postTestCounselDate, String refferedforService, Integer testPurposeTypeId, Integer referredFromTypeId, String testedBefore, String currentPregnancyLactation, Date dateTestedBefore, Integer entryPointId, String finalResultType, String performedBy, String notified) {
       this.htcnumber = htcnumber;
       this.opdnumber = opdnumber;
       this.dateofRegistration = dateofRegistration;
       this.coupleTo = coupleTo;
       this.isCouple = isCouple;
       this.htcapproach = htcapproach;
       this.htcmodelId = htcmodelId;
       this.counselingRecieved = counselingRecieved;
       this.optedOut = optedOut;
       this.nameofCounselor = nameofCounselor;
       this.recievedResult = recievedResult;
       this.postTestCounseled = postTestCounseled;
       this.postTestCounselDate = postTestCounselDate;
       this.refferedforService = refferedforService;
       this.testPurposeTypeId = testPurposeTypeId;
       this.referredFromTypeId = referredFromTypeId;
       this.testedBefore = testedBefore;
       this.currentPregnancyLactation = currentPregnancyLactation;
       this.dateTestedBefore = dateTestedBefore;
       this.entryPointId = entryPointId;
       this.finalResultType = finalResultType;
       this.performedBy = performedBy;
       this.notified = notified;
    }
   
    public String getHtcnumber() {
        return this.htcnumber;
    }
    
    public void setHtcnumber(String htcnumber) {
        this.htcnumber = htcnumber;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public Date getDateofRegistration() {
        return this.dateofRegistration;
    }
    
    public void setDateofRegistration(Date dateofRegistration) {
        this.dateofRegistration = dateofRegistration;
    }
    public String getCoupleTo() {
        return this.coupleTo;
    }
    
    public void setCoupleTo(String coupleTo) {
        this.coupleTo = coupleTo;
    }
    public String getIsCouple() {
        return this.isCouple;
    }
    
    public void setIsCouple(String isCouple) {
        this.isCouple = isCouple;
    }
    public String getHtcapproach() {
        return this.htcapproach;
    }
    
    public void setHtcapproach(String htcapproach) {
        this.htcapproach = htcapproach;
    }
    public Integer getHtcmodelId() {
        return this.htcmodelId;
    }
    
    public void setHtcmodelId(Integer htcmodelId) {
        this.htcmodelId = htcmodelId;
    }
    public String getCounselingRecieved() {
        return this.counselingRecieved;
    }
    
    public void setCounselingRecieved(String counselingRecieved) {
        this.counselingRecieved = counselingRecieved;
    }
    public String getOptedOut() {
        return this.optedOut;
    }
    
    public void setOptedOut(String optedOut) {
        this.optedOut = optedOut;
    }
    public String getNameofCounselor() {
        return this.nameofCounselor;
    }
    
    public void setNameofCounselor(String nameofCounselor) {
        this.nameofCounselor = nameofCounselor;
    }
    public String getRecievedResult() {
        return this.recievedResult;
    }
    
    public void setRecievedResult(String recievedResult) {
        this.recievedResult = recievedResult;
    }
    public String getPostTestCounseled() {
        return this.postTestCounseled;
    }
    
    public void setPostTestCounseled(String postTestCounseled) {
        this.postTestCounseled = postTestCounseled;
    }
    public Date getPostTestCounselDate() {
        return this.postTestCounselDate;
    }
    
    public void setPostTestCounselDate(Date postTestCounselDate) {
        this.postTestCounselDate = postTestCounselDate;
    }
    public String getRefferedforService() {
        return this.refferedforService;
    }
    
    public void setRefferedforService(String refferedforService) {
        this.refferedforService = refferedforService;
    }
    public Integer getTestPurposeTypeId() {
        return this.testPurposeTypeId;
    }
    
    public void setTestPurposeTypeId(Integer testPurposeTypeId) {
        this.testPurposeTypeId = testPurposeTypeId;
    }
    public Integer getReferredFromTypeId() {
        return this.referredFromTypeId;
    }
    
    public void setReferredFromTypeId(Integer referredFromTypeId) {
        this.referredFromTypeId = referredFromTypeId;
    }
    public String getTestedBefore() {
        return this.testedBefore;
    }
    
    public void setTestedBefore(String testedBefore) {
        this.testedBefore = testedBefore;
    }
    public String getCurrentPregnancyLactation() {
        return this.currentPregnancyLactation;
    }
    
    public void setCurrentPregnancyLactation(String currentPregnancyLactation) {
        this.currentPregnancyLactation = currentPregnancyLactation;
    }
    public Date getDateTestedBefore() {
        return this.dateTestedBefore;
    }
    
    public void setDateTestedBefore(Date dateTestedBefore) {
        this.dateTestedBefore = dateTestedBefore;
    }
    public Integer getEntryPointId() {
        return this.entryPointId;
    }
    
    public void setEntryPointId(Integer entryPointId) {
        this.entryPointId = entryPointId;
    }
    public String getFinalResultType() {
        return this.finalResultType;
    }
    
    public void setFinalResultType(String finalResultType) {
        this.finalResultType = finalResultType;
    }
    public String getPerformedBy() {
        return this.performedBy;
    }
    
    public void setPerformedBy(String performedBy) {
        this.performedBy = performedBy;
    }
    public String getNotified() {
        return this.notified;
    }
    
    public void setNotified(String notified) {
        this.notified = notified;
    }




}


