package com.vmmc.entities;
// Generated May 24, 2020 9:48:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HtcHivresult generated by hbm2java
 */
public class HtcHivresult  implements java.io.Serializable {


     private Long id;
     private String opdnumber;
     private String htcnumber;
     private String testKit;
     private String lotNumber;
     private Boolean isRetest;
     private Integer testCategory;
     private String result;
     private Date expireDate;
     private String starttime;
     private String readingtime;
     private Date dob;
     private String sex;
     private Date dateofRegistration;

    public HtcHivresult() {
    }

    public HtcHivresult(String opdnumber, String htcnumber, String testKit, String lotNumber, Boolean isRetest, Integer testCategory, String result, Date expireDate, String starttime, String readingtime, Date dob, String sex, Date dateofRegistration) {
       this.opdnumber = opdnumber;
       this.htcnumber = htcnumber;
       this.testKit = testKit;
       this.lotNumber = lotNumber;
       this.isRetest = isRetest;
       this.testCategory = testCategory;
       this.result = result;
       this.expireDate = expireDate;
       this.starttime = starttime;
       this.readingtime = readingtime;
       this.dob = dob;
       this.sex = sex;
       this.dateofRegistration = dateofRegistration;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public String getHtcnumber() {
        return this.htcnumber;
    }
    
    public void setHtcnumber(String htcnumber) {
        this.htcnumber = htcnumber;
    }
    public String getTestKit() {
        return this.testKit;
    }
    
    public void setTestKit(String testKit) {
        this.testKit = testKit;
    }
    public String getLotNumber() {
        return this.lotNumber;
    }
    
    public void setLotNumber(String lotNumber) {
        this.lotNumber = lotNumber;
    }
    public Boolean getIsRetest() {
        return this.isRetest;
    }
    
    public void setIsRetest(Boolean isRetest) {
        this.isRetest = isRetest;
    }
    public Integer getTestCategory() {
        return this.testCategory;
    }
    
    public void setTestCategory(Integer testCategory) {
        this.testCategory = testCategory;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
    public String getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }
    public String getReadingtime() {
        return this.readingtime;
    }
    
    public void setReadingtime(String readingtime) {
        this.readingtime = readingtime;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Date getDateofRegistration() {
        return this.dateofRegistration;
    }
    
    public void setDateofRegistration(Date dateofRegistration) {
        this.dateofRegistration = dateofRegistration;
    }




}


