package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * HtcTesttype generated by hbm2java
 */
public class HtcTesttype  implements java.io.Serializable {


     private Integer id;
     private String testName;

    public HtcTesttype() {
    }

    public HtcTesttype(String testName) {
       this.testName = testName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTestName() {
        return this.testName;
    }
    
    public void setTestName(String testName) {
        this.testName = testName;
    }




}


