package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * HtsEntrypoint generated by hbm2java
 */
public class HtsEntrypoint  implements java.io.Serializable {


     private Integer id;
     private String description;
     private String type;

    public HtsEntrypoint() {
    }

    public HtsEntrypoint(String description, String type) {
       this.description = description;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


