package com.vmmc.entities;
// Generated Jun 22, 2020 11:20:08 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Laboratory generated by hbm2java
 */
public class Laboratory  implements java.io.Serializable {


     private int id;
     private String patientId;
     private String testType;
     private Date testDate;
     private Date receivedDate;
     private Date patientReceivedDate;
     private Integer result;

    public Laboratory() {
    }

	
    public Laboratory(int id) {
        this.id = id;
    }
    public Laboratory(int id, String patientId, String testType, Date testDate, Date receivedDate, Date patientReceivedDate, Integer result) {
       this.id = id;
       this.patientId = patientId;
       this.testType = testType;
       this.testDate = testDate;
       this.receivedDate = receivedDate;
       this.patientReceivedDate = patientReceivedDate;
       this.result = result;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public String getTestType() {
        return this.testType;
    }
    
    public void setTestType(String testType) {
        this.testType = testType;
    }
    public Date getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }
    public Date getReceivedDate() {
        return this.receivedDate;
    }
    
    public void setReceivedDate(Date receivedDate) {
        this.receivedDate = receivedDate;
    }
    public Date getPatientReceivedDate() {
        return this.patientReceivedDate;
    }
    
    public void setPatientReceivedDate(Date patientReceivedDate) {
        this.patientReceivedDate = patientReceivedDate;
    }
    public Integer getResult() {
        return this.result;
    }
    
    public void setResult(Integer result) {
        this.result = result;
    }

    @Override
    public String toString() {
        return "Laboratory{" + "id=" + id + ", patientId=" + patientId + ", testType=" + testType + ", testDate=" + testDate + ", receivedDate=" + receivedDate + ", patientReceivedDate=" + patientReceivedDate + ", result=" + result + '}';
    }




}


