package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Linkages generated by hbm2java
 */
public class Linkages  implements java.io.Serializable {


     private Integer id;
     private int patientId;
     private String opdnumber;
     private String referredTo;
     private Date referredToDate;
     private String referredFrom;
     private Date referredFromDate;

    public Linkages() {
    }

    public Linkages(int patientId, String opdnumber, String referredTo, Date referredToDate, String referredFrom, Date referredFromDate) {
       this.patientId = patientId;
       this.opdnumber = opdnumber;
       this.referredTo = referredTo;
       this.referredToDate = referredToDate;
       this.referredFrom = referredFrom;
       this.referredFromDate = referredFromDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(int patientId) {
        this.patientId = patientId;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public String getReferredTo() {
        return this.referredTo;
    }
    
    public void setReferredTo(String referredTo) {
        this.referredTo = referredTo;
    }
    public Date getReferredToDate() {
        return this.referredToDate;
    }
    
    public void setReferredToDate(Date referredToDate) {
        this.referredToDate = referredToDate;
    }
    public String getReferredFrom() {
        return this.referredFrom;
    }
    
    public void setReferredFrom(String referredFrom) {
        this.referredFrom = referredFrom;
    }
    public Date getReferredFromDate() {
        return this.referredFromDate;
    }
    
    public void setReferredFromDate(Date referredFromDate) {
        this.referredFromDate = referredFromDate;
    }




}


