package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Locks generated by hbm2java
 */
public class Locks  implements java.io.Serializable {


     private String lockedPatientId;
     private String lockByMachine;
     private String lockByForm;

    public Locks() {
    }

	
    public Locks(String lockedPatientId) {
        this.lockedPatientId = lockedPatientId;
    }
    public Locks(String lockedPatientId, String lockByMachine, String lockByForm) {
       this.lockedPatientId = lockedPatientId;
       this.lockByMachine = lockByMachine;
       this.lockByForm = lockByForm;
    }
   
    public String getLockedPatientId() {
        return this.lockedPatientId;
    }
    
    public void setLockedPatientId(String lockedPatientId) {
        this.lockedPatientId = lockedPatientId;
    }
    public String getLockByMachine() {
        return this.lockByMachine;
    }
    
    public void setLockByMachine(String lockByMachine) {
        this.lockByMachine = lockByMachine;
    }
    public String getLockByForm() {
        return this.lockByForm;
    }
    
    public void setLockByForm(String lockByForm) {
        this.lockByForm = lockByForm;
    }




}


