package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Merge generated by hbm2java
 */
public class Merge  implements java.io.Serializable {


     private Integer id;
     private String opdnumber;

    public Merge() {
    }

    public Merge(String opdnumber) {
       this.opdnumber = opdnumber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }




}


