package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Modulerole generated by hbm2java
 */
public class Modulerole  implements java.io.Serializable {


     private int id;
     private Integer moduleId;
     private Integer roleId;

    public Modulerole() {
    }

	
    public Modulerole(int id) {
        this.id = id;
    }
    public Modulerole(int id, Integer moduleId, Integer roleId) {
       this.id = id;
       this.moduleId = moduleId;
       this.roleId = roleId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }




}


