package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Module generated by hbm2java
 */
public class Module  implements java.io.Serializable {


     private int id;
     private String moduleName;
     private String folderPath;

    public Module() {
    }

	
    public Module(int id) {
        this.id = id;
    }
    public Module(int id, String moduleName, String folderPath) {
       this.id = id;
       this.moduleName = moduleName;
       this.folderPath = folderPath;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getModuleName() {
        return this.moduleName;
    }
    
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }
    public String getFolderPath() {
        return this.folderPath;
    }
    
    public void setFolderPath(String folderPath) {
        this.folderPath = folderPath;
    }




}


