package com.vmmc.entities;
// Generated Jul 8, 2020 11:10:29 AM by Hibernate Tools 4.3.1



/**
 * Nationality generated by hbm2java
 */
public class Nationality  implements java.io.Serializable {


     private int nationalityId;
     private String name;

    public Nationality() {
    }

	
    public Nationality(int nationalityId) {
        this.nationalityId = nationalityId;
    }
    public Nationality(int nationalityId, String name) {
       this.nationalityId = nationalityId;
       this.name = name;
    }
   
    public int getNationalityId() {
        return this.nationalityId;
    }
    
    public void setNationalityId(int nationalityId) {
        this.nationalityId = nationalityId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


