package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Nextofkin generated by hbm2java
 */
public class Nextofkin  implements java.io.Serializable {


     private Integer id;
     private Integer patientId;
     private String opdnumber;
     private String firstName;
     private String lastName;
     private String physicalAddress;
     private String contactNumber;
     private String relationType;
     private String chief;
     private String kraal;
     private String village;
     private String school;
     private String clinic;

    public Nextofkin() {
    }

    public Nextofkin(Integer patientId, String opdnumber, String firstName, String lastName, String physicalAddress, String contactNumber, String relationType, String chief, String kraal, String village, String school, String clinic) {
       this.patientId = patientId;
       this.opdnumber = opdnumber;
       this.firstName = firstName;
       this.lastName = lastName;
       this.physicalAddress = physicalAddress;
       this.contactNumber = contactNumber;
       this.relationType = relationType;
       this.chief = chief;
       this.kraal = kraal;
       this.village = village;
       this.school = school;
       this.clinic = clinic;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPhysicalAddress() {
        return this.physicalAddress;
    }
    
    public void setPhysicalAddress(String physicalAddress) {
        this.physicalAddress = physicalAddress;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }
    public String getRelationType() {
        return this.relationType;
    }
    
    public void setRelationType(String relationType) {
        this.relationType = relationType;
    }
    public String getChief() {
        return this.chief;
    }
    
    public void setChief(String chief) {
        this.chief = chief;
    }
    public String getKraal() {
        return this.kraal;
    }
    
    public void setKraal(String kraal) {
        this.kraal = kraal;
    }
    public String getVillage() {
        return this.village;
    }
    
    public void setVillage(String village) {
        this.village = village;
    }
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    public String getClinic() {
        return this.clinic;
    }
    
    public void setClinic(String clinic) {
        this.clinic = clinic;
    }




}


