package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Noderole generated by hbm2java
 */
public class Noderole  implements java.io.Serializable {


     private int id;
     private Integer nodeId;
     private Integer roleId;
     private Boolean viewAllowed;
     private Boolean editAllowed;

    public Noderole() {
    }

	
    public Noderole(int id) {
        this.id = id;
    }
    public Noderole(int id, Integer nodeId, Integer roleId, Boolean viewAllowed, Boolean editAllowed) {
       this.id = id;
       this.nodeId = nodeId;
       this.roleId = roleId;
       this.viewAllowed = viewAllowed;
       this.editAllowed = editAllowed;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getNodeId() {
        return this.nodeId;
    }
    
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public Boolean getViewAllowed() {
        return this.viewAllowed;
    }
    
    public void setViewAllowed(Boolean viewAllowed) {
        this.viewAllowed = viewAllowed;
    }
    public Boolean getEditAllowed() {
        return this.editAllowed;
    }
    
    public void setEditAllowed(Boolean editAllowed) {
        this.editAllowed = editAllowed;
    }




}


