package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Node generated by hbm2java
 */
public class Node  implements java.io.Serializable {


     private int id;
     private Integer moduleId;
     private String title;
     private String filePath;
     private String description;
     private Integer pageId;

    public Node() {
    }

	
    public Node(int id) {
        this.id = id;
    }
    public Node(int id, Integer moduleId, String title, String filePath, String description, Integer pageId) {
       this.id = id;
       this.moduleId = moduleId;
       this.title = title;
       this.filePath = filePath;
       this.description = description;
       this.pageId = pageId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getPageId() {
        return this.pageId;
    }
    
    public void setPageId(Integer pageId) {
        this.pageId = pageId;
    }




}


