package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PatientStatus generated by hbm2java
 */
public class PatientStatus  implements java.io.Serializable {


     private Integer id;
     private Integer patientId;
     private String opdnumber;
     private Integer statusTypeId;
     private Date date;

    public PatientStatus() {
    }

    public PatientStatus(Integer patientId, String opdnumber, Integer statusTypeId, Date date) {
       this.patientId = patientId;
       this.opdnumber = opdnumber;
       this.statusTypeId = statusTypeId;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public Integer getStatusTypeId() {
        return this.statusTypeId;
    }
    
    public void setStatusTypeId(Integer statusTypeId) {
        this.statusTypeId = statusTypeId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


