package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * PatientDiagnosis generated by hbm2java
 */
public class PatientDiagnosis  implements java.io.Serializable {


     private Integer id;
     private String opdnumber;
     private String vmmcid;
     private Integer diagnosisTypeId;
     private String diagnosisDescription;
     private String specifyOtherDiagnosis;

    public PatientDiagnosis() {
    }

    public PatientDiagnosis(String opdnumber, String vmmcid, Integer diagnosisTypeId, String diagnosisDescription, String specifyOtherDiagnosis) {
       this.opdnumber = opdnumber;
       this.vmmcid = vmmcid;
       this.diagnosisTypeId = diagnosisTypeId;
       this.diagnosisDescription = diagnosisDescription;
       this.specifyOtherDiagnosis = specifyOtherDiagnosis;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }
    public Integer getDiagnosisTypeId() {
        return this.diagnosisTypeId;
    }
    
    public void setDiagnosisTypeId(Integer diagnosisTypeId) {
        this.diagnosisTypeId = diagnosisTypeId;
    }
    public String getDiagnosisDescription() {
        return this.diagnosisDescription;
    }
    
    public void setDiagnosisDescription(String diagnosisDescription) {
        this.diagnosisDescription = diagnosisDescription;
    }
    public String getSpecifyOtherDiagnosis() {
        return this.specifyOtherDiagnosis;
    }
    
    public void setSpecifyOtherDiagnosis(String specifyOtherDiagnosis) {
        this.specifyOtherDiagnosis = specifyOtherDiagnosis;
    }




}


