package com.vmmc.entities;
// Generated Jul 10, 2020 9:57:12 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private String opdnumber;
     private String firstName;
     private String lastName;
     private String nationality;
     private String type;
     private String nationalId;
     private Float age;
     private String sex;
     private String facilityCode;
     private Date registrationDate;
     private String maritalStatus;
     private String educationalLevel;
     private String occupation;
     private Date dob;
     private String vmmcId;
     private String htsId;
     private String tbId;
     private String patientId;
     private String stiId;
     private String ophanStatus;
     private Date dateOfDeath;
     private String religion;
     private String fileRef;

    public Patient() {
    }

	
    public Patient(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public Patient(String opdnumber, String firstName, String lastName, String nationality, String type, String nationalId, Float age, String sex, String facilityCode, Date registrationDate, String maritalStatus, String educationalLevel, String occupation, Date dob, String vmmcId, String htsId, String tbId, String patientId, String stiId, String ophanStatus, Date dateOfDeath, String religion, String fileRef) {
       this.opdnumber = opdnumber;
       this.firstName = firstName;
       this.lastName = lastName;
       this.nationality = nationality;
       this.type = type;
       this.nationalId = nationalId;
       this.age = age;
       this.sex = sex;
       this.facilityCode = facilityCode;
       this.registrationDate = registrationDate;
       this.maritalStatus = maritalStatus;
       this.educationalLevel = educationalLevel;
       this.occupation = occupation;
       this.dob = dob;
       this.vmmcId = vmmcId;
       this.htsId = htsId;
       this.tbId = tbId;
       this.patientId = patientId;
       this.stiId = stiId;
       this.ophanStatus = ophanStatus;
       this.dateOfDeath = dateOfDeath;
       this.religion = religion;
       this.fileRef = fileRef;
    }
   
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getNationalId() {
        return this.nationalId;
    }
    
    public void setNationalId(String nationalId) {
        this.nationalId = nationalId;
    }
    public Float getAge() {
        return this.age;
    }
    
    public void setAge(Float age) {
        this.age = age;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getFacilityCode() {
        return this.facilityCode;
    }
    
    public void setFacilityCode(String facilityCode) {
        this.facilityCode = facilityCode;
    }
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public String getEducationalLevel() {
        return this.educationalLevel;
    }
    
    public void setEducationalLevel(String educationalLevel) {
        this.educationalLevel = educationalLevel;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getVmmcId() {
        return this.vmmcId;
    }
    
    public void setVmmcId(String vmmcId) {
        this.vmmcId = vmmcId;
    }
    public String getHtsId() {
        return this.htsId;
    }
    
    public void setHtsId(String htsId) {
        this.htsId = htsId;
    }
    public String getTbId() {
        return this.tbId;
    }
    
    public void setTbId(String tbId) {
        this.tbId = tbId;
    }
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public String getStiId() {
        return this.stiId;
    }
    
    public void setStiId(String stiId) {
        this.stiId = stiId;
    }
    public String getOphanStatus() {
        return this.ophanStatus;
    }
    
    public void setOphanStatus(String ophanStatus) {
        this.ophanStatus = ophanStatus;
    }
    public Date getDateOfDeath() {
        return this.dateOfDeath;
    }
    
    public void setDateOfDeath(Date dateOfDeath) {
        this.dateOfDeath = dateOfDeath;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String getFileRef() {
        return this.fileRef;
    }
    
    public void setFileRef(String fileRef) {
        this.fileRef = fileRef;
    }




}


