package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * PatientAddress generated by hbm2java
 */
public class PatientAddress  implements java.io.Serializable {


     private Integer id;
     private Integer patientId;
     private String opdnumber;
     private String physicalAddress;
     private String chief;
     private String kraal;
     private String school;
     private String village;
     private String clinic;
     private String mobileNumber;
     private String telNumber;
     private String workTelNumber;
     private String workAddress;

    public PatientAddress() {
    }

    public PatientAddress(Integer patientId, String opdnumber, String physicalAddress, String chief, String kraal, String school, String village, String clinic, String mobileNumber, String telNumber, String workTelNumber, String workAddress) {
       this.patientId = patientId;
       this.opdnumber = opdnumber;
       this.physicalAddress = physicalAddress;
       this.chief = chief;
       this.kraal = kraal;
       this.school = school;
       this.village = village;
       this.clinic = clinic;
       this.mobileNumber = mobileNumber;
       this.telNumber = telNumber;
       this.workTelNumber = workTelNumber;
       this.workAddress = workAddress;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public String getPhysicalAddress() {
        return this.physicalAddress;
    }
    
    public void setPhysicalAddress(String physicalAddress) {
        this.physicalAddress = physicalAddress;
    }
    public String getChief() {
        return this.chief;
    }
    
    public void setChief(String chief) {
        this.chief = chief;
    }
    public String getKraal() {
        return this.kraal;
    }
    
    public void setKraal(String kraal) {
        this.kraal = kraal;
    }
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    public String getVillage() {
        return this.village;
    }
    
    public void setVillage(String village) {
        this.village = village;
    }
    public String getClinic() {
        return this.clinic;
    }
    
    public void setClinic(String clinic) {
        this.clinic = clinic;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getTelNumber() {
        return this.telNumber;
    }
    
    public void setTelNumber(String telNumber) {
        this.telNumber = telNumber;
    }
    public String getWorkTelNumber() {
        return this.workTelNumber;
    }
    
    public void setWorkTelNumber(String workTelNumber) {
        this.workTelNumber = workTelNumber;
    }
    public String getWorkAddress() {
        return this.workAddress;
    }
    
    public void setWorkAddress(String workAddress) {
        this.workAddress = workAddress;
    }




}


