package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Proceduretype generated by hbm2java
 */
public class Proceduretype  implements java.io.Serializable {


     private int id;
     private String procedureName;

    public Proceduretype() {
    }

	
    public Proceduretype(int id) {
        this.id = id;
    }
    public Proceduretype(int id, String procedureName) {
       this.id = id;
       this.procedureName = procedureName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getProcedureName() {
        return this.procedureName;
    }
    
    public void setProcedureName(String procedureName) {
        this.procedureName = procedureName;
    }




}


