package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Province generated by hbm2java
 */
public class Province  implements java.io.Serializable {


     private String provinceName;
     private int id;
     private String provinceCode;

    public Province() {
    }

	
    public Province(String provinceName, int id) {
        this.provinceName = provinceName;
        this.id = id;
    }
    public Province(String provinceName, int id, String provinceCode) {
       this.provinceName = provinceName;
       this.id = id;
       this.provinceCode = provinceCode;
    }
   
    public String getProvinceName() {
        return this.provinceName;
    }
    
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getProvinceCode() {
        return this.provinceCode;
    }
    
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }




}


