package com.vmmc.entities;
// Generated Jun 18, 2020 8:58:48 AM by Hibernate Tools 4.3.1



/**
 * Reportdates generated by hbm2java
 */
public class Reportdates  implements java.io.Serializable {


     private int id;
     private String startDate;
     private String end;

    public Reportdates() {
    }

	
    public Reportdates(int id) {
        this.id = id;
    }
    public Reportdates(int id, String startDate, String end) {
       this.id = id;
       this.startDate = startDate;
       this.end = end;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
    public String getEnd() {
        return this.end;
    }
    
    public void setEnd(String end) {
        this.end = end;
    }

    @Override
    public String toString() {
        return "Reportdates{" + "id=" + id + ", startDate=" + startDate + ", end=" + end + '}';
    }




}


