package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Riskreductionplantype generated by hbm2java
 */
public class Riskreductionplantype  implements java.io.Serializable {


     private int id;
     private String riskReductionName;

    public Riskreductionplantype() {
    }

	
    public Riskreductionplantype(int id) {
        this.id = id;
    }
    public Riskreductionplantype(int id, String riskReductionName) {
       this.id = id;
       this.riskReductionName = riskReductionName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRiskReductionName() {
        return this.riskReductionName;
    }
    
    public void setRiskReductionName(String riskReductionName) {
        this.riskReductionName = riskReductionName;
    }




}


