package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private String roleId;
     private String name;
     private Integer permissionLevel;

    public Role() {
    }

	
    public Role(String roleId) {
        this.roleId = roleId;
    }
    public Role(String roleId, String name, Integer permissionLevel) {
       this.roleId = roleId;
       this.name = name;
       this.permissionLevel = permissionLevel;
    }
   
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getPermissionLevel() {
        return this.permissionLevel;
    }
    
    public void setPermissionLevel(Integer permissionLevel) {
        this.permissionLevel = permissionLevel;
    }




}


