package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Securityaccesslevels generated by hbm2java
 */
public class Securityaccesslevels  implements java.io.Serializable {


     private int accessLevel;
     private String description;
     private Byte enterSecurity;
     private Byte enterUtilities;
     private Byte enterPrintouts;
     private Byte enterSetup;
     private Byte enterDataEntryDispensing;
     private Byte enterDataEntry;
     private Byte enterPrintoutsSpecial;

    public Securityaccesslevels() {
    }

	
    public Securityaccesslevels(int accessLevel) {
        this.accessLevel = accessLevel;
    }
    public Securityaccesslevels(int accessLevel, String description, Byte enterSecurity, Byte enterUtilities, Byte enterPrintouts, Byte enterSetup, Byte enterDataEntryDispensing, Byte enterDataEntry, Byte enterPrintoutsSpecial) {
       this.accessLevel = accessLevel;
       this.description = description;
       this.enterSecurity = enterSecurity;
       this.enterUtilities = enterUtilities;
       this.enterPrintouts = enterPrintouts;
       this.enterSetup = enterSetup;
       this.enterDataEntryDispensing = enterDataEntryDispensing;
       this.enterDataEntry = enterDataEntry;
       this.enterPrintoutsSpecial = enterPrintoutsSpecial;
    }
   
    public int getAccessLevel() {
        return this.accessLevel;
    }
    
    public void setAccessLevel(int accessLevel) {
        this.accessLevel = accessLevel;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Byte getEnterSecurity() {
        return this.enterSecurity;
    }
    
    public void setEnterSecurity(Byte enterSecurity) {
        this.enterSecurity = enterSecurity;
    }
    public Byte getEnterUtilities() {
        return this.enterUtilities;
    }
    
    public void setEnterUtilities(Byte enterUtilities) {
        this.enterUtilities = enterUtilities;
    }
    public Byte getEnterPrintouts() {
        return this.enterPrintouts;
    }
    
    public void setEnterPrintouts(Byte enterPrintouts) {
        this.enterPrintouts = enterPrintouts;
    }
    public Byte getEnterSetup() {
        return this.enterSetup;
    }
    
    public void setEnterSetup(Byte enterSetup) {
        this.enterSetup = enterSetup;
    }
    public Byte getEnterDataEntryDispensing() {
        return this.enterDataEntryDispensing;
    }
    
    public void setEnterDataEntryDispensing(Byte enterDataEntryDispensing) {
        this.enterDataEntryDispensing = enterDataEntryDispensing;
    }
    public Byte getEnterDataEntry() {
        return this.enterDataEntry;
    }
    
    public void setEnterDataEntry(Byte enterDataEntry) {
        this.enterDataEntry = enterDataEntry;
    }
    public Byte getEnterPrintoutsSpecial() {
        return this.enterPrintoutsSpecial;
    }
    
    public void setEnterPrintoutsSpecial(Byte enterPrintoutsSpecial) {
        this.enterPrintoutsSpecial = enterPrintoutsSpecial;
    }




}


