package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Securityusers generated by hbm2java
 */
public class Securityusers  implements java.io.Serializable {


     private int userNumber;
     private String fullName;
     private String loginName;
     private String password;
     private Integer accessLevel;
     private Integer active;

    public Securityusers() {
    }

	
    public Securityusers(int userNumber) {
        this.userNumber = userNumber;
    }
    public Securityusers(int userNumber, String fullName, String loginName, String password, Integer accessLevel, Integer active) {
       this.userNumber = userNumber;
       this.fullName = fullName;
       this.loginName = loginName;
       this.password = password;
       this.accessLevel = accessLevel;
       this.active = active;
    }
   
    public int getUserNumber() {
        return this.userNumber;
    }
    
    public void setUserNumber(int userNumber) {
        this.userNumber = userNumber;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getAccessLevel() {
        return this.accessLevel;
    }
    
    public void setAccessLevel(Integer accessLevel) {
        this.accessLevel = accessLevel;
    }
    public Integer getActive() {
        return this.active;
    }
    
    public void setActive(Integer active) {
        this.active = active;
    }




}


