package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Setupstaff generated by hbm2java
 */
public class Setupstaff  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String firstName;
     private String lastName;
     private String userRole;

    public Setupstaff() {
    }

    public Setupstaff(String userName, String firstName, String lastName, String userRole) {
       this.userName = userName;
       this.firstName = firstName;
       this.lastName = lastName;
       this.userRole = userRole;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }




}


