package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Setupclinicians generated by hbm2java
 */
public class Setupclinicians  implements java.io.Serializable {


     private Integer id;
     private String fistName;
     private String surname;
     private String idnumber;

    public Setupclinicians() {
    }

    public Setupclinicians(String fistName, String surname, String idnumber) {
       this.fistName = fistName;
       this.surname = surname;
       this.idnumber = idnumber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFistName() {
        return this.fistName;
    }
    
    public void setFistName(String fistName) {
        this.fistName = fistName;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getIdnumber() {
        return this.idnumber;
    }
    
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }




}


