package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * SetupreferredTo generated by hbm2java
 */
public class SetupreferredTo  implements java.io.Serializable {


     private int id;
     private String description;

    public SetupreferredTo() {
    }

	
    public SetupreferredTo(int id) {
        this.id = id;
    }
    public SetupreferredTo(int id, String description) {
       this.id = id;
       this.description = description;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


