package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Setupreferredfrom generated by hbm2java
 */
public class Setupreferredfrom  implements java.io.Serializable {


     private Integer id;
     private String referredFromName;

    public Setupreferredfrom() {
    }

    public Setupreferredfrom(String referredFromName) {
       this.referredFromName = referredFromName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getReferredFromName() {
        return this.referredFromName;
    }
    
    public void setReferredFromName(String referredFromName) {
        this.referredFromName = referredFromName;
    }




}


