package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Setupmedicalaidsocities generated by hbm2java
 */
public class Setupmedicalaidsocities  implements java.io.Serializable {


     private Integer id;
     private String medicalAidName;
     private String address;

    public Setupmedicalaidsocities() {
    }

    public Setupmedicalaidsocities(String medicalAidName, String address) {
       this.medicalAidName = medicalAidName;
       this.address = address;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMedicalAidName() {
        return this.medicalAidName;
    }
    
    public void setMedicalAidName(String medicalAidName) {
        this.medicalAidName = medicalAidName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


