package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Setupriskreductionplan generated by hbm2java
 */
public class Setupriskreductionplan  implements java.io.Serializable {


     private Integer id;
     private String riskReductionPlanName;

    public Setupriskreductionplan() {
    }

    public Setupriskreductionplan(String riskReductionPlanName) {
       this.riskReductionPlanName = riskReductionPlanName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRiskReductionPlanName() {
        return this.riskReductionPlanName;
    }
    
    public void setRiskReductionPlanName(String riskReductionPlanName) {
        this.riskReductionPlanName = riskReductionPlanName;
    }




}


