package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Statustype generated by hbm2java
 */
public class Statustype  implements java.io.Serializable {


     private Integer id;
     private String statusName;

    public Statustype() {
    }

    public Statustype(String statusName) {
       this.statusName = statusName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStatusName() {
        return this.statusName;
    }
    
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }




}


