package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sti generated by hbm2java
 */
public class Sti  implements java.io.Serializable {


     private String stinumber;
     private String opdnumber;
     private Date dateOfRegistration;
     private String complaints;
     private String sexualHistory;
     private String episode;
     private String stisyndrome;
     private String examinations;
     private String testedForSyphilis;
     private String purposeOfSyphilisTesting;
     private String syphilisTestResult;
     private String treatment;
     private String testedForHiv;
     private String stiContactSlipIssued;
     private String stiContactSlipReceived;
     private String syphilisResult;
     private String screenedForSyphilis;
     private String syphilisTreated;
     private String hivTestResult;
     private String condomInformationGiven;
     private String condomsIssued;
     private String comments;
     private String entryPoint;
     private String deliveryOutcome;
     private String ancBookingTime;
     private String ancTestedForSyphilis;
     private String ancSyphilisTestResults;
     private String ancSyphilisTreated;
     private String ancSyphillisTreatment;
     private String ancTestedDuringPregnancy;
     private Date ancDateTestedSyphDuriPreg;
     private String ancSyphTestedBeforeResult;
     private String ancSyphTreatedBefore;
     private Date ancDeliveryDate;
     private String stiInfectionType;
     private String ancSyphilisResult;
     private String hivtestedBefore;
     private String hivtestedBeforeResult;

    public Sti() {
    }

	
    public Sti(String stinumber, String opdnumber) {
        this.stinumber = stinumber;
        this.opdnumber = opdnumber;
    }
    public Sti(String stinumber, String opdnumber, Date dateOfRegistration, String complaints, String sexualHistory, String episode, String stisyndrome, String examinations, String testedForSyphilis, String purposeOfSyphilisTesting, String syphilisTestResult, String treatment, String testedForHiv, String stiContactSlipIssued, String stiContactSlipReceived, String syphilisResult, String screenedForSyphilis, String syphilisTreated, String hivTestResult, String condomInformationGiven, String condomsIssued, String comments, String entryPoint, String deliveryOutcome, String ancBookingTime, String ancTestedForSyphilis, String ancSyphilisTestResults, String ancSyphilisTreated, String ancSyphillisTreatment, String ancTestedDuringPregnancy, Date ancDateTestedSyphDuriPreg, String ancSyphTestedBeforeResult, String ancSyphTreatedBefore, Date ancDeliveryDate, String stiInfectionType, String ancSyphilisResult, String hivtestedBefore, String hivtestedBeforeResult) {
       this.stinumber = stinumber;
       this.opdnumber = opdnumber;
       this.dateOfRegistration = dateOfRegistration;
       this.complaints = complaints;
       this.sexualHistory = sexualHistory;
       this.episode = episode;
       this.stisyndrome = stisyndrome;
       this.examinations = examinations;
       this.testedForSyphilis = testedForSyphilis;
       this.purposeOfSyphilisTesting = purposeOfSyphilisTesting;
       this.syphilisTestResult = syphilisTestResult;
       this.treatment = treatment;
       this.testedForHiv = testedForHiv;
       this.stiContactSlipIssued = stiContactSlipIssued;
       this.stiContactSlipReceived = stiContactSlipReceived;
       this.syphilisResult = syphilisResult;
       this.screenedForSyphilis = screenedForSyphilis;
       this.syphilisTreated = syphilisTreated;
       this.hivTestResult = hivTestResult;
       this.condomInformationGiven = condomInformationGiven;
       this.condomsIssued = condomsIssued;
       this.comments = comments;
       this.entryPoint = entryPoint;
       this.deliveryOutcome = deliveryOutcome;
       this.ancBookingTime = ancBookingTime;
       this.ancTestedForSyphilis = ancTestedForSyphilis;
       this.ancSyphilisTestResults = ancSyphilisTestResults;
       this.ancSyphilisTreated = ancSyphilisTreated;
       this.ancSyphillisTreatment = ancSyphillisTreatment;
       this.ancTestedDuringPregnancy = ancTestedDuringPregnancy;
       this.ancDateTestedSyphDuriPreg = ancDateTestedSyphDuriPreg;
       this.ancSyphTestedBeforeResult = ancSyphTestedBeforeResult;
       this.ancSyphTreatedBefore = ancSyphTreatedBefore;
       this.ancDeliveryDate = ancDeliveryDate;
       this.stiInfectionType = stiInfectionType;
       this.ancSyphilisResult = ancSyphilisResult;
       this.hivtestedBefore = hivtestedBefore;
       this.hivtestedBeforeResult = hivtestedBeforeResult;
    }
   
    public String getStinumber() {
        return this.stinumber;
    }
    
    public void setStinumber(String stinumber) {
        this.stinumber = stinumber;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public Date getDateOfRegistration() {
        return this.dateOfRegistration;
    }
    
    public void setDateOfRegistration(Date dateOfRegistration) {
        this.dateOfRegistration = dateOfRegistration;
    }
    public String getComplaints() {
        return this.complaints;
    }
    
    public void setComplaints(String complaints) {
        this.complaints = complaints;
    }
    public String getSexualHistory() {
        return this.sexualHistory;
    }
    
    public void setSexualHistory(String sexualHistory) {
        this.sexualHistory = sexualHistory;
    }
    public String getEpisode() {
        return this.episode;
    }
    
    public void setEpisode(String episode) {
        this.episode = episode;
    }
    public String getStisyndrome() {
        return this.stisyndrome;
    }
    
    public void setStisyndrome(String stisyndrome) {
        this.stisyndrome = stisyndrome;
    }
    public String getExaminations() {
        return this.examinations;
    }
    
    public void setExaminations(String examinations) {
        this.examinations = examinations;
    }
    public String getTestedForSyphilis() {
        return this.testedForSyphilis;
    }
    
    public void setTestedForSyphilis(String testedForSyphilis) {
        this.testedForSyphilis = testedForSyphilis;
    }
    public String getPurposeOfSyphilisTesting() {
        return this.purposeOfSyphilisTesting;
    }
    
    public void setPurposeOfSyphilisTesting(String purposeOfSyphilisTesting) {
        this.purposeOfSyphilisTesting = purposeOfSyphilisTesting;
    }
    public String getSyphilisTestResult() {
        return this.syphilisTestResult;
    }
    
    public void setSyphilisTestResult(String syphilisTestResult) {
        this.syphilisTestResult = syphilisTestResult;
    }
    public String getTreatment() {
        return this.treatment;
    }
    
    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }
    public String getTestedForHiv() {
        return this.testedForHiv;
    }
    
    public void setTestedForHiv(String testedForHiv) {
        this.testedForHiv = testedForHiv;
    }
    public String getStiContactSlipIssued() {
        return this.stiContactSlipIssued;
    }
    
    public void setStiContactSlipIssued(String stiContactSlipIssued) {
        this.stiContactSlipIssued = stiContactSlipIssued;
    }
    public String getStiContactSlipReceived() {
        return this.stiContactSlipReceived;
    }
    
    public void setStiContactSlipReceived(String stiContactSlipReceived) {
        this.stiContactSlipReceived = stiContactSlipReceived;
    }
    public String getSyphilisResult() {
        return this.syphilisResult;
    }
    
    public void setSyphilisResult(String syphilisResult) {
        this.syphilisResult = syphilisResult;
    }
    public String getScreenedForSyphilis() {
        return this.screenedForSyphilis;
    }
    
    public void setScreenedForSyphilis(String screenedForSyphilis) {
        this.screenedForSyphilis = screenedForSyphilis;
    }
    public String getSyphilisTreated() {
        return this.syphilisTreated;
    }
    
    public void setSyphilisTreated(String syphilisTreated) {
        this.syphilisTreated = syphilisTreated;
    }
    public String getHivTestResult() {
        return this.hivTestResult;
    }
    
    public void setHivTestResult(String hivTestResult) {
        this.hivTestResult = hivTestResult;
    }
    public String getCondomInformationGiven() {
        return this.condomInformationGiven;
    }
    
    public void setCondomInformationGiven(String condomInformationGiven) {
        this.condomInformationGiven = condomInformationGiven;
    }
    public String getCondomsIssued() {
        return this.condomsIssued;
    }
    
    public void setCondomsIssued(String condomsIssued) {
        this.condomsIssued = condomsIssued;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getEntryPoint() {
        return this.entryPoint;
    }
    
    public void setEntryPoint(String entryPoint) {
        this.entryPoint = entryPoint;
    }
    public String getDeliveryOutcome() {
        return this.deliveryOutcome;
    }
    
    public void setDeliveryOutcome(String deliveryOutcome) {
        this.deliveryOutcome = deliveryOutcome;
    }
    public String getAncBookingTime() {
        return this.ancBookingTime;
    }
    
    public void setAncBookingTime(String ancBookingTime) {
        this.ancBookingTime = ancBookingTime;
    }
    public String getAncTestedForSyphilis() {
        return this.ancTestedForSyphilis;
    }
    
    public void setAncTestedForSyphilis(String ancTestedForSyphilis) {
        this.ancTestedForSyphilis = ancTestedForSyphilis;
    }
    public String getAncSyphilisTestResults() {
        return this.ancSyphilisTestResults;
    }
    
    public void setAncSyphilisTestResults(String ancSyphilisTestResults) {
        this.ancSyphilisTestResults = ancSyphilisTestResults;
    }
    public String getAncSyphilisTreated() {
        return this.ancSyphilisTreated;
    }
    
    public void setAncSyphilisTreated(String ancSyphilisTreated) {
        this.ancSyphilisTreated = ancSyphilisTreated;
    }
    public String getAncSyphillisTreatment() {
        return this.ancSyphillisTreatment;
    }
    
    public void setAncSyphillisTreatment(String ancSyphillisTreatment) {
        this.ancSyphillisTreatment = ancSyphillisTreatment;
    }
    public String getAncTestedDuringPregnancy() {
        return this.ancTestedDuringPregnancy;
    }
    
    public void setAncTestedDuringPregnancy(String ancTestedDuringPregnancy) {
        this.ancTestedDuringPregnancy = ancTestedDuringPregnancy;
    }
    public Date getAncDateTestedSyphDuriPreg() {
        return this.ancDateTestedSyphDuriPreg;
    }
    
    public void setAncDateTestedSyphDuriPreg(Date ancDateTestedSyphDuriPreg) {
        this.ancDateTestedSyphDuriPreg = ancDateTestedSyphDuriPreg;
    }
    public String getAncSyphTestedBeforeResult() {
        return this.ancSyphTestedBeforeResult;
    }
    
    public void setAncSyphTestedBeforeResult(String ancSyphTestedBeforeResult) {
        this.ancSyphTestedBeforeResult = ancSyphTestedBeforeResult;
    }
    public String getAncSyphTreatedBefore() {
        return this.ancSyphTreatedBefore;
    }
    
    public void setAncSyphTreatedBefore(String ancSyphTreatedBefore) {
        this.ancSyphTreatedBefore = ancSyphTreatedBefore;
    }
    public Date getAncDeliveryDate() {
        return this.ancDeliveryDate;
    }
    
    public void setAncDeliveryDate(Date ancDeliveryDate) {
        this.ancDeliveryDate = ancDeliveryDate;
    }
    public String getStiInfectionType() {
        return this.stiInfectionType;
    }
    
    public void setStiInfectionType(String stiInfectionType) {
        this.stiInfectionType = stiInfectionType;
    }
    public String getAncSyphilisResult() {
        return this.ancSyphilisResult;
    }
    
    public void setAncSyphilisResult(String ancSyphilisResult) {
        this.ancSyphilisResult = ancSyphilisResult;
    }
    public String getHivtestedBefore() {
        return this.hivtestedBefore;
    }
    
    public void setHivtestedBefore(String hivtestedBefore) {
        this.hivtestedBefore = hivtestedBefore;
    }
    public String getHivtestedBeforeResult() {
        return this.hivtestedBeforeResult;
    }
    
    public void setHivtestedBeforeResult(String hivtestedBeforeResult) {
        this.hivtestedBeforeResult = hivtestedBeforeResult;
    }




}


