package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StiAncsyphilis generated by hbm2java
 */
public class StiAncsyphilis  implements java.io.Serializable {


     private String stinumber;
     private String opdnumber;
     private Date dateOfRegistration;
     private String screenedForSyphilis;
     private String syphilisResult;
     private String syphilisTreated;
     private String sexualHistory;
     private String episode;
     private String stisyndrome;
     private String testedForSyphilis;
     private String purposeOfSyphilisTesting;
     private String syphilisTestResult;
     private String treatment;
     private String testedForHiv;
     private String hivTestResult;
     private String stiContactSlipIssued;
     private String stiContactSlipReceived;
     private String condomInformationGiven;
     private String condomsIssued;
     private String comments;

    public StiAncsyphilis() {
    }

	
    public StiAncsyphilis(String stinumber, String opdnumber) {
        this.stinumber = stinumber;
        this.opdnumber = opdnumber;
    }
    public StiAncsyphilis(String stinumber, String opdnumber, Date dateOfRegistration, String screenedForSyphilis, String syphilisResult, String syphilisTreated, String sexualHistory, String episode, String stisyndrome, String testedForSyphilis, String purposeOfSyphilisTesting, String syphilisTestResult, String treatment, String testedForHiv, String hivTestResult, String stiContactSlipIssued, String stiContactSlipReceived, String condomInformationGiven, String condomsIssued, String comments) {
       this.stinumber = stinumber;
       this.opdnumber = opdnumber;
       this.dateOfRegistration = dateOfRegistration;
       this.screenedForSyphilis = screenedForSyphilis;
       this.syphilisResult = syphilisResult;
       this.syphilisTreated = syphilisTreated;
       this.sexualHistory = sexualHistory;
       this.episode = episode;
       this.stisyndrome = stisyndrome;
       this.testedForSyphilis = testedForSyphilis;
       this.purposeOfSyphilisTesting = purposeOfSyphilisTesting;
       this.syphilisTestResult = syphilisTestResult;
       this.treatment = treatment;
       this.testedForHiv = testedForHiv;
       this.hivTestResult = hivTestResult;
       this.stiContactSlipIssued = stiContactSlipIssued;
       this.stiContactSlipReceived = stiContactSlipReceived;
       this.condomInformationGiven = condomInformationGiven;
       this.condomsIssued = condomsIssued;
       this.comments = comments;
    }
   
    public String getStinumber() {
        return this.stinumber;
    }
    
    public void setStinumber(String stinumber) {
        this.stinumber = stinumber;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public Date getDateOfRegistration() {
        return this.dateOfRegistration;
    }
    
    public void setDateOfRegistration(Date dateOfRegistration) {
        this.dateOfRegistration = dateOfRegistration;
    }
    public String getScreenedForSyphilis() {
        return this.screenedForSyphilis;
    }
    
    public void setScreenedForSyphilis(String screenedForSyphilis) {
        this.screenedForSyphilis = screenedForSyphilis;
    }
    public String getSyphilisResult() {
        return this.syphilisResult;
    }
    
    public void setSyphilisResult(String syphilisResult) {
        this.syphilisResult = syphilisResult;
    }
    public String getSyphilisTreated() {
        return this.syphilisTreated;
    }
    
    public void setSyphilisTreated(String syphilisTreated) {
        this.syphilisTreated = syphilisTreated;
    }
    public String getSexualHistory() {
        return this.sexualHistory;
    }
    
    public void setSexualHistory(String sexualHistory) {
        this.sexualHistory = sexualHistory;
    }
    public String getEpisode() {
        return this.episode;
    }
    
    public void setEpisode(String episode) {
        this.episode = episode;
    }
    public String getStisyndrome() {
        return this.stisyndrome;
    }
    
    public void setStisyndrome(String stisyndrome) {
        this.stisyndrome = stisyndrome;
    }
    public String getTestedForSyphilis() {
        return this.testedForSyphilis;
    }
    
    public void setTestedForSyphilis(String testedForSyphilis) {
        this.testedForSyphilis = testedForSyphilis;
    }
    public String getPurposeOfSyphilisTesting() {
        return this.purposeOfSyphilisTesting;
    }
    
    public void setPurposeOfSyphilisTesting(String purposeOfSyphilisTesting) {
        this.purposeOfSyphilisTesting = purposeOfSyphilisTesting;
    }
    public String getSyphilisTestResult() {
        return this.syphilisTestResult;
    }
    
    public void setSyphilisTestResult(String syphilisTestResult) {
        this.syphilisTestResult = syphilisTestResult;
    }
    public String getTreatment() {
        return this.treatment;
    }
    
    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }
    public String getTestedForHiv() {
        return this.testedForHiv;
    }
    
    public void setTestedForHiv(String testedForHiv) {
        this.testedForHiv = testedForHiv;
    }
    public String getHivTestResult() {
        return this.hivTestResult;
    }
    
    public void setHivTestResult(String hivTestResult) {
        this.hivTestResult = hivTestResult;
    }
    public String getStiContactSlipIssued() {
        return this.stiContactSlipIssued;
    }
    
    public void setStiContactSlipIssued(String stiContactSlipIssued) {
        this.stiContactSlipIssued = stiContactSlipIssued;
    }
    public String getStiContactSlipReceived() {
        return this.stiContactSlipReceived;
    }
    
    public void setStiContactSlipReceived(String stiContactSlipReceived) {
        this.stiContactSlipReceived = stiContactSlipReceived;
    }
    public String getCondomInformationGiven() {
        return this.condomInformationGiven;
    }
    
    public void setCondomInformationGiven(String condomInformationGiven) {
        this.condomInformationGiven = condomInformationGiven;
    }
    public String getCondomsIssued() {
        return this.condomsIssued;
    }
    
    public void setCondomsIssued(String condomsIssued) {
        this.condomsIssued = condomsIssued;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


