package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StiAncsyphilistreatment generated by hbm2java
 */
public class StiAncsyphilistreatment  implements java.io.Serializable {


     private Integer id;
     private String dose;
     private String stinumber;
     private String frequency;
     private Date dateTreatmentCommenced;
     private Date dateOfDelivery;

    public StiAncsyphilistreatment() {
    }

	
    public StiAncsyphilistreatment(String dose, String stinumber) {
        this.dose = dose;
        this.stinumber = stinumber;
    }
    public StiAncsyphilistreatment(String dose, String stinumber, String frequency, Date dateTreatmentCommenced, Date dateOfDelivery) {
       this.dose = dose;
       this.stinumber = stinumber;
       this.frequency = frequency;
       this.dateTreatmentCommenced = dateTreatmentCommenced;
       this.dateOfDelivery = dateOfDelivery;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDose() {
        return this.dose;
    }
    
    public void setDose(String dose) {
        this.dose = dose;
    }
    public String getStinumber() {
        return this.stinumber;
    }
    
    public void setStinumber(String stinumber) {
        this.stinumber = stinumber;
    }
    public String getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }
    public Date getDateTreatmentCommenced() {
        return this.dateTreatmentCommenced;
    }
    
    public void setDateTreatmentCommenced(Date dateTreatmentCommenced) {
        this.dateTreatmentCommenced = dateTreatmentCommenced;
    }
    public Date getDateOfDelivery() {
        return this.dateOfDelivery;
    }
    
    public void setDateOfDelivery(Date dateOfDelivery) {
        this.dateOfDelivery = dateOfDelivery;
    }




}


