package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StiCs generated by hbm2java
 */
public class StiCs  implements java.io.Serializable {


     private Integer id;
     private String stinumber;
     private String opdnumber;
     private Date dateofReport;
     private String reportingFacility;
     private String motherId;
     private String mothersAddress;
     private String mothersObsHistoryGravida;
     private String mothersObsHistoryParity;
     private Date lmpbeforeDelivery;
     private String mothersReligion;
     private Date firstPrenatalVisit;
     private String trimesterFirstPrenatalVisit;
     private String motherHivstatusDuriPreg;
     private String mothersMaritalStatus;
     private String periodReceivingBenzathinePenicillin;
     private Date dateReceivingBenzathinePenicillin;
     private String motherSyphilisTreatment;
     private Date dateOfDelivery;
     private String vitalStatus;
     private Date dateOfDeath;
     private String birthWeight;
     private String gestationalAge;
     private String nonTreponemaltest;
     private String titerOfNonTreponemalTest;
     private String treponemaltestDone;
     private Date treponemaltestDoneDate;
     private Date dateOfNonTreponemalTest;
     private String darkiedExam;
     private String signsOfCongenitalSyphilis;
     private String boneXray;
     private String csfvdrl;
     private String csfproteinCsfwb;
     private String infantCongenitalSyphilistreatment;
     private String csclassification;
     private String isNonTreponemalTestFirstVisit;
     private String isNonTreponemalTestWeeksGest;
     private String isNonTreponemalTestDelivery;
     private Date dateOfNonTreponemalTestMotherRecent;
     private String resultOfNonTreponemalTestMotherRecent;
     private String titerOfNonTreponemalTestMotherRecent;
     private Date dateOfNonTreponemalTestMotherRecenFirst;
     private String resultOfNonTreponemalTestMotherFirst;
     private String titerOfNonTreponemalTestMotherFirst;
     private Date dateOfPositiveTreponemalTestRecent;
     private Date dateOfPositiveTreponemalTestFirst;

    public StiCs() {
    }

    public StiCs(String stinumber, String opdnumber, Date dateofReport, String reportingFacility, String motherId, String mothersAddress, String mothersObsHistoryGravida, String mothersObsHistoryParity, Date lmpbeforeDelivery, String mothersReligion, Date firstPrenatalVisit, String trimesterFirstPrenatalVisit, String motherHivstatusDuriPreg, String mothersMaritalStatus, String periodReceivingBenzathinePenicillin, Date dateReceivingBenzathinePenicillin, String motherSyphilisTreatment, Date dateOfDelivery, String vitalStatus, Date dateOfDeath, String birthWeight, String gestationalAge, String nonTreponemaltest, String titerOfNonTreponemalTest, String treponemaltestDone, Date treponemaltestDoneDate, Date dateOfNonTreponemalTest, String darkiedExam, String signsOfCongenitalSyphilis, String boneXray, String csfvdrl, String csfproteinCsfwb, String infantCongenitalSyphilistreatment, String csclassification, String isNonTreponemalTestFirstVisit, String isNonTreponemalTestWeeksGest, String isNonTreponemalTestDelivery, Date dateOfNonTreponemalTestMotherRecent, String resultOfNonTreponemalTestMotherRecent, String titerOfNonTreponemalTestMotherRecent, Date dateOfNonTreponemalTestMotherRecenFirst, String resultOfNonTreponemalTestMotherFirst, String titerOfNonTreponemalTestMotherFirst, Date dateOfPositiveTreponemalTestRecent, Date dateOfPositiveTreponemalTestFirst) {
       this.stinumber = stinumber;
       this.opdnumber = opdnumber;
       this.dateofReport = dateofReport;
       this.reportingFacility = reportingFacility;
       this.motherId = motherId;
       this.mothersAddress = mothersAddress;
       this.mothersObsHistoryGravida = mothersObsHistoryGravida;
       this.mothersObsHistoryParity = mothersObsHistoryParity;
       this.lmpbeforeDelivery = lmpbeforeDelivery;
       this.mothersReligion = mothersReligion;
       this.firstPrenatalVisit = firstPrenatalVisit;
       this.trimesterFirstPrenatalVisit = trimesterFirstPrenatalVisit;
       this.motherHivstatusDuriPreg = motherHivstatusDuriPreg;
       this.mothersMaritalStatus = mothersMaritalStatus;
       this.periodReceivingBenzathinePenicillin = periodReceivingBenzathinePenicillin;
       this.dateReceivingBenzathinePenicillin = dateReceivingBenzathinePenicillin;
       this.motherSyphilisTreatment = motherSyphilisTreatment;
       this.dateOfDelivery = dateOfDelivery;
       this.vitalStatus = vitalStatus;
       this.dateOfDeath = dateOfDeath;
       this.birthWeight = birthWeight;
       this.gestationalAge = gestationalAge;
       this.nonTreponemaltest = nonTreponemaltest;
       this.titerOfNonTreponemalTest = titerOfNonTreponemalTest;
       this.treponemaltestDone = treponemaltestDone;
       this.treponemaltestDoneDate = treponemaltestDoneDate;
       this.dateOfNonTreponemalTest = dateOfNonTreponemalTest;
       this.darkiedExam = darkiedExam;
       this.signsOfCongenitalSyphilis = signsOfCongenitalSyphilis;
       this.boneXray = boneXray;
       this.csfvdrl = csfvdrl;
       this.csfproteinCsfwb = csfproteinCsfwb;
       this.infantCongenitalSyphilistreatment = infantCongenitalSyphilistreatment;
       this.csclassification = csclassification;
       this.isNonTreponemalTestFirstVisit = isNonTreponemalTestFirstVisit;
       this.isNonTreponemalTestWeeksGest = isNonTreponemalTestWeeksGest;
       this.isNonTreponemalTestDelivery = isNonTreponemalTestDelivery;
       this.dateOfNonTreponemalTestMotherRecent = dateOfNonTreponemalTestMotherRecent;
       this.resultOfNonTreponemalTestMotherRecent = resultOfNonTreponemalTestMotherRecent;
       this.titerOfNonTreponemalTestMotherRecent = titerOfNonTreponemalTestMotherRecent;
       this.dateOfNonTreponemalTestMotherRecenFirst = dateOfNonTreponemalTestMotherRecenFirst;
       this.resultOfNonTreponemalTestMotherFirst = resultOfNonTreponemalTestMotherFirst;
       this.titerOfNonTreponemalTestMotherFirst = titerOfNonTreponemalTestMotherFirst;
       this.dateOfPositiveTreponemalTestRecent = dateOfPositiveTreponemalTestRecent;
       this.dateOfPositiveTreponemalTestFirst = dateOfPositiveTreponemalTestFirst;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStinumber() {
        return this.stinumber;
    }
    
    public void setStinumber(String stinumber) {
        this.stinumber = stinumber;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public Date getDateofReport() {
        return this.dateofReport;
    }
    
    public void setDateofReport(Date dateofReport) {
        this.dateofReport = dateofReport;
    }
    public String getReportingFacility() {
        return this.reportingFacility;
    }
    
    public void setReportingFacility(String reportingFacility) {
        this.reportingFacility = reportingFacility;
    }
    public String getMotherId() {
        return this.motherId;
    }
    
    public void setMotherId(String motherId) {
        this.motherId = motherId;
    }
    public String getMothersAddress() {
        return this.mothersAddress;
    }
    
    public void setMothersAddress(String mothersAddress) {
        this.mothersAddress = mothersAddress;
    }
    public String getMothersObsHistoryGravida() {
        return this.mothersObsHistoryGravida;
    }
    
    public void setMothersObsHistoryGravida(String mothersObsHistoryGravida) {
        this.mothersObsHistoryGravida = mothersObsHistoryGravida;
    }
    public String getMothersObsHistoryParity() {
        return this.mothersObsHistoryParity;
    }
    
    public void setMothersObsHistoryParity(String mothersObsHistoryParity) {
        this.mothersObsHistoryParity = mothersObsHistoryParity;
    }
    public Date getLmpbeforeDelivery() {
        return this.lmpbeforeDelivery;
    }
    
    public void setLmpbeforeDelivery(Date lmpbeforeDelivery) {
        this.lmpbeforeDelivery = lmpbeforeDelivery;
    }
    public String getMothersReligion() {
        return this.mothersReligion;
    }
    
    public void setMothersReligion(String mothersReligion) {
        this.mothersReligion = mothersReligion;
    }
    public Date getFirstPrenatalVisit() {
        return this.firstPrenatalVisit;
    }
    
    public void setFirstPrenatalVisit(Date firstPrenatalVisit) {
        this.firstPrenatalVisit = firstPrenatalVisit;
    }
    public String getTrimesterFirstPrenatalVisit() {
        return this.trimesterFirstPrenatalVisit;
    }
    
    public void setTrimesterFirstPrenatalVisit(String trimesterFirstPrenatalVisit) {
        this.trimesterFirstPrenatalVisit = trimesterFirstPrenatalVisit;
    }
    public String getMotherHivstatusDuriPreg() {
        return this.motherHivstatusDuriPreg;
    }
    
    public void setMotherHivstatusDuriPreg(String motherHivstatusDuriPreg) {
        this.motherHivstatusDuriPreg = motherHivstatusDuriPreg;
    }
    public String getMothersMaritalStatus() {
        return this.mothersMaritalStatus;
    }
    
    public void setMothersMaritalStatus(String mothersMaritalStatus) {
        this.mothersMaritalStatus = mothersMaritalStatus;
    }
    public String getPeriodReceivingBenzathinePenicillin() {
        return this.periodReceivingBenzathinePenicillin;
    }
    
    public void setPeriodReceivingBenzathinePenicillin(String periodReceivingBenzathinePenicillin) {
        this.periodReceivingBenzathinePenicillin = periodReceivingBenzathinePenicillin;
    }
    public Date getDateReceivingBenzathinePenicillin() {
        return this.dateReceivingBenzathinePenicillin;
    }
    
    public void setDateReceivingBenzathinePenicillin(Date dateReceivingBenzathinePenicillin) {
        this.dateReceivingBenzathinePenicillin = dateReceivingBenzathinePenicillin;
    }
    public String getMotherSyphilisTreatment() {
        return this.motherSyphilisTreatment;
    }
    
    public void setMotherSyphilisTreatment(String motherSyphilisTreatment) {
        this.motherSyphilisTreatment = motherSyphilisTreatment;
    }
    public Date getDateOfDelivery() {
        return this.dateOfDelivery;
    }
    
    public void setDateOfDelivery(Date dateOfDelivery) {
        this.dateOfDelivery = dateOfDelivery;
    }
    public String getVitalStatus() {
        return this.vitalStatus;
    }
    
    public void setVitalStatus(String vitalStatus) {
        this.vitalStatus = vitalStatus;
    }
    public Date getDateOfDeath() {
        return this.dateOfDeath;
    }
    
    public void setDateOfDeath(Date dateOfDeath) {
        this.dateOfDeath = dateOfDeath;
    }
    public String getBirthWeight() {
        return this.birthWeight;
    }
    
    public void setBirthWeight(String birthWeight) {
        this.birthWeight = birthWeight;
    }
    public String getGestationalAge() {
        return this.gestationalAge;
    }
    
    public void setGestationalAge(String gestationalAge) {
        this.gestationalAge = gestationalAge;
    }
    public String getNonTreponemaltest() {
        return this.nonTreponemaltest;
    }
    
    public void setNonTreponemaltest(String nonTreponemaltest) {
        this.nonTreponemaltest = nonTreponemaltest;
    }
    public String getTiterOfNonTreponemalTest() {
        return this.titerOfNonTreponemalTest;
    }
    
    public void setTiterOfNonTreponemalTest(String titerOfNonTreponemalTest) {
        this.titerOfNonTreponemalTest = titerOfNonTreponemalTest;
    }
    public String getTreponemaltestDone() {
        return this.treponemaltestDone;
    }
    
    public void setTreponemaltestDone(String treponemaltestDone) {
        this.treponemaltestDone = treponemaltestDone;
    }
    public Date getTreponemaltestDoneDate() {
        return this.treponemaltestDoneDate;
    }
    
    public void setTreponemaltestDoneDate(Date treponemaltestDoneDate) {
        this.treponemaltestDoneDate = treponemaltestDoneDate;
    }
    public Date getDateOfNonTreponemalTest() {
        return this.dateOfNonTreponemalTest;
    }
    
    public void setDateOfNonTreponemalTest(Date dateOfNonTreponemalTest) {
        this.dateOfNonTreponemalTest = dateOfNonTreponemalTest;
    }
    public String getDarkiedExam() {
        return this.darkiedExam;
    }
    
    public void setDarkiedExam(String darkiedExam) {
        this.darkiedExam = darkiedExam;
    }
    public String getSignsOfCongenitalSyphilis() {
        return this.signsOfCongenitalSyphilis;
    }
    
    public void setSignsOfCongenitalSyphilis(String signsOfCongenitalSyphilis) {
        this.signsOfCongenitalSyphilis = signsOfCongenitalSyphilis;
    }
    public String getBoneXray() {
        return this.boneXray;
    }
    
    public void setBoneXray(String boneXray) {
        this.boneXray = boneXray;
    }
    public String getCsfvdrl() {
        return this.csfvdrl;
    }
    
    public void setCsfvdrl(String csfvdrl) {
        this.csfvdrl = csfvdrl;
    }
    public String getCsfproteinCsfwb() {
        return this.csfproteinCsfwb;
    }
    
    public void setCsfproteinCsfwb(String csfproteinCsfwb) {
        this.csfproteinCsfwb = csfproteinCsfwb;
    }
    public String getInfantCongenitalSyphilistreatment() {
        return this.infantCongenitalSyphilistreatment;
    }
    
    public void setInfantCongenitalSyphilistreatment(String infantCongenitalSyphilistreatment) {
        this.infantCongenitalSyphilistreatment = infantCongenitalSyphilistreatment;
    }
    public String getCsclassification() {
        return this.csclassification;
    }
    
    public void setCsclassification(String csclassification) {
        this.csclassification = csclassification;
    }
    public String getIsNonTreponemalTestFirstVisit() {
        return this.isNonTreponemalTestFirstVisit;
    }
    
    public void setIsNonTreponemalTestFirstVisit(String isNonTreponemalTestFirstVisit) {
        this.isNonTreponemalTestFirstVisit = isNonTreponemalTestFirstVisit;
    }
    public String getIsNonTreponemalTestWeeksGest() {
        return this.isNonTreponemalTestWeeksGest;
    }
    
    public void setIsNonTreponemalTestWeeksGest(String isNonTreponemalTestWeeksGest) {
        this.isNonTreponemalTestWeeksGest = isNonTreponemalTestWeeksGest;
    }
    public String getIsNonTreponemalTestDelivery() {
        return this.isNonTreponemalTestDelivery;
    }
    
    public void setIsNonTreponemalTestDelivery(String isNonTreponemalTestDelivery) {
        this.isNonTreponemalTestDelivery = isNonTreponemalTestDelivery;
    }
    public Date getDateOfNonTreponemalTestMotherRecent() {
        return this.dateOfNonTreponemalTestMotherRecent;
    }
    
    public void setDateOfNonTreponemalTestMotherRecent(Date dateOfNonTreponemalTestMotherRecent) {
        this.dateOfNonTreponemalTestMotherRecent = dateOfNonTreponemalTestMotherRecent;
    }
    public String getResultOfNonTreponemalTestMotherRecent() {
        return this.resultOfNonTreponemalTestMotherRecent;
    }
    
    public void setResultOfNonTreponemalTestMotherRecent(String resultOfNonTreponemalTestMotherRecent) {
        this.resultOfNonTreponemalTestMotherRecent = resultOfNonTreponemalTestMotherRecent;
    }
    public String getTiterOfNonTreponemalTestMotherRecent() {
        return this.titerOfNonTreponemalTestMotherRecent;
    }
    
    public void setTiterOfNonTreponemalTestMotherRecent(String titerOfNonTreponemalTestMotherRecent) {
        this.titerOfNonTreponemalTestMotherRecent = titerOfNonTreponemalTestMotherRecent;
    }
    public Date getDateOfNonTreponemalTestMotherRecenFirst() {
        return this.dateOfNonTreponemalTestMotherRecenFirst;
    }
    
    public void setDateOfNonTreponemalTestMotherRecenFirst(Date dateOfNonTreponemalTestMotherRecenFirst) {
        this.dateOfNonTreponemalTestMotherRecenFirst = dateOfNonTreponemalTestMotherRecenFirst;
    }
    public String getResultOfNonTreponemalTestMotherFirst() {
        return this.resultOfNonTreponemalTestMotherFirst;
    }
    
    public void setResultOfNonTreponemalTestMotherFirst(String resultOfNonTreponemalTestMotherFirst) {
        this.resultOfNonTreponemalTestMotherFirst = resultOfNonTreponemalTestMotherFirst;
    }
    public String getTiterOfNonTreponemalTestMotherFirst() {
        return this.titerOfNonTreponemalTestMotherFirst;
    }
    
    public void setTiterOfNonTreponemalTestMotherFirst(String titerOfNonTreponemalTestMotherFirst) {
        this.titerOfNonTreponemalTestMotherFirst = titerOfNonTreponemalTestMotherFirst;
    }
    public Date getDateOfPositiveTreponemalTestRecent() {
        return this.dateOfPositiveTreponemalTestRecent;
    }
    
    public void setDateOfPositiveTreponemalTestRecent(Date dateOfPositiveTreponemalTestRecent) {
        this.dateOfPositiveTreponemalTestRecent = dateOfPositiveTreponemalTestRecent;
    }
    public Date getDateOfPositiveTreponemalTestFirst() {
        return this.dateOfPositiveTreponemalTestFirst;
    }
    
    public void setDateOfPositiveTreponemalTestFirst(Date dateOfPositiveTreponemalTestFirst) {
        this.dateOfPositiveTreponemalTestFirst = dateOfPositiveTreponemalTestFirst;
    }




}


