package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * StiCsexposeinfant generated by hbm2java
 */
public class StiCsexposeinfant  implements java.io.Serializable {


     private String infantId;
     private String infantOpdnumber;
     private String motherOpdnumber;
     private String examination;
     private String examinationType;
     private String umblicalOrPlacentaStatus;
     private String nonTreponemalTestResult;
     private String signs;
     private String caseDefination;
     private String notified;
     private String caseCriteria;

    public StiCsexposeinfant() {
    }

	
    public StiCsexposeinfant(String infantId) {
        this.infantId = infantId;
    }
    public StiCsexposeinfant(String infantId, String infantOpdnumber, String motherOpdnumber, String examination, String examinationType, String umblicalOrPlacentaStatus, String nonTreponemalTestResult, String signs, String caseDefination, String notified, String caseCriteria) {
       this.infantId = infantId;
       this.infantOpdnumber = infantOpdnumber;
       this.motherOpdnumber = motherOpdnumber;
       this.examination = examination;
       this.examinationType = examinationType;
       this.umblicalOrPlacentaStatus = umblicalOrPlacentaStatus;
       this.nonTreponemalTestResult = nonTreponemalTestResult;
       this.signs = signs;
       this.caseDefination = caseDefination;
       this.notified = notified;
       this.caseCriteria = caseCriteria;
    }
   
    public String getInfantId() {
        return this.infantId;
    }
    
    public void setInfantId(String infantId) {
        this.infantId = infantId;
    }
    public String getInfantOpdnumber() {
        return this.infantOpdnumber;
    }
    
    public void setInfantOpdnumber(String infantOpdnumber) {
        this.infantOpdnumber = infantOpdnumber;
    }
    public String getMotherOpdnumber() {
        return this.motherOpdnumber;
    }
    
    public void setMotherOpdnumber(String motherOpdnumber) {
        this.motherOpdnumber = motherOpdnumber;
    }
    public String getExamination() {
        return this.examination;
    }
    
    public void setExamination(String examination) {
        this.examination = examination;
    }
    public String getExaminationType() {
        return this.examinationType;
    }
    
    public void setExaminationType(String examinationType) {
        this.examinationType = examinationType;
    }
    public String getUmblicalOrPlacentaStatus() {
        return this.umblicalOrPlacentaStatus;
    }
    
    public void setUmblicalOrPlacentaStatus(String umblicalOrPlacentaStatus) {
        this.umblicalOrPlacentaStatus = umblicalOrPlacentaStatus;
    }
    public String getNonTreponemalTestResult() {
        return this.nonTreponemalTestResult;
    }
    
    public void setNonTreponemalTestResult(String nonTreponemalTestResult) {
        this.nonTreponemalTestResult = nonTreponemalTestResult;
    }
    public String getSigns() {
        return this.signs;
    }
    
    public void setSigns(String signs) {
        this.signs = signs;
    }
    public String getCaseDefination() {
        return this.caseDefination;
    }
    
    public void setCaseDefination(String caseDefination) {
        this.caseDefination = caseDefination;
    }
    public String getNotified() {
        return this.notified;
    }
    
    public void setNotified(String notified) {
        this.notified = notified;
    }
    public String getCaseCriteria() {
        return this.caseCriteria;
    }
    
    public void setCaseCriteria(String caseCriteria) {
        this.caseCriteria = caseCriteria;
    }




}


