package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * StiDrugs generated by hbm2java
 */
public class StiDrugs  implements java.io.Serializable {


     private Integer id;
     private String infectionCode;
     private String description;

    public StiDrugs() {
    }

    public StiDrugs(String infectionCode, String description) {
       this.infectionCode = infectionCode;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getInfectionCode() {
        return this.infectionCode;
    }
    
    public void setInfectionCode(String infectionCode) {
        this.infectionCode = infectionCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


