package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * StiExaminations generated by hbm2java
 */
public class StiExaminations  implements java.io.Serializable {


     private Integer id;
     private String examination;
     private Integer type;

    public StiExaminations() {
    }

    public StiExaminations(String examination, Integer type) {
       this.examination = examination;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getExamination() {
        return this.examination;
    }
    
    public void setExamination(String examination) {
        this.examination = examination;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }




}


