package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * StiHistory generated by hbm2java
 */
public class StiHistory  implements java.io.Serializable {


     private Integer id;
     private String history;
     private Integer type;

    public StiHistory() {
    }

    public StiHistory(String history, Integer type) {
       this.history = history;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getHistory() {
        return this.history;
    }
    
    public void setHistory(String history) {
        this.history = history;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }




}


