package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * StiInfectiontype generated by hbm2java
 */
public class StiInfectiontype  implements java.io.Serializable {


     private Integer id;
     private String description;
     private String infectiontype;
     private String syndrome;
     private String type;

    public StiInfectiontype() {
    }

    public StiInfectiontype(String description, String infectiontype, String syndrome, String type) {
       this.description = description;
       this.infectiontype = infectiontype;
       this.syndrome = syndrome;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getInfectiontype() {
        return this.infectiontype;
    }
    
    public void setInfectiontype(String infectiontype) {
        this.infectiontype = infectiontype;
    }
    public String getSyndrome() {
        return this.syndrome;
    }
    
    public void setSyndrome(String syndrome) {
        this.syndrome = syndrome;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


