package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * StiSexualactivity generated by hbm2java
 */
public class StiSexualactivity  implements java.io.Serializable {


     private Integer id;
     private String sexualactivity;

    public StiSexualactivity() {
    }

    public StiSexualactivity(String sexualactivity) {
       this.sexualactivity = sexualactivity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSexualactivity() {
        return this.sexualactivity;
    }
    
    public void setSexualactivity(String sexualactivity) {
        this.sexualactivity = sexualactivity;
    }




}


