package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * StiSetuppurposeofsyphilis generated by hbm2java
 */
public class StiSetuppurposeofsyphilis  implements java.io.Serializable {


     private Integer id;
     private String description;
     private String code;

    public StiSetuppurposeofsyphilis() {
    }

    public StiSetuppurposeofsyphilis(String description, String code) {
       this.description = description;
       this.code = code;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }




}


