package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * StiSymptoms generated by hbm2java
 */
public class StiSymptoms  implements java.io.Serializable {


     private int id;
     private String symptoms;
     private String category;

    public StiSymptoms() {
    }

	
    public StiSymptoms(int id) {
        this.id = id;
    }
    public StiSymptoms(int id, String symptoms, String category) {
       this.id = id;
       this.symptoms = symptoms;
       this.category = category;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getSymptoms() {
        return this.symptoms;
    }
    
    public void setSymptoms(String symptoms) {
        this.symptoms = symptoms;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }




}


