package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StiTreament generated by hbm2java
 */
public class StiTreament  implements java.io.Serializable {


     private Integer id;
     private String stiNumber;
     private Date treatmentdate;
     private String typeofsti;
     private String duration;
     private String dose;
     private String comment;

    public StiTreament() {
    }

    public StiTreament(String stiNumber, Date treatmentdate, String typeofsti, String duration, String dose, String comment) {
       this.stiNumber = stiNumber;
       this.treatmentdate = treatmentdate;
       this.typeofsti = typeofsti;
       this.duration = duration;
       this.dose = dose;
       this.comment = comment;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStiNumber() {
        return this.stiNumber;
    }
    
    public void setStiNumber(String stiNumber) {
        this.stiNumber = stiNumber;
    }
    public Date getTreatmentdate() {
        return this.treatmentdate;
    }
    
    public void setTreatmentdate(Date treatmentdate) {
        this.treatmentdate = treatmentdate;
    }
    public String getTypeofsti() {
        return this.typeofsti;
    }
    
    public void setTypeofsti(String typeofsti) {
        this.typeofsti = typeofsti;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }
    public String getDose() {
        return this.dose;
    }
    
    public void setDose(String dose) {
        this.dose = dose;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


