package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblappointmentsId generated by hbm2java
 */
public class TblappointmentsId  implements java.io.Serializable {


     private String patientId;
     private Date dateOfAppointment;

    public TblappointmentsId() {
    }

    public TblappointmentsId(String patientId, Date dateOfAppointment) {
       this.patientId = patientId;
       this.dateOfAppointment = dateOfAppointment;
    }
   
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public Date getDateOfAppointment() {
        return this.dateOfAppointment;
    }
    
    public void setDateOfAppointment(Date dateOfAppointment) {
        this.dateOfAppointment = dateOfAppointment;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblappointmentsId) ) return false;
		 TblappointmentsId castOther = ( TblappointmentsId ) other; 
         
		 return ( (this.getPatientId()==castOther.getPatientId()) || ( this.getPatientId()!=null && castOther.getPatientId()!=null && this.getPatientId().equals(castOther.getPatientId()) ) )
 && ( (this.getDateOfAppointment()==castOther.getDateOfAppointment()) || ( this.getDateOfAppointment()!=null && castOther.getDateOfAppointment()!=null && this.getDateOfAppointment().equals(castOther.getDateOfAppointment()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientId() == null ? 0 : this.getPatientId().hashCode() );
         result = 37 * result + ( getDateOfAppointment() == null ? 0 : this.getDateOfAppointment().hashCode() );
         return result;
   }   


}


