package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblbatches generated by hbm2java
 */
public class Tblbatches  implements java.io.Serializable {


     private String batchNumber;
     private String msdcode;
     private Date dateReceived;
     private Date expiryDate;
     private Byte finished;
     private String notes;
     private String invoiceNumber;

    public Tblbatches() {
    }

	
    public Tblbatches(String batchNumber) {
        this.batchNumber = batchNumber;
    }
    public Tblbatches(String batchNumber, String msdcode, Date dateReceived, Date expiryDate, Byte finished, String notes, String invoiceNumber) {
       this.batchNumber = batchNumber;
       this.msdcode = msdcode;
       this.dateReceived = dateReceived;
       this.expiryDate = expiryDate;
       this.finished = finished;
       this.notes = notes;
       this.invoiceNumber = invoiceNumber;
    }
   
    public String getBatchNumber() {
        return this.batchNumber;
    }
    
    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }
    public String getMsdcode() {
        return this.msdcode;
    }
    
    public void setMsdcode(String msdcode) {
        this.msdcode = msdcode;
    }
    public Date getDateReceived() {
        return this.dateReceived;
    }
    
    public void setDateReceived(Date dateReceived) {
        this.dateReceived = dateReceived;
    }
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }
    public Byte getFinished() {
        return this.finished;
    }
    
    public void setFinished(Byte finished) {
        this.finished = finished;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getInvoiceNumber() {
        return this.invoiceNumber;
    }
    
    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }




}


