package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblconfigoptions generated by hbm2java
 */
public class Tblconfigoptions  implements java.io.Serializable {


     private String configOptionName;
     private String configOptionValue;
     private String configOptionDescription;

    public Tblconfigoptions() {
    }

	
    public Tblconfigoptions(String configOptionName) {
        this.configOptionName = configOptionName;
    }
    public Tblconfigoptions(String configOptionName, String configOptionValue, String configOptionDescription) {
       this.configOptionName = configOptionName;
       this.configOptionValue = configOptionValue;
       this.configOptionDescription = configOptionDescription;
    }
   
    public String getConfigOptionName() {
        return this.configOptionName;
    }
    
    public void setConfigOptionName(String configOptionName) {
        this.configOptionName = configOptionName;
    }
    public String getConfigOptionValue() {
        return this.configOptionValue;
    }
    
    public void setConfigOptionValue(String configOptionValue) {
        this.configOptionValue = configOptionValue;
    }
    public String getConfigOptionDescription() {
        return this.configOptionDescription;
    }
    
    public void setConfigOptionDescription(String configOptionDescription) {
        this.configOptionDescription = configOptionDescription;
    }




}


