package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblconfig generated by hbm2java
 */
public class Tblconfig  implements java.io.Serializable {


     private TblconfigId id;

    public Tblconfig() {
    }

    public Tblconfig(TblconfigId id) {
       this.id = id;
    }
   
    public TblconfigId getId() {
        return this.id;
    }
    
    public void setId(TblconfigId id) {
        this.id = id;
    }




}


