package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * TblconfigId generated by hbm2java
 */
public class TblconfigId  implements java.io.Serializable {


     private int regionCode;
     private String districtCode;
     private String facilityCode;

    public TblconfigId() {
    }

    public TblconfigId(int regionCode, String districtCode, String facilityCode) {
       this.regionCode = regionCode;
       this.districtCode = districtCode;
       this.facilityCode = facilityCode;
    }
   
    public int getRegionCode() {
        return this.regionCode;
    }
    
    public void setRegionCode(int regionCode) {
        this.regionCode = regionCode;
    }
    public String getDistrictCode() {
        return this.districtCode;
    }
    
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }
    public String getFacilityCode() {
        return this.facilityCode;
    }
    
    public void setFacilityCode(String facilityCode) {
        this.facilityCode = facilityCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblconfigId) ) return false;
		 TblconfigId castOther = ( TblconfigId ) other; 
         
		 return (this.getRegionCode()==castOther.getRegionCode())
 && ( (this.getDistrictCode()==castOther.getDistrictCode()) || ( this.getDistrictCode()!=null && castOther.getDistrictCode()!=null && this.getDistrictCode().equals(castOther.getDistrictCode()) ) )
 && ( (this.getFacilityCode()==castOther.getFacilityCode()) || ( this.getFacilityCode()!=null && castOther.getFacilityCode()!=null && this.getFacilityCode().equals(castOther.getFacilityCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRegionCode();
         result = 37 * result + ( getDistrictCode() == null ? 0 : this.getDistrictCode().hashCode() );
         result = 37 * result + ( getFacilityCode() == null ? 0 : this.getFacilityCode().hashCode() );
         return result;
   }   


}


