package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbldatachecknotesId generated by hbm2java
 */
public class TbldatachecknotesId  implements java.io.Serializable {


     private String patientId;
     private Date visitDate;
     private int dataCheckId;

    public TbldatachecknotesId() {
    }

    public TbldatachecknotesId(String patientId, Date visitDate, int dataCheckId) {
       this.patientId = patientId;
       this.visitDate = visitDate;
       this.dataCheckId = dataCheckId;
    }
   
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public Date getVisitDate() {
        return this.visitDate;
    }
    
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }
    public int getDataCheckId() {
        return this.dataCheckId;
    }
    
    public void setDataCheckId(int dataCheckId) {
        this.dataCheckId = dataCheckId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbldatachecknotesId) ) return false;
		 TbldatachecknotesId castOther = ( TbldatachecknotesId ) other; 
         
		 return ( (this.getPatientId()==castOther.getPatientId()) || ( this.getPatientId()!=null && castOther.getPatientId()!=null && this.getPatientId().equals(castOther.getPatientId()) ) )
 && ( (this.getVisitDate()==castOther.getVisitDate()) || ( this.getVisitDate()!=null && castOther.getVisitDate()!=null && this.getVisitDate().equals(castOther.getVisitDate()) ) )
 && (this.getDataCheckId()==castOther.getDataCheckId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientId() == null ? 0 : this.getPatientId().hashCode() );
         result = 37 * result + ( getVisitDate() == null ? 0 : this.getVisitDate().hashCode() );
         result = 37 * result + this.getDataCheckId();
         return result;
   }   


}


