package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tbldatachecknotes generated by hbm2java
 */
public class Tbldatachecknotes  implements java.io.Serializable {


     private TbldatachecknotesId id;
     private String notes;

    public Tbldatachecknotes() {
    }

	
    public Tbldatachecknotes(TbldatachecknotesId id) {
        this.id = id;
    }
    public Tbldatachecknotes(TbldatachecknotesId id, String notes) {
       this.id = id;
       this.notes = notes;
    }
   
    public TbldatachecknotesId getId() {
        return this.id;
    }
    
    public void setId(TbldatachecknotesId id) {
        this.id = id;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


