package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbldispenseId generated by hbm2java
 */
public class TbldispenseId  implements java.io.Serializable {


     private String msdcode;
     private Date dispenseDate;
     private String patientId;

    public TbldispenseId() {
    }

    public TbldispenseId(String msdcode, Date dispenseDate, String patientId) {
       this.msdcode = msdcode;
       this.dispenseDate = dispenseDate;
       this.patientId = patientId;
    }
   
    public String getMsdcode() {
        return this.msdcode;
    }
    
    public void setMsdcode(String msdcode) {
        this.msdcode = msdcode;
    }
    public Date getDispenseDate() {
        return this.dispenseDate;
    }
    
    public void setDispenseDate(Date dispenseDate) {
        this.dispenseDate = dispenseDate;
    }
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbldispenseId) ) return false;
		 TbldispenseId castOther = ( TbldispenseId ) other; 
         
		 return ( (this.getMsdcode()==castOther.getMsdcode()) || ( this.getMsdcode()!=null && castOther.getMsdcode()!=null && this.getMsdcode().equals(castOther.getMsdcode()) ) )
 && ( (this.getDispenseDate()==castOther.getDispenseDate()) || ( this.getDispenseDate()!=null && castOther.getDispenseDate()!=null && this.getDispenseDate().equals(castOther.getDispenseDate()) ) )
 && ( (this.getPatientId()==castOther.getPatientId()) || ( this.getPatientId()!=null && castOther.getPatientId()!=null && this.getPatientId().equals(castOther.getPatientId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMsdcode() == null ? 0 : this.getMsdcode().hashCode() );
         result = 37 * result + ( getDispenseDate() == null ? 0 : this.getDispenseDate().hashCode() );
         result = 37 * result + ( getPatientId() == null ? 0 : this.getPatientId().hashCode() );
         return result;
   }   


}


