package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tbldispense generated by hbm2java
 */
public class Tbldispense  implements java.io.Serializable {


     private TbldispenseId id;
     private Tblsetupdispensers tblsetupdispensers;
     private String fullFacilityCode;
     private Integer transit;
     private Integer quantity;
     private Integer userNumber;
     private Integer dispenseOrder;

    public Tbldispense() {
    }

	
    public Tbldispense(TbldispenseId id) {
        this.id = id;
    }
    public Tbldispense(TbldispenseId id, Tblsetupdispensers tblsetupdispensers, String fullFacilityCode, Integer transit, Integer quantity, Integer userNumber, Integer dispenseOrder) {
       this.id = id;
       this.tblsetupdispensers = tblsetupdispensers;
       this.fullFacilityCode = fullFacilityCode;
       this.transit = transit;
       this.quantity = quantity;
       this.userNumber = userNumber;
       this.dispenseOrder = dispenseOrder;
    }
   
    public TbldispenseId getId() {
        return this.id;
    }
    
    public void setId(TbldispenseId id) {
        this.id = id;
    }
    public Tblsetupdispensers getTblsetupdispensers() {
        return this.tblsetupdispensers;
    }
    
    public void setTblsetupdispensers(Tblsetupdispensers tblsetupdispensers) {
        this.tblsetupdispensers = tblsetupdispensers;
    }
    public String getFullFacilityCode() {
        return this.fullFacilityCode;
    }
    
    public void setFullFacilityCode(String fullFacilityCode) {
        this.fullFacilityCode = fullFacilityCode;
    }
    public Integer getTransit() {
        return this.transit;
    }
    
    public void setTransit(Integer transit) {
        this.transit = transit;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getUserNumber() {
        return this.userNumber;
    }
    
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }
    public Integer getDispenseOrder() {
        return this.dispenseOrder;
    }
    
    public void setDispenseOrder(Integer dispenseOrder) {
        this.dispenseOrder = dispenseOrder;
    }




}


