package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblexposedinfantproblemsId generated by hbm2java
 */
public class TblexposedinfantproblemsId  implements java.io.Serializable {


     private String exposedInfantId;
     private Date visitDate;
     private String problemAcronym;

    public TblexposedinfantproblemsId() {
    }

    public TblexposedinfantproblemsId(String exposedInfantId, Date visitDate, String problemAcronym) {
       this.exposedInfantId = exposedInfantId;
       this.visitDate = visitDate;
       this.problemAcronym = problemAcronym;
    }
   
    public String getExposedInfantId() {
        return this.exposedInfantId;
    }
    
    public void setExposedInfantId(String exposedInfantId) {
        this.exposedInfantId = exposedInfantId;
    }
    public Date getVisitDate() {
        return this.visitDate;
    }
    
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }
    public String getProblemAcronym() {
        return this.problemAcronym;
    }
    
    public void setProblemAcronym(String problemAcronym) {
        this.problemAcronym = problemAcronym;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblexposedinfantproblemsId) ) return false;
		 TblexposedinfantproblemsId castOther = ( TblexposedinfantproblemsId ) other; 
         
		 return ( (this.getExposedInfantId()==castOther.getExposedInfantId()) || ( this.getExposedInfantId()!=null && castOther.getExposedInfantId()!=null && this.getExposedInfantId().equals(castOther.getExposedInfantId()) ) )
 && ( (this.getVisitDate()==castOther.getVisitDate()) || ( this.getVisitDate()!=null && castOther.getVisitDate()!=null && this.getVisitDate().equals(castOther.getVisitDate()) ) )
 && ( (this.getProblemAcronym()==castOther.getProblemAcronym()) || ( this.getProblemAcronym()!=null && castOther.getProblemAcronym()!=null && this.getProblemAcronym().equals(castOther.getProblemAcronym()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getExposedInfantId() == null ? 0 : this.getExposedInfantId().hashCode() );
         result = 37 * result + ( getVisitDate() == null ? 0 : this.getVisitDate().hashCode() );
         result = 37 * result + ( getProblemAcronym() == null ? 0 : this.getProblemAcronym().hashCode() );
         return result;
   }   


}


