package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblexposedinfantproblems generated by hbm2java
 */
public class Tblexposedinfantproblems  implements java.io.Serializable {


     private TblexposedinfantproblemsId id;
     private Tblexposedinfantvisits tblexposedinfantvisits;

    public Tblexposedinfantproblems() {
    }

    public Tblexposedinfantproblems(TblexposedinfantproblemsId id, Tblexposedinfantvisits tblexposedinfantvisits) {
       this.id = id;
       this.tblexposedinfantvisits = tblexposedinfantvisits;
    }
   
    public TblexposedinfantproblemsId getId() {
        return this.id;
    }
    
    public void setId(TblexposedinfantproblemsId id) {
        this.id = id;
    }
    public Tblexposedinfantvisits getTblexposedinfantvisits() {
        return this.tblexposedinfantvisits;
    }
    
    public void setTblexposedinfantvisits(Tblexposedinfantvisits tblexposedinfantvisits) {
        this.tblexposedinfantvisits = tblexposedinfantvisits;
    }




}


