package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblexposedinfanttestsId generated by hbm2java
 */
public class TblexposedinfanttestsId  implements java.io.Serializable {


     private String exposedInfantId;
     private Date testDate;

    public TblexposedinfanttestsId() {
    }

    public TblexposedinfanttestsId(String exposedInfantId, Date testDate) {
       this.exposedInfantId = exposedInfantId;
       this.testDate = testDate;
    }
   
    public String getExposedInfantId() {
        return this.exposedInfantId;
    }
    
    public void setExposedInfantId(String exposedInfantId) {
        this.exposedInfantId = exposedInfantId;
    }
    public Date getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblexposedinfanttestsId) ) return false;
		 TblexposedinfanttestsId castOther = ( TblexposedinfanttestsId ) other; 
         
		 return ( (this.getExposedInfantId()==castOther.getExposedInfantId()) || ( this.getExposedInfantId()!=null && castOther.getExposedInfantId()!=null && this.getExposedInfantId().equals(castOther.getExposedInfantId()) ) )
 && ( (this.getTestDate()==castOther.getTestDate()) || ( this.getTestDate()!=null && castOther.getTestDate()!=null && this.getTestDate().equals(castOther.getTestDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getExposedInfantId() == null ? 0 : this.getExposedInfantId().hashCode() );
         result = 37 * result + ( getTestDate() == null ? 0 : this.getTestDate().hashCode() );
         return result;
   }   


}


