package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblexposedinfanttests generated by hbm2java
 */
public class Tblexposedinfanttests  implements java.io.Serializable {


     private TblexposedinfanttestsId id;
     private Tblexposedinfants tblexposedinfants;
     private String testTypeId;
     private String testResultId;
     private Date dateResultsObtained;
     private Date dateResultsGiven;

    public Tblexposedinfanttests() {
    }

	
    public Tblexposedinfanttests(TblexposedinfanttestsId id, Tblexposedinfants tblexposedinfants) {
        this.id = id;
        this.tblexposedinfants = tblexposedinfants;
    }
    public Tblexposedinfanttests(TblexposedinfanttestsId id, Tblexposedinfants tblexposedinfants, String testTypeId, String testResultId, Date dateResultsObtained, Date dateResultsGiven) {
       this.id = id;
       this.tblexposedinfants = tblexposedinfants;
       this.testTypeId = testTypeId;
       this.testResultId = testResultId;
       this.dateResultsObtained = dateResultsObtained;
       this.dateResultsGiven = dateResultsGiven;
    }
   
    public TblexposedinfanttestsId getId() {
        return this.id;
    }
    
    public void setId(TblexposedinfanttestsId id) {
        this.id = id;
    }
    public Tblexposedinfants getTblexposedinfants() {
        return this.tblexposedinfants;
    }
    
    public void setTblexposedinfants(Tblexposedinfants tblexposedinfants) {
        this.tblexposedinfants = tblexposedinfants;
    }
    public String getTestTypeId() {
        return this.testTypeId;
    }
    
    public void setTestTypeId(String testTypeId) {
        this.testTypeId = testTypeId;
    }
    public String getTestResultId() {
        return this.testResultId;
    }
    
    public void setTestResultId(String testResultId) {
        this.testResultId = testResultId;
    }
    public Date getDateResultsObtained() {
        return this.dateResultsObtained;
    }
    
    public void setDateResultsObtained(Date dateResultsObtained) {
        this.dateResultsObtained = dateResultsObtained;
    }
    public Date getDateResultsGiven() {
        return this.dateResultsGiven;
    }
    
    public void setDateResultsGiven(Date dateResultsGiven) {
        this.dateResultsGiven = dateResultsGiven;
    }




}


