package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblexposedinfants generated by hbm2java
 */
public class Tblexposedinfants  implements java.io.Serializable {


     private String exposedInfantId;
     private String motherPatientId;
     private String fullName;
     private String sex;
     private Date dateOfBirth;
     private String infantStatusCode;
     private Date infantStatusDate;
     private String childPatientId;
     private Date dateOfDeath;
     private Integer userNumber;
     private Date theTimeStamp;
     private String modeOfDelivery;
     private String placeOfDelivery;
     private Date registrationDate;
     private Set tblexposedinfantvisitses = new HashSet(0);
     private Set tblexposedinfanttestses = new HashSet(0);

    public Tblexposedinfants() {
    }

	
    public Tblexposedinfants(String exposedInfantId) {
        this.exposedInfantId = exposedInfantId;
    }
    public Tblexposedinfants(String exposedInfantId, String motherPatientId, String fullName, String sex, Date dateOfBirth, String infantStatusCode, Date infantStatusDate, String childPatientId, Date dateOfDeath, Integer userNumber, Date theTimeStamp, String modeOfDelivery, String placeOfDelivery, Date registrationDate, Set tblexposedinfantvisitses, Set tblexposedinfanttestses) {
       this.exposedInfantId = exposedInfantId;
       this.motherPatientId = motherPatientId;
       this.fullName = fullName;
       this.sex = sex;
       this.dateOfBirth = dateOfBirth;
       this.infantStatusCode = infantStatusCode;
       this.infantStatusDate = infantStatusDate;
       this.childPatientId = childPatientId;
       this.dateOfDeath = dateOfDeath;
       this.userNumber = userNumber;
       this.theTimeStamp = theTimeStamp;
       this.modeOfDelivery = modeOfDelivery;
       this.placeOfDelivery = placeOfDelivery;
       this.registrationDate = registrationDate;
       this.tblexposedinfantvisitses = tblexposedinfantvisitses;
       this.tblexposedinfanttestses = tblexposedinfanttestses;
    }
   
    public String getExposedInfantId() {
        return this.exposedInfantId;
    }
    
    public void setExposedInfantId(String exposedInfantId) {
        this.exposedInfantId = exposedInfantId;
    }
    public String getMotherPatientId() {
        return this.motherPatientId;
    }
    
    public void setMotherPatientId(String motherPatientId) {
        this.motherPatientId = motherPatientId;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getInfantStatusCode() {
        return this.infantStatusCode;
    }
    
    public void setInfantStatusCode(String infantStatusCode) {
        this.infantStatusCode = infantStatusCode;
    }
    public Date getInfantStatusDate() {
        return this.infantStatusDate;
    }
    
    public void setInfantStatusDate(Date infantStatusDate) {
        this.infantStatusDate = infantStatusDate;
    }
    public String getChildPatientId() {
        return this.childPatientId;
    }
    
    public void setChildPatientId(String childPatientId) {
        this.childPatientId = childPatientId;
    }
    public Date getDateOfDeath() {
        return this.dateOfDeath;
    }
    
    public void setDateOfDeath(Date dateOfDeath) {
        this.dateOfDeath = dateOfDeath;
    }
    public Integer getUserNumber() {
        return this.userNumber;
    }
    
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }
    public Date getTheTimeStamp() {
        return this.theTimeStamp;
    }
    
    public void setTheTimeStamp(Date theTimeStamp) {
        this.theTimeStamp = theTimeStamp;
    }
    public String getModeOfDelivery() {
        return this.modeOfDelivery;
    }
    
    public void setModeOfDelivery(String modeOfDelivery) {
        this.modeOfDelivery = modeOfDelivery;
    }
    public String getPlaceOfDelivery() {
        return this.placeOfDelivery;
    }
    
    public void setPlaceOfDelivery(String placeOfDelivery) {
        this.placeOfDelivery = placeOfDelivery;
    }
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
    public Set getTblexposedinfantvisitses() {
        return this.tblexposedinfantvisitses;
    }
    
    public void setTblexposedinfantvisitses(Set tblexposedinfantvisitses) {
        this.tblexposedinfantvisitses = tblexposedinfantvisitses;
    }
    public Set getTblexposedinfanttestses() {
        return this.tblexposedinfanttestses;
    }
    
    public void setTblexposedinfanttestses(Set tblexposedinfanttestses) {
        this.tblexposedinfanttestses = tblexposedinfanttestses;
    }




}


