package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblexposedinfantmedication generated by hbm2java
 */
public class Tblexposedinfantmedication  implements java.io.Serializable {


     private TblexposedinfantmedicationId id;
     private Tblexposedinfantvisits tblexposedinfantvisits;
     private Integer numDaysDispensed;

    public Tblexposedinfantmedication() {
    }

	
    public Tblexposedinfantmedication(TblexposedinfantmedicationId id, Tblexposedinfantvisits tblexposedinfantvisits) {
        this.id = id;
        this.tblexposedinfantvisits = tblexposedinfantvisits;
    }
    public Tblexposedinfantmedication(TblexposedinfantmedicationId id, Tblexposedinfantvisits tblexposedinfantvisits, Integer numDaysDispensed) {
       this.id = id;
       this.tblexposedinfantvisits = tblexposedinfantvisits;
       this.numDaysDispensed = numDaysDispensed;
    }
   
    public TblexposedinfantmedicationId getId() {
        return this.id;
    }
    
    public void setId(TblexposedinfantmedicationId id) {
        this.id = id;
    }
    public Tblexposedinfantvisits getTblexposedinfantvisits() {
        return this.tblexposedinfantvisits;
    }
    
    public void setTblexposedinfantvisits(Tblexposedinfantvisits tblexposedinfantvisits) {
        this.tblexposedinfantvisits = tblexposedinfantvisits;
    }
    public Integer getNumDaysDispensed() {
        return this.numDaysDispensed;
    }
    
    public void setNumDaysDispensed(Integer numDaysDispensed) {
        this.numDaysDispensed = numDaysDispensed;
    }




}


