package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblexposedinfantvisitsId generated by hbm2java
 */
public class TblexposedinfantvisitsId  implements java.io.Serializable {


     private String exposedInfantId;
     private Date visitDate;

    public TblexposedinfantvisitsId() {
    }

    public TblexposedinfantvisitsId(String exposedInfantId, Date visitDate) {
       this.exposedInfantId = exposedInfantId;
       this.visitDate = visitDate;
    }
   
    public String getExposedInfantId() {
        return this.exposedInfantId;
    }
    
    public void setExposedInfantId(String exposedInfantId) {
        this.exposedInfantId = exposedInfantId;
    }
    public Date getVisitDate() {
        return this.visitDate;
    }
    
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblexposedinfantvisitsId) ) return false;
		 TblexposedinfantvisitsId castOther = ( TblexposedinfantvisitsId ) other; 
         
		 return ( (this.getExposedInfantId()==castOther.getExposedInfantId()) || ( this.getExposedInfantId()!=null && castOther.getExposedInfantId()!=null && this.getExposedInfantId().equals(castOther.getExposedInfantId()) ) )
 && ( (this.getVisitDate()==castOther.getVisitDate()) || ( this.getVisitDate()!=null && castOther.getVisitDate()!=null && this.getVisitDate().equals(castOther.getVisitDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getExposedInfantId() == null ? 0 : this.getExposedInfantId().hashCode() );
         result = 37 * result + ( getVisitDate() == null ? 0 : this.getVisitDate().hashCode() );
         return result;
   }   


}


