package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblfamilyrelatives generated by hbm2java
 */
public class Tblfamilyrelatives  implements java.io.Serializable {


     private int relativeId;
     private String relativeCtcid;
     private String relativeName;
     private Integer relativeAge;
     private Integer onArt;
     private Set tblfamilyinfos = new HashSet(0);

    public Tblfamilyrelatives() {
    }

	
    public Tblfamilyrelatives(int relativeId) {
        this.relativeId = relativeId;
    }
    public Tblfamilyrelatives(int relativeId, String relativeCtcid, String relativeName, Integer relativeAge, Integer onArt, Set tblfamilyinfos) {
       this.relativeId = relativeId;
       this.relativeCtcid = relativeCtcid;
       this.relativeName = relativeName;
       this.relativeAge = relativeAge;
       this.onArt = onArt;
       this.tblfamilyinfos = tblfamilyinfos;
    }
   
    public int getRelativeId() {
        return this.relativeId;
    }
    
    public void setRelativeId(int relativeId) {
        this.relativeId = relativeId;
    }
    public String getRelativeCtcid() {
        return this.relativeCtcid;
    }
    
    public void setRelativeCtcid(String relativeCtcid) {
        this.relativeCtcid = relativeCtcid;
    }
    public String getRelativeName() {
        return this.relativeName;
    }
    
    public void setRelativeName(String relativeName) {
        this.relativeName = relativeName;
    }
    public Integer getRelativeAge() {
        return this.relativeAge;
    }
    
    public void setRelativeAge(Integer relativeAge) {
        this.relativeAge = relativeAge;
    }
    public Integer getOnArt() {
        return this.onArt;
    }
    
    public void setOnArt(Integer onArt) {
        this.onArt = onArt;
    }
    public Set getTblfamilyinfos() {
        return this.tblfamilyinfos;
    }
    
    public void setTblfamilyinfos(Set tblfamilyinfos) {
        this.tblfamilyinfos = tblfamilyinfos;
    }




}


