package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblinventory generated by hbm2java
 */
public class Tblinventory  implements java.io.Serializable {


     private TblinventoryId id;
     private Integer quantity;
     private Integer userNumber;
     private String notes;

    public Tblinventory() {
    }

	
    public Tblinventory(TblinventoryId id) {
        this.id = id;
    }
    public Tblinventory(TblinventoryId id, Integer quantity, Integer userNumber, String notes) {
       this.id = id;
       this.quantity = quantity;
       this.userNumber = userNumber;
       this.notes = notes;
    }
   
    public TblinventoryId getId() {
        return this.id;
    }
    
    public void setId(TblinventoryId id) {
        this.id = id;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getUserNumber() {
        return this.userNumber;
    }
    
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


