package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblledger generated by hbm2java
 */
public class Tblledger  implements java.io.Serializable {


     private TblledgerId id;
     private Integer quantity;
     private Integer userNumber;
     private String notes;

    public Tblledger() {
    }

	
    public Tblledger(TblledgerId id) {
        this.id = id;
    }
    public Tblledger(TblledgerId id, Integer quantity, Integer userNumber, String notes) {
       this.id = id;
       this.quantity = quantity;
       this.userNumber = userNumber;
       this.notes = notes;
    }
   
    public TblledgerId getId() {
        return this.id;
    }
    
    public void setId(TblledgerId id) {
        this.id = id;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getUserNumber() {
        return this.userNumber;
    }
    
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


