package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblmedication generated by hbm2java
 */
public class Tblmedication  implements java.io.Serializable {


     private TblmedicationId id;
     private Tblvisits tblvisits;
     private Integer quantityPrescribed;
     private Integer percentAdherence;
     private String notes;
     private Integer quantityDisp;

    public Tblmedication() {
    }

	
    public Tblmedication(TblmedicationId id, Tblvisits tblvisits) {
        this.id = id;
        this.tblvisits = tblvisits;
    }
    public Tblmedication(TblmedicationId id, Tblvisits tblvisits, Integer quantityPrescribed, Integer percentAdherence, String notes, Integer quantityDisp) {
       this.id = id;
       this.tblvisits = tblvisits;
       this.quantityPrescribed = quantityPrescribed;
       this.percentAdherence = percentAdherence;
       this.notes = notes;
       this.quantityDisp = quantityDisp;
    }
   
    public TblmedicationId getId() {
        return this.id;
    }
    
    public void setId(TblmedicationId id) {
        this.id = id;
    }
    public Tblvisits getTblvisits() {
        return this.tblvisits;
    }
    
    public void setTblvisits(Tblvisits tblvisits) {
        this.tblvisits = tblvisits;
    }
    public Integer getQuantityPrescribed() {
        return this.quantityPrescribed;
    }
    
    public void setQuantityPrescribed(Integer quantityPrescribed) {
        this.quantityPrescribed = quantityPrescribed;
    }
    public Integer getPercentAdherence() {
        return this.percentAdherence;
    }
    
    public void setPercentAdherence(Integer percentAdherence) {
        this.percentAdherence = percentAdherence;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Integer getQuantityDisp() {
        return this.quantityDisp;
    }
    
    public void setQuantityDisp(Integer quantityDisp) {
        this.quantityDisp = quantityDisp;
    }




}


