package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblpregnanciesId generated by hbm2java
 */
public class TblpregnanciesId  implements java.io.Serializable {


     private String patientId;
     private Date dueDate;

    public TblpregnanciesId() {
    }

    public TblpregnanciesId(String patientId, Date dueDate) {
       this.patientId = patientId;
       this.dueDate = dueDate;
    }
   
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblpregnanciesId) ) return false;
		 TblpregnanciesId castOther = ( TblpregnanciesId ) other; 
         
		 return ( (this.getPatientId()==castOther.getPatientId()) || ( this.getPatientId()!=null && castOther.getPatientId()!=null && this.getPatientId().equals(castOther.getPatientId()) ) )
 && ( (this.getDueDate()==castOther.getDueDate()) || ( this.getDueDate()!=null && castOther.getDueDate()!=null && this.getDueDate().equals(castOther.getDueDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientId() == null ? 0 : this.getPatientId().hashCode() );
         result = 37 * result + ( getDueDate() == null ? 0 : this.getDueDate().hashCode() );
         return result;
   }   


}


