package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblpatientspriorexposure generated by hbm2java
 */
public class Tblpatientspriorexposure  implements java.io.Serializable {


     private TblpatientspriorexposureId id;
     private Tblpatients tblpatients;
     private Integer regimenCode;
     private Date dateStarted;
     private Date dateLastTakenOrCompleted;
     private String notes;

    public Tblpatientspriorexposure() {
    }

	
    public Tblpatientspriorexposure(TblpatientspriorexposureId id, Tblpatients tblpatients) {
        this.id = id;
        this.tblpatients = tblpatients;
    }
    public Tblpatientspriorexposure(TblpatientspriorexposureId id, Tblpatients tblpatients, Integer regimenCode, Date dateStarted, Date dateLastTakenOrCompleted, String notes) {
       this.id = id;
       this.tblpatients = tblpatients;
       this.regimenCode = regimenCode;
       this.dateStarted = dateStarted;
       this.dateLastTakenOrCompleted = dateLastTakenOrCompleted;
       this.notes = notes;
    }
   
    public TblpatientspriorexposureId getId() {
        return this.id;
    }
    
    public void setId(TblpatientspriorexposureId id) {
        this.id = id;
    }
    public Tblpatients getTblpatients() {
        return this.tblpatients;
    }
    
    public void setTblpatients(Tblpatients tblpatients) {
        this.tblpatients = tblpatients;
    }
    public Integer getRegimenCode() {
        return this.regimenCode;
    }
    
    public void setRegimenCode(Integer regimenCode) {
        this.regimenCode = regimenCode;
    }
    public Date getDateStarted() {
        return this.dateStarted;
    }
    
    public void setDateStarted(Date dateStarted) {
        this.dateStarted = dateStarted;
    }
    public Date getDateLastTakenOrCompleted() {
        return this.dateLastTakenOrCompleted;
    }
    
    public void setDateLastTakenOrCompleted(Date dateLastTakenOrCompleted) {
        this.dateLastTakenOrCompleted = dateLastTakenOrCompleted;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


