package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblpatientsproblems generated by hbm2java
 */
public class Tblpatientsproblems  implements java.io.Serializable {


     private TblpatientsproblemsId id;
     private Tblpatients tblpatients;
     private String notes;

    public Tblpatientsproblems() {
    }

	
    public Tblpatientsproblems(TblpatientsproblemsId id, Tblpatients tblpatients) {
        this.id = id;
        this.tblpatients = tblpatients;
    }
    public Tblpatientsproblems(TblpatientsproblemsId id, Tblpatients tblpatients, String notes) {
       this.id = id;
       this.tblpatients = tblpatients;
       this.notes = notes;
    }
   
    public TblpatientsproblemsId getId() {
        return this.id;
    }
    
    public void setId(TblpatientsproblemsId id) {
        this.id = id;
    }
    public Tblpatients getTblpatients() {
        return this.tblpatients;
    }
    
    public void setTblpatients(Tblpatients tblpatients) {
        this.tblpatients = tblpatients;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


