package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * TblpatientsproblemsId generated by hbm2java
 */
public class TblpatientsproblemsId  implements java.io.Serializable {


     private String patientId;
     private String problemAcronym;

    public TblpatientsproblemsId() {
    }

    public TblpatientsproblemsId(String patientId, String problemAcronym) {
       this.patientId = patientId;
       this.problemAcronym = problemAcronym;
    }
   
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public String getProblemAcronym() {
        return this.problemAcronym;
    }
    
    public void setProblemAcronym(String problemAcronym) {
        this.problemAcronym = problemAcronym;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblpatientsproblemsId) ) return false;
		 TblpatientsproblemsId castOther = ( TblpatientsproblemsId ) other; 
         
		 return ( (this.getPatientId()==castOther.getPatientId()) || ( this.getPatientId()!=null && castOther.getPatientId()!=null && this.getPatientId().equals(castOther.getPatientId()) ) )
 && ( (this.getProblemAcronym()==castOther.getProblemAcronym()) || ( this.getProblemAcronym()!=null && castOther.getProblemAcronym()!=null && this.getProblemAcronym().equals(castOther.getProblemAcronym()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientId() == null ? 0 : this.getPatientId().hashCode() );
         result = 37 * result + ( getProblemAcronym() == null ? 0 : this.getProblemAcronym().hashCode() );
         return result;
   }   


}


