package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblproblemsId generated by hbm2java
 */
public class TblproblemsId  implements java.io.Serializable {


     private String patientId;
     private Date visitDate;
     private String problemAcronym;

    public TblproblemsId() {
    }

    public TblproblemsId(String patientId, Date visitDate, String problemAcronym) {
       this.patientId = patientId;
       this.visitDate = visitDate;
       this.problemAcronym = problemAcronym;
    }
   
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public Date getVisitDate() {
        return this.visitDate;
    }
    
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }
    public String getProblemAcronym() {
        return this.problemAcronym;
    }
    
    public void setProblemAcronym(String problemAcronym) {
        this.problemAcronym = problemAcronym;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblproblemsId) ) return false;
		 TblproblemsId castOther = ( TblproblemsId ) other; 
         
		 return ( (this.getPatientId()==castOther.getPatientId()) || ( this.getPatientId()!=null && castOther.getPatientId()!=null && this.getPatientId().equals(castOther.getPatientId()) ) )
 && ( (this.getVisitDate()==castOther.getVisitDate()) || ( this.getVisitDate()!=null && castOther.getVisitDate()!=null && this.getVisitDate().equals(castOther.getVisitDate()) ) )
 && ( (this.getProblemAcronym()==castOther.getProblemAcronym()) || ( this.getProblemAcronym()!=null && castOther.getProblemAcronym()!=null && this.getProblemAcronym().equals(castOther.getProblemAcronym()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientId() == null ? 0 : this.getPatientId().hashCode() );
         result = 37 * result + ( getVisitDate() == null ? 0 : this.getVisitDate().hashCode() );
         result = 37 * result + ( getProblemAcronym() == null ? 0 : this.getProblemAcronym().hashCode() );
         return result;
   }   


}


