package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblproblems generated by hbm2java
 */
public class Tblproblems  implements java.io.Serializable {


     private TblproblemsId id;
     private Tblvisits tblvisits;

    public Tblproblems() {
    }

    public Tblproblems(TblproblemsId id, Tblvisits tblvisits) {
       this.id = id;
       this.tblvisits = tblvisits;
    }
   
    public TblproblemsId getId() {
        return this.id;
    }
    
    public void setId(TblproblemsId id) {
        this.id = id;
    }
    public Tblvisits getTblvisits() {
        return this.tblvisits;
    }
    
    public void setTblvisits(Tblvisits tblvisits) {
        this.tblvisits = tblvisits;
    }




}


