package com.vmmc.entities;
// Generated Sep 15, 2020 10:19:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblpatients generated by hbm2java
 */
public class Tblpatients  implements java.io.Serializable {


     private String patientId;
     private String firstName;
     private String surName;
     private String nationalId;
     private Date dateOfBirth;
     private String sex;
     private String maritalStatus;
     private String medInsSchemeName;
     private String medInsMemberName;
     private String medInsNumber;
     private String medInsRelationshipToMember;
     private String physicalAddress;
     private String physicalAddressNextKin;
     private String nearestKraal;
     private String nearestKraalNextKin;
     private String nearestVillage;
     private String nearestVillageNextKin;
     private String nearestSchool;
     private String nearestSchoolNextKin;
     private String nearestClinic;
     private String nearestClinicNextKin;
     private String phone;
     private String phoneNextKin;
     private String cellPhone;
     private String cellPhoneNextKin;
     private String workAddress;
     private String workAddressNextKin;
     private String workTel;
     private String workTelNextKin;
     private String occupation;
     private String occupationNextKin;
     private String transferInId;
     private String referredFromId;
     private String referredFromNotes;
     private String orphanStatusId;
     private String educationLevelId;
     private Date dateOfDeath;
     private Date dateConfirmedHivpositive;
     private String locationHivtestCode;
     private String hivtestTypeId;
     private String hivtestReasonId;
     private String hivtestNotes;
     private String hivtestLocationCode;
     private String drugAllergies;
     private String fileRef;
     private String notes;
     private Integer userNumber;
     private Date theTimeStamp;
     private String opdnumber;
     private Date dateOfEnrolment;
     private String personalTracingName;
     private Date personalTracingDate;
     private String indexCaseName;
     private Date indexCaseDate;
     private String isDisclosureHiv;
     private String disclosureYesWhom;
     private String disclosureNoReason;
     private Date disclosureYesDate;
     private String disclosureYesRelation;
     private String isRetestForHivinitiation;
     private Date isRetestForHivinitiationDate;
     private String nameNextKin;
     private Set tblvisitses = new HashSet(0);

    public Tblpatients() {
    }

	
    public Tblpatients(String patientId) {
        this.patientId = patientId;
    }
    public Tblpatients(String patientId, String firstName, String surName, String nationalId, Date dateOfBirth, String sex, String maritalStatus, String medInsSchemeName, String medInsMemberName, String medInsNumber, String medInsRelationshipToMember, String physicalAddress, String physicalAddressNextKin, String nearestKraal, String nearestKraalNextKin, String nearestVillage, String nearestVillageNextKin, String nearestSchool, String nearestSchoolNextKin, String nearestClinic, String nearestClinicNextKin, String phone, String phoneNextKin, String cellPhone, String cellPhoneNextKin, String workAddress, String workAddressNextKin, String workTel, String workTelNextKin, String occupation, String occupationNextKin, String transferInId, String referredFromId, String referredFromNotes, String orphanStatusId, String educationLevelId, Date dateOfDeath, Date dateConfirmedHivpositive, String locationHivtestCode, String hivtestTypeId, String hivtestReasonId, String hivtestNotes, String hivtestLocationCode, String drugAllergies, String fileRef, String notes, Integer userNumber, Date theTimeStamp, String opdnumber, Date dateOfEnrolment, String personalTracingName, Date personalTracingDate, String indexCaseName, Date indexCaseDate, String isDisclosureHiv, String disclosureYesWhom, String disclosureNoReason, Date disclosureYesDate, String disclosureYesRelation, String isRetestForHivinitiation, Date isRetestForHivinitiationDate, String nameNextKin, Set tblvisitses) {
       this.patientId = patientId;
       this.firstName = firstName;
       this.surName = surName;
       this.nationalId = nationalId;
       this.dateOfBirth = dateOfBirth;
       this.sex = sex;
       this.maritalStatus = maritalStatus;
       this.medInsSchemeName = medInsSchemeName;
       this.medInsMemberName = medInsMemberName;
       this.medInsNumber = medInsNumber;
       this.medInsRelationshipToMember = medInsRelationshipToMember;
       this.physicalAddress = physicalAddress;
       this.physicalAddressNextKin = physicalAddressNextKin;
       this.nearestKraal = nearestKraal;
       this.nearestKraalNextKin = nearestKraalNextKin;
       this.nearestVillage = nearestVillage;
       this.nearestVillageNextKin = nearestVillageNextKin;
       this.nearestSchool = nearestSchool;
       this.nearestSchoolNextKin = nearestSchoolNextKin;
       this.nearestClinic = nearestClinic;
       this.nearestClinicNextKin = nearestClinicNextKin;
       this.phone = phone;
       this.phoneNextKin = phoneNextKin;
       this.cellPhone = cellPhone;
       this.cellPhoneNextKin = cellPhoneNextKin;
       this.workAddress = workAddress;
       this.workAddressNextKin = workAddressNextKin;
       this.workTel = workTel;
       this.workTelNextKin = workTelNextKin;
       this.occupation = occupation;
       this.occupationNextKin = occupationNextKin;
       this.transferInId = transferInId;
       this.referredFromId = referredFromId;
       this.referredFromNotes = referredFromNotes;
       this.orphanStatusId = orphanStatusId;
       this.educationLevelId = educationLevelId;
       this.dateOfDeath = dateOfDeath;
       this.dateConfirmedHivpositive = dateConfirmedHivpositive;
       this.locationHivtestCode = locationHivtestCode;
       this.hivtestTypeId = hivtestTypeId;
       this.hivtestReasonId = hivtestReasonId;
       this.hivtestNotes = hivtestNotes;
       this.hivtestLocationCode = hivtestLocationCode;
       this.drugAllergies = drugAllergies;
       this.fileRef = fileRef;
       this.notes = notes;
       this.userNumber = userNumber;
       this.theTimeStamp = theTimeStamp;
       this.opdnumber = opdnumber;
       this.dateOfEnrolment = dateOfEnrolment;
       this.personalTracingName = personalTracingName;
       this.personalTracingDate = personalTracingDate;
       this.indexCaseName = indexCaseName;
       this.indexCaseDate = indexCaseDate;
       this.isDisclosureHiv = isDisclosureHiv;
       this.disclosureYesWhom = disclosureYesWhom;
       this.disclosureNoReason = disclosureNoReason;
       this.disclosureYesDate = disclosureYesDate;
       this.disclosureYesRelation = disclosureYesRelation;
       this.isRetestForHivinitiation = isRetestForHivinitiation;
       this.isRetestForHivinitiationDate = isRetestForHivinitiationDate;
       this.nameNextKin = nameNextKin;
       this.tblvisitses = tblvisitses;
    }
   
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getSurName() {
        return this.surName;
    }
    
    public void setSurName(String surName) {
        this.surName = surName;
    }
    public String getNationalId() {
        return this.nationalId;
    }
    
    public void setNationalId(String nationalId) {
        this.nationalId = nationalId;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public String getMedInsSchemeName() {
        return this.medInsSchemeName;
    }
    
    public void setMedInsSchemeName(String medInsSchemeName) {
        this.medInsSchemeName = medInsSchemeName;
    }
    public String getMedInsMemberName() {
        return this.medInsMemberName;
    }
    
    public void setMedInsMemberName(String medInsMemberName) {
        this.medInsMemberName = medInsMemberName;
    }
    public String getMedInsNumber() {
        return this.medInsNumber;
    }
    
    public void setMedInsNumber(String medInsNumber) {
        this.medInsNumber = medInsNumber;
    }
    public String getMedInsRelationshipToMember() {
        return this.medInsRelationshipToMember;
    }
    
    public void setMedInsRelationshipToMember(String medInsRelationshipToMember) {
        this.medInsRelationshipToMember = medInsRelationshipToMember;
    }
    public String getPhysicalAddress() {
        return this.physicalAddress;
    }
    
    public void setPhysicalAddress(String physicalAddress) {
        this.physicalAddress = physicalAddress;
    }
    public String getPhysicalAddressNextKin() {
        return this.physicalAddressNextKin;
    }
    
    public void setPhysicalAddressNextKin(String physicalAddressNextKin) {
        this.physicalAddressNextKin = physicalAddressNextKin;
    }
    public String getNearestKraal() {
        return this.nearestKraal;
    }
    
    public void setNearestKraal(String nearestKraal) {
        this.nearestKraal = nearestKraal;
    }
    public String getNearestKraalNextKin() {
        return this.nearestKraalNextKin;
    }
    
    public void setNearestKraalNextKin(String nearestKraalNextKin) {
        this.nearestKraalNextKin = nearestKraalNextKin;
    }
    public String getNearestVillage() {
        return this.nearestVillage;
    }
    
    public void setNearestVillage(String nearestVillage) {
        this.nearestVillage = nearestVillage;
    }
    public String getNearestVillageNextKin() {
        return this.nearestVillageNextKin;
    }
    
    public void setNearestVillageNextKin(String nearestVillageNextKin) {
        this.nearestVillageNextKin = nearestVillageNextKin;
    }
    public String getNearestSchool() {
        return this.nearestSchool;
    }
    
    public void setNearestSchool(String nearestSchool) {
        this.nearestSchool = nearestSchool;
    }
    public String getNearestSchoolNextKin() {
        return this.nearestSchoolNextKin;
    }
    
    public void setNearestSchoolNextKin(String nearestSchoolNextKin) {
        this.nearestSchoolNextKin = nearestSchoolNextKin;
    }
    public String getNearestClinic() {
        return this.nearestClinic;
    }
    
    public void setNearestClinic(String nearestClinic) {
        this.nearestClinic = nearestClinic;
    }
    public String getNearestClinicNextKin() {
        return this.nearestClinicNextKin;
    }
    
    public void setNearestClinicNextKin(String nearestClinicNextKin) {
        this.nearestClinicNextKin = nearestClinicNextKin;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPhoneNextKin() {
        return this.phoneNextKin;
    }
    
    public void setPhoneNextKin(String phoneNextKin) {
        this.phoneNextKin = phoneNextKin;
    }
    public String getCellPhone() {
        return this.cellPhone;
    }
    
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }
    public String getCellPhoneNextKin() {
        return this.cellPhoneNextKin;
    }
    
    public void setCellPhoneNextKin(String cellPhoneNextKin) {
        this.cellPhoneNextKin = cellPhoneNextKin;
    }
    public String getWorkAddress() {
        return this.workAddress;
    }
    
    public void setWorkAddress(String workAddress) {
        this.workAddress = workAddress;
    }
    public String getWorkAddressNextKin() {
        return this.workAddressNextKin;
    }
    
    public void setWorkAddressNextKin(String workAddressNextKin) {
        this.workAddressNextKin = workAddressNextKin;
    }
    public String getWorkTel() {
        return this.workTel;
    }
    
    public void setWorkTel(String workTel) {
        this.workTel = workTel;
    }
    public String getWorkTelNextKin() {
        return this.workTelNextKin;
    }
    
    public void setWorkTelNextKin(String workTelNextKin) {
        this.workTelNextKin = workTelNextKin;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public String getOccupationNextKin() {
        return this.occupationNextKin;
    }
    
    public void setOccupationNextKin(String occupationNextKin) {
        this.occupationNextKin = occupationNextKin;
    }
    public String getTransferInId() {
        return this.transferInId;
    }
    
    public void setTransferInId(String transferInId) {
        this.transferInId = transferInId;
    }
    public String getReferredFromId() {
        return this.referredFromId;
    }
    
    public void setReferredFromId(String referredFromId) {
        this.referredFromId = referredFromId;
    }
    public String getReferredFromNotes() {
        return this.referredFromNotes;
    }
    
    public void setReferredFromNotes(String referredFromNotes) {
        this.referredFromNotes = referredFromNotes;
    }
    public String getOrphanStatusId() {
        return this.orphanStatusId;
    }
    
    public void setOrphanStatusId(String orphanStatusId) {
        this.orphanStatusId = orphanStatusId;
    }
    public String getEducationLevelId() {
        return this.educationLevelId;
    }
    
    public void setEducationLevelId(String educationLevelId) {
        this.educationLevelId = educationLevelId;
    }
    public Date getDateOfDeath() {
        return this.dateOfDeath;
    }
    
    public void setDateOfDeath(Date dateOfDeath) {
        this.dateOfDeath = dateOfDeath;
    }
    public Date getDateConfirmedHivpositive() {
        return this.dateConfirmedHivpositive;
    }
    
    public void setDateConfirmedHivpositive(Date dateConfirmedHivpositive) {
        this.dateConfirmedHivpositive = dateConfirmedHivpositive;
    }
    public String getLocationHivtestCode() {
        return this.locationHivtestCode;
    }
    
    public void setLocationHivtestCode(String locationHivtestCode) {
        this.locationHivtestCode = locationHivtestCode;
    }
    public String getHivtestTypeId() {
        return this.hivtestTypeId;
    }
    
    public void setHivtestTypeId(String hivtestTypeId) {
        this.hivtestTypeId = hivtestTypeId;
    }
    public String getHivtestReasonId() {
        return this.hivtestReasonId;
    }
    
    public void setHivtestReasonId(String hivtestReasonId) {
        this.hivtestReasonId = hivtestReasonId;
    }
    public String getHivtestNotes() {
        return this.hivtestNotes;
    }
    
    public void setHivtestNotes(String hivtestNotes) {
        this.hivtestNotes = hivtestNotes;
    }
    public String getHivtestLocationCode() {
        return this.hivtestLocationCode;
    }
    
    public void setHivtestLocationCode(String hivtestLocationCode) {
        this.hivtestLocationCode = hivtestLocationCode;
    }
    public String getDrugAllergies() {
        return this.drugAllergies;
    }
    
    public void setDrugAllergies(String drugAllergies) {
        this.drugAllergies = drugAllergies;
    }
    public String getFileRef() {
        return this.fileRef;
    }
    
    public void setFileRef(String fileRef) {
        this.fileRef = fileRef;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Integer getUserNumber() {
        return this.userNumber;
    }
    
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }
    public Date getTheTimeStamp() {
        return this.theTimeStamp;
    }
    
    public void setTheTimeStamp(Date theTimeStamp) {
        this.theTimeStamp = theTimeStamp;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public Date getDateOfEnrolment() {
        return this.dateOfEnrolment;
    }
    
    public void setDateOfEnrolment(Date dateOfEnrolment) {
        this.dateOfEnrolment = dateOfEnrolment;
    }
    public String getPersonalTracingName() {
        return this.personalTracingName;
    }
    
    public void setPersonalTracingName(String personalTracingName) {
        this.personalTracingName = personalTracingName;
    }
    public Date getPersonalTracingDate() {
        return this.personalTracingDate;
    }
    
    public void setPersonalTracingDate(Date personalTracingDate) {
        this.personalTracingDate = personalTracingDate;
    }
    public String getIndexCaseName() {
        return this.indexCaseName;
    }
    
    public void setIndexCaseName(String indexCaseName) {
        this.indexCaseName = indexCaseName;
    }
    public Date getIndexCaseDate() {
        return this.indexCaseDate;
    }
    
    public void setIndexCaseDate(Date indexCaseDate) {
        this.indexCaseDate = indexCaseDate;
    }
    public String getIsDisclosureHiv() {
        return this.isDisclosureHiv;
    }
    
    public void setIsDisclosureHiv(String isDisclosureHiv) {
        this.isDisclosureHiv = isDisclosureHiv;
    }
    public String getDisclosureYesWhom() {
        return this.disclosureYesWhom;
    }
    
    public void setDisclosureYesWhom(String disclosureYesWhom) {
        this.disclosureYesWhom = disclosureYesWhom;
    }
    public String getDisclosureNoReason() {
        return this.disclosureNoReason;
    }
    
    public void setDisclosureNoReason(String disclosureNoReason) {
        this.disclosureNoReason = disclosureNoReason;
    }
    public Date getDisclosureYesDate() {
        return this.disclosureYesDate;
    }
    
    public void setDisclosureYesDate(Date disclosureYesDate) {
        this.disclosureYesDate = disclosureYesDate;
    }
    public String getDisclosureYesRelation() {
        return this.disclosureYesRelation;
    }
    
    public void setDisclosureYesRelation(String disclosureYesRelation) {
        this.disclosureYesRelation = disclosureYesRelation;
    }
    public String getIsRetestForHivinitiation() {
        return this.isRetestForHivinitiation;
    }
    
    public void setIsRetestForHivinitiation(String isRetestForHivinitiation) {
        this.isRetestForHivinitiation = isRetestForHivinitiation;
    }
    public Date getIsRetestForHivinitiationDate() {
        return this.isRetestForHivinitiationDate;
    }
    
    public void setIsRetestForHivinitiationDate(Date isRetestForHivinitiationDate) {
        this.isRetestForHivinitiationDate = isRetestForHivinitiationDate;
    }
    public String getNameNextKin() {
        return this.nameNextKin;
    }
    
    public void setNameNextKin(String nameNextKin) {
        this.nameNextKin = nameNextKin;
    }
    public Set getTblvisitses() {
        return this.tblvisitses;
    }
    
    public void setTblvisitses(Set tblvisitses) {
        this.tblvisitses = tblvisitses;
    }




}


