package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblreferralstoId generated by hbm2java
 */
public class TblreferralstoId  implements java.io.Serializable {


     private String patientId;
     private Date visitDate;
     private String referralToCode;

    public TblreferralstoId() {
    }

    public TblreferralstoId(String patientId, Date visitDate, String referralToCode) {
       this.patientId = patientId;
       this.visitDate = visitDate;
       this.referralToCode = referralToCode;
    }
   
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public Date getVisitDate() {
        return this.visitDate;
    }
    
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }
    public String getReferralToCode() {
        return this.referralToCode;
    }
    
    public void setReferralToCode(String referralToCode) {
        this.referralToCode = referralToCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblreferralstoId) ) return false;
		 TblreferralstoId castOther = ( TblreferralstoId ) other; 
         
		 return ( (this.getPatientId()==castOther.getPatientId()) || ( this.getPatientId()!=null && castOther.getPatientId()!=null && this.getPatientId().equals(castOther.getPatientId()) ) )
 && ( (this.getVisitDate()==castOther.getVisitDate()) || ( this.getVisitDate()!=null && castOther.getVisitDate()!=null && this.getVisitDate().equals(castOther.getVisitDate()) ) )
 && ( (this.getReferralToCode()==castOther.getReferralToCode()) || ( this.getReferralToCode()!=null && castOther.getReferralToCode()!=null && this.getReferralToCode().equals(castOther.getReferralToCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientId() == null ? 0 : this.getPatientId().hashCode() );
         result = 37 * result + ( getVisitDate() == null ? 0 : this.getVisitDate().hashCode() );
         result = 37 * result + ( getReferralToCode() == null ? 0 : this.getReferralToCode().hashCode() );
         return result;
   }   


}


