package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblrequestdates generated by hbm2java
 */
public class Tblrequestdates  implements java.io.Serializable {


     private Date periodEndDate;
     private Date sentDate;

    public Tblrequestdates() {
    }

	
    public Tblrequestdates(Date periodEndDate) {
        this.periodEndDate = periodEndDate;
    }
    public Tblrequestdates(Date periodEndDate, Date sentDate) {
       this.periodEndDate = periodEndDate;
       this.sentDate = sentDate;
    }
   
    public Date getPeriodEndDate() {
        return this.periodEndDate;
    }
    
    public void setPeriodEndDate(Date periodEndDate) {
        this.periodEndDate = periodEndDate;
    }
    public Date getSentDate() {
        return this.sentDate;
    }
    
    public void setSentDate(Date sentDate) {
        this.sentDate = sentDate;
    }




}


