package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblrequestsId generated by hbm2java
 */
public class TblrequestsId  implements java.io.Serializable {


     private String msdcode;
     private Date periodEndDate;

    public TblrequestsId() {
    }

    public TblrequestsId(String msdcode, Date periodEndDate) {
       this.msdcode = msdcode;
       this.periodEndDate = periodEndDate;
    }
   
    public String getMsdcode() {
        return this.msdcode;
    }
    
    public void setMsdcode(String msdcode) {
        this.msdcode = msdcode;
    }
    public Date getPeriodEndDate() {
        return this.periodEndDate;
    }
    
    public void setPeriodEndDate(Date periodEndDate) {
        this.periodEndDate = periodEndDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblrequestsId) ) return false;
		 TblrequestsId castOther = ( TblrequestsId ) other; 
         
		 return ( (this.getMsdcode()==castOther.getMsdcode()) || ( this.getMsdcode()!=null && castOther.getMsdcode()!=null && this.getMsdcode().equals(castOther.getMsdcode()) ) )
 && ( (this.getPeriodEndDate()==castOther.getPeriodEndDate()) || ( this.getPeriodEndDate()!=null && castOther.getPeriodEndDate()!=null && this.getPeriodEndDate().equals(castOther.getPeriodEndDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMsdcode() == null ? 0 : this.getMsdcode().hashCode() );
         result = 37 * result + ( getPeriodEndDate() == null ? 0 : this.getPeriodEndDate().hashCode() );
         return result;
   }   


}


