package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblrequests generated by hbm2java
 */
public class Tblrequests  implements java.io.Serializable {


     private TblrequestsId id;
     private Integer quantityRequested;
     private String remarks;

    public Tblrequests() {
    }

	
    public Tblrequests(TblrequestsId id) {
        this.id = id;
    }
    public Tblrequests(TblrequestsId id, Integer quantityRequested, String remarks) {
       this.id = id;
       this.quantityRequested = quantityRequested;
       this.remarks = remarks;
    }
   
    public TblrequestsId getId() {
        return this.id;
    }
    
    public void setId(TblrequestsId id) {
        this.id = id;
    }
    public Integer getQuantityRequested() {
        return this.quantityRequested;
    }
    
    public void setQuantityRequested(Integer quantityRequested) {
        this.quantityRequested = quantityRequested;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


