package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetuphivtestreasons generated by hbm2java
 */
public class Tblsetuphivtestreasons  implements java.io.Serializable {


     private String hivtestReasonId;
     private String hivtestReason;

    public Tblsetuphivtestreasons() {
    }

	
    public Tblsetuphivtestreasons(String hivtestReasonId) {
        this.hivtestReasonId = hivtestReasonId;
    }
    public Tblsetuphivtestreasons(String hivtestReasonId, String hivtestReason) {
       this.hivtestReasonId = hivtestReasonId;
       this.hivtestReason = hivtestReason;
    }
   
    public String getHivtestReasonId() {
        return this.hivtestReasonId;
    }
    
    public void setHivtestReasonId(String hivtestReasonId) {
        this.hivtestReasonId = hivtestReasonId;
    }
    public String getHivtestReason() {
        return this.hivtestReason;
    }
    
    public void setHivtestReason(String hivtestReason) {
        this.hivtestReason = hivtestReason;
    }




}


