package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupproblems generated by hbm2java
 */
public class Tblsetupproblems  implements java.io.Serializable {


     private String problemAcronym;
     private String problemType;
     private String problemDescription;
     private Integer theOrder;
     private Integer forStandard;
     private Integer forInfants;

    public Tblsetupproblems() {
    }

	
    public Tblsetupproblems(String problemAcronym) {
        this.problemAcronym = problemAcronym;
    }
    public Tblsetupproblems(String problemAcronym, String problemType, String problemDescription, Integer theOrder, Integer forStandard, Integer forInfants) {
       this.problemAcronym = problemAcronym;
       this.problemType = problemType;
       this.problemDescription = problemDescription;
       this.theOrder = theOrder;
       this.forStandard = forStandard;
       this.forInfants = forInfants;
    }
   
    public String getProblemAcronym() {
        return this.problemAcronym;
    }
    
    public void setProblemAcronym(String problemAcronym) {
        this.problemAcronym = problemAcronym;
    }
    public String getProblemType() {
        return this.problemType;
    }
    
    public void setProblemType(String problemType) {
        this.problemType = problemType;
    }
    public String getProblemDescription() {
        return this.problemDescription;
    }
    
    public void setProblemDescription(String problemDescription) {
        this.problemDescription = problemDescription;
    }
    public Integer getTheOrder() {
        return this.theOrder;
    }
    
    public void setTheOrder(Integer theOrder) {
        this.theOrder = theOrder;
    }
    public Integer getForStandard() {
        return this.forStandard;
    }
    
    public void setForStandard(Integer forStandard) {
        this.forStandard = forStandard;
    }
    public Integer getForInfants() {
        return this.forInfants;
    }
    
    public void setForInfants(Integer forInfants) {
        this.forInfants = forInfants;
    }




}


