package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetuppregnancystatus generated by hbm2java
 */
public class Tblsetuppregnancystatus  implements java.io.Serializable {


     private String pregnancystatuscode;
     private String pregnancystatusdescription;

    public Tblsetuppregnancystatus() {
    }

    public Tblsetuppregnancystatus(String pregnancystatuscode, String pregnancystatusdescription) {
       this.pregnancystatuscode = pregnancystatuscode;
       this.pregnancystatusdescription = pregnancystatusdescription;
    }
   
    public String getPregnancystatuscode() {
        return this.pregnancystatuscode;
    }
    
    public void setPregnancystatuscode(String pregnancystatuscode) {
        this.pregnancystatuscode = pregnancystatuscode;
    }
    public String getPregnancystatusdescription() {
        return this.pregnancystatusdescription;
    }
    
    public void setPregnancystatusdescription(String pregnancystatusdescription) {
        this.pregnancystatusdescription = pregnancystatusdescription;
    }




}


