package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupeducationlevel generated by hbm2java
 */
public class Tblsetupeducationlevel  implements java.io.Serializable {


     private String educationLevelId;
     private String educationLevel;

    public Tblsetupeducationlevel() {
    }

	
    public Tblsetupeducationlevel(String educationLevelId) {
        this.educationLevelId = educationLevelId;
    }
    public Tblsetupeducationlevel(String educationLevelId, String educationLevel) {
       this.educationLevelId = educationLevelId;
       this.educationLevel = educationLevel;
    }
   
    public String getEducationLevelId() {
        return this.educationLevelId;
    }
    
    public void setEducationLevelId(String educationLevelId) {
        this.educationLevelId = educationLevelId;
    }
    public String getEducationLevel() {
        return this.educationLevel;
    }
    
    public void setEducationLevel(String educationLevel) {
        this.educationLevel = educationLevel;
    }




}


