package com.vmmc.entities;
// Generated Jul 5, 2021 12:52:57 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupcryptococcaltreatment generated by hbm2java
 */
public class Tblsetupcryptococcaltreatment  implements java.io.Serializable {


     private String cryptococcalTreatmentCode;
     private String cryptococcalTreatmentDescription;

    public Tblsetupcryptococcaltreatment() {
    }

	
    public Tblsetupcryptococcaltreatment(String cryptococcalTreatmentCode) {
        this.cryptococcalTreatmentCode = cryptococcalTreatmentCode;
    }
    public Tblsetupcryptococcaltreatment(String cryptococcalTreatmentCode, String cryptococcalTreatmentDescription) {
       this.cryptococcalTreatmentCode = cryptococcalTreatmentCode;
       this.cryptococcalTreatmentDescription = cryptococcalTreatmentDescription;
    }
   
    public String getCryptococcalTreatmentCode() {
        return this.cryptococcalTreatmentCode;
    }
    
    public void setCryptococcalTreatmentCode(String cryptococcalTreatmentCode) {
        this.cryptococcalTreatmentCode = cryptococcalTreatmentCode;
    }
    public String getCryptococcalTreatmentDescription() {
        return this.cryptococcalTreatmentDescription;
    }
    
    public void setCryptococcalTreatmentDescription(String cryptococcalTreatmentDescription) {
        this.cryptococcalTreatmentDescription = cryptococcalTreatmentDescription;
    }




}


