package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblsetupregions generated by hbm2java
 */
public class Tblsetupregions  implements java.io.Serializable {


     private int regionCode;
     private String region;
     private Set tblsetupdistrictses = new HashSet(0);

    public Tblsetupregions() {
    }

	
    public Tblsetupregions(int regionCode) {
        this.regionCode = regionCode;
    }
    public Tblsetupregions(int regionCode, String region, Set tblsetupdistrictses) {
       this.regionCode = regionCode;
       this.region = region;
       this.tblsetupdistrictses = tblsetupdistrictses;
    }
   
    public int getRegionCode() {
        return this.regionCode;
    }
    
    public void setRegionCode(int regionCode) {
        this.regionCode = regionCode;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public Set getTblsetupdistrictses() {
        return this.tblsetupdistrictses;
    }
    
    public void setTblsetupdistrictses(Set tblsetupdistrictses) {
        this.tblsetupdistrictses = tblsetupdistrictses;
    }




}


