package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetuppregnancyoutcomes generated by hbm2java
 */
public class Tblsetuppregnancyoutcomes  implements java.io.Serializable {


     private String pregnancyOutcomeId;
     private String pregnancyOutcome;

    public Tblsetuppregnancyoutcomes() {
    }

	
    public Tblsetuppregnancyoutcomes(String pregnancyOutcomeId) {
        this.pregnancyOutcomeId = pregnancyOutcomeId;
    }
    public Tblsetuppregnancyoutcomes(String pregnancyOutcomeId, String pregnancyOutcome) {
       this.pregnancyOutcomeId = pregnancyOutcomeId;
       this.pregnancyOutcome = pregnancyOutcome;
    }
   
    public String getPregnancyOutcomeId() {
        return this.pregnancyOutcomeId;
    }
    
    public void setPregnancyOutcomeId(String pregnancyOutcomeId) {
        this.pregnancyOutcomeId = pregnancyOutcomeId;
    }
    public String getPregnancyOutcome() {
        return this.pregnancyOutcome;
    }
    
    public void setPregnancyOutcome(String pregnancyOutcome) {
        this.pregnancyOutcome = pregnancyOutcome;
    }




}


