package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupfunctionalstatus generated by hbm2java
 */
public class Tblsetupfunctionalstatus  implements java.io.Serializable {


     private String functionalStatusCode;
     private String functionalStatusDescription;

    public Tblsetupfunctionalstatus() {
    }

	
    public Tblsetupfunctionalstatus(String functionalStatusCode) {
        this.functionalStatusCode = functionalStatusCode;
    }
    public Tblsetupfunctionalstatus(String functionalStatusCode, String functionalStatusDescription) {
       this.functionalStatusCode = functionalStatusCode;
       this.functionalStatusDescription = functionalStatusDescription;
    }
   
    public String getFunctionalStatusCode() {
        return this.functionalStatusCode;
    }
    
    public void setFunctionalStatusCode(String functionalStatusCode) {
        this.functionalStatusCode = functionalStatusCode;
    }
    public String getFunctionalStatusDescription() {
        return this.functionalStatusDescription;
    }
    
    public void setFunctionalStatusDescription(String functionalStatusDescription) {
        this.functionalStatusDescription = functionalStatusDescription;
    }




}


