package com.vmmc.entities;
// Generated Jul 12, 2021 7:53:38 PM by Hibernate Tools 4.3.1



/**
 * Tblsetuptpteligibility generated by hbm2java
 */
public class Tblsetuptpteligibility  implements java.io.Serializable {


     private String tptEligibilityCode;
     private String tptEligibilityDescription;

    public Tblsetuptpteligibility() {
    }

	
    public Tblsetuptpteligibility(String tptEligibilityCode) {
        this.tptEligibilityCode = tptEligibilityCode;
    }
    public Tblsetuptpteligibility(String tptEligibilityCode, String tptEligibilityDescription) {
       this.tptEligibilityCode = tptEligibilityCode;
       this.tptEligibilityDescription = tptEligibilityDescription;
    }
   
    public String getTptEligibilityCode() {
        return this.tptEligibilityCode;
    }
    
    public void setTptEligibilityCode(String tptEligibilityCode) {
        this.tptEligibilityCode = tptEligibilityCode;
    }
    public String getTptEligibilityDescription() {
        return this.tptEligibilityDescription;
    }
    
    public void setTptEligibilityDescription(String tptEligibilityDescription) {
        this.tptEligibilityDescription = tptEligibilityDescription;
    }




}


