package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetuptestresults generated by hbm2java
 */
public class Tblsetuptestresults  implements java.io.Serializable {


     private String testResultId;
     private String testResult;
     private Integer confirmed;

    public Tblsetuptestresults() {
    }

	
    public Tblsetuptestresults(String testResultId) {
        this.testResultId = testResultId;
    }
    public Tblsetuptestresults(String testResultId, String testResult, Integer confirmed) {
       this.testResultId = testResultId;
       this.testResult = testResult;
       this.confirmed = confirmed;
    }
   
    public String getTestResultId() {
        return this.testResultId;
    }
    
    public void setTestResultId(String testResultId) {
        this.testResultId = testResultId;
    }
    public String getTestResult() {
        return this.testResult;
    }
    
    public void setTestResult(String testResult) {
        this.testResult = testResult;
    }
    public Integer getConfirmed() {
        return this.confirmed;
    }
    
    public void setConfirmed(Integer confirmed) {
        this.confirmed = confirmed;
    }




}


