package com.vmmc.entities;
// Generated Sep 15, 2020 10:19:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblsetupstaff generated by hbm2java
 */
public class Tblsetupstaff  implements java.io.Serializable {


     private int staffId;
     private String staffSurname;
     private String staffFirstname;
     private String role;
     private Set tblvisitses = new HashSet(0);

    public Tblsetupstaff() {
    }

	
    public Tblsetupstaff(int staffId) {
        this.staffId = staffId;
    }
    public Tblsetupstaff(int staffId, String staffSurname, String staffFirstname, String role, Set tblvisitses) {
       this.staffId = staffId;
       this.staffSurname = staffSurname;
       this.staffFirstname = staffFirstname;
       this.role = role;
       this.tblvisitses = tblvisitses;
    }
   
    public int getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(int staffId) {
        this.staffId = staffId;
    }
    public String getStaffSurname() {
        return this.staffSurname;
    }
    
    public void setStaffSurname(String staffSurname) {
        this.staffSurname = staffSurname;
    }
    public String getStaffFirstname() {
        return this.staffFirstname;
    }
    
    public void setStaffFirstname(String staffFirstname) {
        this.staffFirstname = staffFirstname;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set getTblvisitses() {
        return this.tblvisitses;
    }
    
    public void setTblvisitses(Set tblvisitses) {
        this.tblvisitses = tblvisitses;
    }




}


