package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblstatus generated by hbm2java
 */
public class Tblstatus  implements java.io.Serializable {


     private TblstatusId id;
     private Tblpatients tblpatients;
     private String status;
     private String transferOutToWhere;
     private String notes;

    public Tblstatus() {
    }

	
    public Tblstatus(TblstatusId id, Tblpatients tblpatients) {
        this.id = id;
        this.tblpatients = tblpatients;
    }
    public Tblstatus(TblstatusId id, Tblpatients tblpatients, String status, String transferOutToWhere, String notes) {
       this.id = id;
       this.tblpatients = tblpatients;
       this.status = status;
       this.transferOutToWhere = transferOutToWhere;
       this.notes = notes;
    }
   
    public TblstatusId getId() {
        return this.id;
    }
    
    public void setId(TblstatusId id) {
        this.id = id;
    }
    public Tblpatients getTblpatients() {
        return this.tblpatients;
    }
    
    public void setTblpatients(Tblpatients tblpatients) {
        this.tblpatients = tblpatients;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getTransferOutToWhere() {
        return this.transferOutToWhere;
    }
    
    public void setTransferOutToWhere(String transferOutToWhere) {
        this.transferOutToWhere = transferOutToWhere;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


