package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupdeliverymodes generated by hbm2java
 */
public class Tblsetupdeliverymodes  implements java.io.Serializable {


     private String deliveryModeId;
     private String deliveryMode;
     private String category;

    public Tblsetupdeliverymodes() {
    }

	
    public Tblsetupdeliverymodes(String deliveryModeId) {
        this.deliveryModeId = deliveryModeId;
    }
    public Tblsetupdeliverymodes(String deliveryModeId, String deliveryMode, String category) {
       this.deliveryModeId = deliveryModeId;
       this.deliveryMode = deliveryMode;
       this.category = category;
    }
   
    public String getDeliveryModeId() {
        return this.deliveryModeId;
    }
    
    public void setDeliveryModeId(String deliveryModeId) {
        this.deliveryModeId = deliveryModeId;
    }
    public String getDeliveryMode() {
        return this.deliveryMode;
    }
    
    public void setDeliveryMode(String deliveryMode) {
        this.deliveryMode = deliveryMode;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }




}


