package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblsetuparvreasoncodes generated by hbm2java
 */
public class Tblsetuparvreasoncodes  implements java.io.Serializable {


     private int arvreasonCode;
     private String arvreason;
     private String reasonCategory;
     private Integer medEligible;
     private Integer ready;
     private Set tblsetuparvstatuscodeses = new HashSet(0);

    public Tblsetuparvreasoncodes() {
    }

	
    public Tblsetuparvreasoncodes(int arvreasonCode) {
        this.arvreasonCode = arvreasonCode;
    }
    public Tblsetuparvreasoncodes(int arvreasonCode, String arvreason, String reasonCategory, Integer medEligible, Integer ready, Set tblsetuparvstatuscodeses) {
       this.arvreasonCode = arvreasonCode;
       this.arvreason = arvreason;
       this.reasonCategory = reasonCategory;
       this.medEligible = medEligible;
       this.ready = ready;
       this.tblsetuparvstatuscodeses = tblsetuparvstatuscodeses;
    }
   
    public int getArvreasonCode() {
        return this.arvreasonCode;
    }
    
    public void setArvreasonCode(int arvreasonCode) {
        this.arvreasonCode = arvreasonCode;
    }
    public String getArvreason() {
        return this.arvreason;
    }
    
    public void setArvreason(String arvreason) {
        this.arvreason = arvreason;
    }
    public String getReasonCategory() {
        return this.reasonCategory;
    }
    
    public void setReasonCategory(String reasonCategory) {
        this.reasonCategory = reasonCategory;
    }
    public Integer getMedEligible() {
        return this.medEligible;
    }
    
    public void setMedEligible(Integer medEligible) {
        this.medEligible = medEligible;
    }
    public Integer getReady() {
        return this.ready;
    }
    
    public void setReady(Integer ready) {
        this.ready = ready;
    }
    public Set getTblsetuparvstatuscodeses() {
        return this.tblsetuparvstatuscodeses;
    }
    
    public void setTblsetuparvstatuscodeses(Set tblsetuparvstatuscodeses) {
        this.tblsetuparvstatuscodeses = tblsetuparvstatuscodeses;
    }




}


