package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupreferralsto generated by hbm2java
 */
public class Tblsetupreferralsto  implements java.io.Serializable {


     private String referralToCode;
     private String referralTo;

    public Tblsetupreferralsto() {
    }

	
    public Tblsetupreferralsto(String referralToCode) {
        this.referralToCode = referralToCode;
    }
    public Tblsetupreferralsto(String referralToCode, String referralTo) {
       this.referralToCode = referralToCode;
       this.referralTo = referralTo;
    }
   
    public String getReferralToCode() {
        return this.referralToCode;
    }
    
    public void setReferralToCode(String referralToCode) {
        this.referralToCode = referralToCode;
    }
    public String getReferralTo() {
        return this.referralTo;
    }
    
    public void setReferralTo(String referralTo) {
        this.referralTo = referralTo;
    }




}


