package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetuporphanstatus generated by hbm2java
 */
public class Tblsetuporphanstatus  implements java.io.Serializable {


     private String orphanStatusId;
     private String orphanStatus;

    public Tblsetuporphanstatus() {
    }

	
    public Tblsetuporphanstatus(String orphanStatusId) {
        this.orphanStatusId = orphanStatusId;
    }
    public Tblsetuporphanstatus(String orphanStatusId, String orphanStatus) {
       this.orphanStatusId = orphanStatusId;
       this.orphanStatus = orphanStatus;
    }
   
    public String getOrphanStatusId() {
        return this.orphanStatusId;
    }
    
    public void setOrphanStatusId(String orphanStatusId) {
        this.orphanStatusId = orphanStatusId;
    }
    public String getOrphanStatus() {
        return this.orphanStatus;
    }
    
    public void setOrphanStatus(String orphanStatus) {
        this.orphanStatus = orphanStatus;
    }




}


