package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupdistricts generated by hbm2java
 */
public class Tblsetupdistricts  implements java.io.Serializable {


     private TblsetupdistrictsId id;
     private Tblsetupregions tblsetupregions;
     private String district;

    public Tblsetupdistricts() {
    }

	
    public Tblsetupdistricts(TblsetupdistrictsId id, Tblsetupregions tblsetupregions) {
        this.id = id;
        this.tblsetupregions = tblsetupregions;
    }
    public Tblsetupdistricts(TblsetupdistrictsId id, Tblsetupregions tblsetupregions, String district) {
       this.id = id;
       this.tblsetupregions = tblsetupregions;
       this.district = district;
    }
   
    public TblsetupdistrictsId getId() {
        return this.id;
    }
    
    public void setId(TblsetupdistrictsId id) {
        this.id = id;
    }
    public Tblsetupregions getTblsetupregions() {
        return this.tblsetupregions;
    }
    
    public void setTblsetupregions(Tblsetupregions tblsetupregions) {
        this.tblsetupregions = tblsetupregions;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }




}


