package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupvisitstatus generated by hbm2java
 */
public class Tblsetupvisitstatus  implements java.io.Serializable {


     private String visitstatuscode;
     private String visitstatusdescription;

    public Tblsetupvisitstatus() {
    }

    public Tblsetupvisitstatus(String visitstatuscode, String visitstatusdescription) {
       this.visitstatuscode = visitstatuscode;
       this.visitstatusdescription = visitstatusdescription;
    }
   
    public String getVisitstatuscode() {
        return this.visitstatuscode;
    }
    
    public void setVisitstatuscode(String visitstatuscode) {
        this.visitstatuscode = visitstatuscode;
    }
    public String getVisitstatusdescription() {
        return this.visitstatusdescription;
    }
    
    public void setVisitstatusdescription(String visitstatusdescription) {
        this.visitstatusdescription = visitstatusdescription;
    }




}


