package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupmaritalstatus generated by hbm2java
 */
public class Tblsetupmaritalstatus  implements java.io.Serializable {


     private String maritalStatusCode;
     private String maritalStatus;

    public Tblsetupmaritalstatus() {
    }

	
    public Tblsetupmaritalstatus(String maritalStatusCode) {
        this.maritalStatusCode = maritalStatusCode;
    }
    public Tblsetupmaritalstatus(String maritalStatusCode, String maritalStatus) {
       this.maritalStatusCode = maritalStatusCode;
       this.maritalStatus = maritalStatus;
    }
   
    public String getMaritalStatusCode() {
        return this.maritalStatusCode;
    }
    
    public void setMaritalStatusCode(String maritalStatusCode) {
        this.maritalStatusCode = maritalStatusCode;
    }
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }




}


