package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetuptbstatus generated by hbm2java
 */
public class Tblsetuptbstatus  implements java.io.Serializable {


     private String tbstatusCode;
     private String tbstatusDescription;
     private Integer hasTb;
     private Integer tbsuspected;
     private Integer tbscreened;

    public Tblsetuptbstatus() {
    }

	
    public Tblsetuptbstatus(String tbstatusCode) {
        this.tbstatusCode = tbstatusCode;
    }
    public Tblsetuptbstatus(String tbstatusCode, String tbstatusDescription, Integer hasTb, Integer tbsuspected, Integer tbscreened) {
       this.tbstatusCode = tbstatusCode;
       this.tbstatusDescription = tbstatusDescription;
       this.hasTb = hasTb;
       this.tbsuspected = tbsuspected;
       this.tbscreened = tbscreened;
    }
   
    public String getTbstatusCode() {
        return this.tbstatusCode;
    }
    
    public void setTbstatusCode(String tbstatusCode) {
        this.tbstatusCode = tbstatusCode;
    }
    public String getTbstatusDescription() {
        return this.tbstatusDescription;
    }
    
    public void setTbstatusDescription(String tbstatusDescription) {
        this.tbstatusDescription = tbstatusDescription;
    }
    public Integer getHasTb() {
        return this.hasTb;
    }
    
    public void setHasTb(Integer hasTb) {
        this.hasTb = hasTb;
    }
    public Integer getTbsuspected() {
        return this.tbsuspected;
    }
    
    public void setTbsuspected(Integer tbsuspected) {
        this.tbsuspected = tbsuspected;
    }
    public Integer getTbscreened() {
        return this.tbscreened;
    }
    
    public void setTbscreened(Integer tbscreened) {
        this.tbscreened = tbscreened;
    }




}


