package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupnosfacilities generated by hbm2java
 */
public class Tblsetupnosfacilities  implements java.io.Serializable {


     private String fullFacilityCode;

    public Tblsetupnosfacilities() {
    }

    public Tblsetupnosfacilities(String fullFacilityCode) {
       this.fullFacilityCode = fullFacilityCode;
    }
   
    public String getFullFacilityCode() {
        return this.fullFacilityCode;
    }
    
    public void setFullFacilityCode(String fullFacilityCode) {
        this.fullFacilityCode = fullFacilityCode;
    }




}


