package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupdrugtypes generated by hbm2java
 */
public class Tblsetupdrugtypes  implements java.io.Serializable {


     private String drugTypeId;
     private String drugType;
     private Integer initialVisitPriorExposure;
     private Integer everyVisit;
     private Integer forInfants;

    public Tblsetupdrugtypes() {
    }

	
    public Tblsetupdrugtypes(String drugTypeId) {
        this.drugTypeId = drugTypeId;
    }
    public Tblsetupdrugtypes(String drugTypeId, String drugType, Integer initialVisitPriorExposure, Integer everyVisit, Integer forInfants) {
       this.drugTypeId = drugTypeId;
       this.drugType = drugType;
       this.initialVisitPriorExposure = initialVisitPriorExposure;
       this.everyVisit = everyVisit;
       this.forInfants = forInfants;
    }
   
    public String getDrugTypeId() {
        return this.drugTypeId;
    }
    
    public void setDrugTypeId(String drugTypeId) {
        this.drugTypeId = drugTypeId;
    }
    public String getDrugType() {
        return this.drugType;
    }
    
    public void setDrugType(String drugType) {
        this.drugType = drugType;
    }
    public Integer getInitialVisitPriorExposure() {
        return this.initialVisitPriorExposure;
    }
    
    public void setInitialVisitPriorExposure(Integer initialVisitPriorExposure) {
        this.initialVisitPriorExposure = initialVisitPriorExposure;
    }
    public Integer getEveryVisit() {
        return this.everyVisit;
    }
    
    public void setEveryVisit(Integer everyVisit) {
        this.everyVisit = everyVisit;
    }
    public Integer getForInfants() {
        return this.forInfants;
    }
    
    public void setForInfants(Integer forInfants) {
        this.forInfants = forInfants;
    }




}


