package com.vmmc.entities;
// Generated Jun 15, 2020 12:43:23 PM by Hibernate Tools 4.3.1



/**
 * Tblsetuptpttype generated by hbm2java
 */
public class Tblsetuptpttype  implements java.io.Serializable {


     private Integer id;
     private String typeoftpt;

    public Tblsetuptpttype() {
    }

    public Tblsetuptpttype(String typeoftpt) {
       this.typeoftpt = typeoftpt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTypeoftpt() {
        return this.typeoftpt;
    }
    
    public void setTypeoftpt(String typeoftpt) {
        this.typeoftpt = typeoftpt;
    }




}


