package com.vmmc.entities;
// Generated Sep 15, 2020 9:37:50 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupiptreasoncodes generated by hbm2java
 */
public class Tblsetupiptreasoncodes  implements java.io.Serializable {


     private int tptId;
     private String iptreason;
     private String iptreasonCode;

    public Tblsetupiptreasoncodes() {
    }

	
    public Tblsetupiptreasoncodes(int tptId) {
        this.tptId = tptId;
    }
    public Tblsetupiptreasoncodes(int tptId, String iptreason, String iptreasonCode) {
       this.tptId = tptId;
       this.iptreason = iptreason;
       this.iptreasonCode = iptreasonCode;
    }
   
    public int getTptId() {
        return this.tptId;
    }
    
    public void setTptId(int tptId) {
        this.tptId = tptId;
    }
    public String getIptreason() {
        return this.iptreason;
    }
    
    public void setIptreason(String iptreason) {
        this.iptreason = iptreason;
    }
    public String getIptreasonCode() {
        return this.iptreasonCode;
    }
    
    public void setIptreasonCode(String iptreasonCode) {
        this.iptreasonCode = iptreasonCode;
    }




}


