package com.vmmc.entities;
// Generated Jul 5, 2021 12:52:57 PM by Hibernate Tools 4.3.1



/**
 * Tblsetuppatientprofile generated by hbm2java
 */
public class Tblsetuppatientprofile  implements java.io.Serializable {


     private char patientProfileCode;
     private String patientProfileDescription;

    public Tblsetuppatientprofile() {
    }

	
    public Tblsetuppatientprofile(char patientProfileCode) {
        this.patientProfileCode = patientProfileCode;
    }
    public Tblsetuppatientprofile(char patientProfileCode, String patientProfileDescription) {
       this.patientProfileCode = patientProfileCode;
       this.patientProfileDescription = patientProfileDescription;
    }
   
    public char getPatientProfileCode() {
        return this.patientProfileCode;
    }
    
    public void setPatientProfileCode(char patientProfileCode) {
        this.patientProfileCode = patientProfileCode;
    }
    public String getPatientProfileDescription() {
        return this.patientProfileDescription;
    }
    
    public void setPatientProfileDescription(String patientProfileDescription) {
        this.patientProfileDescription = patientProfileDescription;
    }




}


