package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupvisittypes generated by hbm2java
 */
public class Tblsetupvisittypes  implements java.io.Serializable {


     private String visitTypeCode;
     private String visitType;
     private String visitTypeLong;
     private Integer theOrder;
     private Integer forStandard;
     private Integer forInfants;
     private Integer dsdclinical;
     private Integer dsdrefil;

    public Tblsetupvisittypes() {
    }

	
    public Tblsetupvisittypes(String visitTypeCode) {
        this.visitTypeCode = visitTypeCode;
    }
    public Tblsetupvisittypes(String visitTypeCode, String visitType, String visitTypeLong, Integer theOrder, Integer forStandard, Integer forInfants, Integer dsdclinical, Integer dsdrefil) {
       this.visitTypeCode = visitTypeCode;
       this.visitType = visitType;
       this.visitTypeLong = visitTypeLong;
       this.theOrder = theOrder;
       this.forStandard = forStandard;
       this.forInfants = forInfants;
       this.dsdclinical = dsdclinical;
       this.dsdrefil = dsdrefil;
    }
   
    public String getVisitTypeCode() {
        return this.visitTypeCode;
    }
    
    public void setVisitTypeCode(String visitTypeCode) {
        this.visitTypeCode = visitTypeCode;
    }
    public String getVisitType() {
        return this.visitType;
    }
    
    public void setVisitType(String visitType) {
        this.visitType = visitType;
    }
    public String getVisitTypeLong() {
        return this.visitTypeLong;
    }
    
    public void setVisitTypeLong(String visitTypeLong) {
        this.visitTypeLong = visitTypeLong;
    }
    public Integer getTheOrder() {
        return this.theOrder;
    }
    
    public void setTheOrder(Integer theOrder) {
        this.theOrder = theOrder;
    }
    public Integer getForStandard() {
        return this.forStandard;
    }
    
    public void setForStandard(Integer forStandard) {
        this.forStandard = forStandard;
    }
    public Integer getForInfants() {
        return this.forInfants;
    }
    
    public void setForInfants(Integer forInfants) {
        this.forInfants = forInfants;
    }
    public Integer getDsdclinical() {
        return this.dsdclinical;
    }
    
    public void setDsdclinical(Integer dsdclinical) {
        this.dsdclinical = dsdclinical;
    }
    public Integer getDsdrefil() {
        return this.dsdrefil;
    }
    
    public void setDsdrefil(Integer dsdrefil) {
        this.dsdrefil = dsdrefil;
    }




}


