package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * TblsetupdistrictsId generated by hbm2java
 */
public class TblsetupdistrictsId  implements java.io.Serializable {


     private int regionCode;
     private String districtCode;

    public TblsetupdistrictsId() {
    }

    public TblsetupdistrictsId(int regionCode, String districtCode) {
       this.regionCode = regionCode;
       this.districtCode = districtCode;
    }
   
    public int getRegionCode() {
        return this.regionCode;
    }
    
    public void setRegionCode(int regionCode) {
        this.regionCode = regionCode;
    }
    public String getDistrictCode() {
        return this.districtCode;
    }
    
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblsetupdistrictsId) ) return false;
		 TblsetupdistrictsId castOther = ( TblsetupdistrictsId ) other; 
         
		 return (this.getRegionCode()==castOther.getRegionCode())
 && ( (this.getDistrictCode()==castOther.getDistrictCode()) || ( this.getDistrictCode()!=null && castOther.getDistrictCode()!=null && this.getDistrictCode().equals(castOther.getDistrictCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRegionCode();
         result = 37 * result + ( getDistrictCode() == null ? 0 : this.getDistrictCode().hashCode() );
         return result;
   }   


}


