package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupinfantfeedingpractices generated by hbm2java
 */
public class Tblsetupinfantfeedingpractices  implements java.io.Serializable {


     private String feedingPracticeId;
     private String feedingPractice;
     private String feedingPracticeDescription;
     private Integer numCode;
     private Integer exposedToHiv;

    public Tblsetupinfantfeedingpractices() {
    }

	
    public Tblsetupinfantfeedingpractices(String feedingPracticeId) {
        this.feedingPracticeId = feedingPracticeId;
    }
    public Tblsetupinfantfeedingpractices(String feedingPracticeId, String feedingPractice, String feedingPracticeDescription, Integer numCode, Integer exposedToHiv) {
       this.feedingPracticeId = feedingPracticeId;
       this.feedingPractice = feedingPractice;
       this.feedingPracticeDescription = feedingPracticeDescription;
       this.numCode = numCode;
       this.exposedToHiv = exposedToHiv;
    }
   
    public String getFeedingPracticeId() {
        return this.feedingPracticeId;
    }
    
    public void setFeedingPracticeId(String feedingPracticeId) {
        this.feedingPracticeId = feedingPracticeId;
    }
    public String getFeedingPractice() {
        return this.feedingPractice;
    }
    
    public void setFeedingPractice(String feedingPractice) {
        this.feedingPractice = feedingPractice;
    }
    public String getFeedingPracticeDescription() {
        return this.feedingPracticeDescription;
    }
    
    public void setFeedingPracticeDescription(String feedingPracticeDescription) {
        this.feedingPracticeDescription = feedingPracticeDescription;
    }
    public Integer getNumCode() {
        return this.numCode;
    }
    
    public void setNumCode(Integer numCode) {
        this.numCode = numCode;
    }
    public Integer getExposedToHiv() {
        return this.exposedToHiv;
    }
    
    public void setExposedToHiv(Integer exposedToHiv) {
        this.exposedToHiv = exposedToHiv;
    }




}


