package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblsetupdispensers generated by hbm2java
 */
public class Tblsetupdispensers  implements java.io.Serializable {


     private int dispenserId;
     private String dispenserFirstName;
     private String dispenserSurname;
     private Integer userNumber;
     private Set tbldispenses = new HashSet(0);

    public Tblsetupdispensers() {
    }

	
    public Tblsetupdispensers(int dispenserId) {
        this.dispenserId = dispenserId;
    }
    public Tblsetupdispensers(int dispenserId, String dispenserFirstName, String dispenserSurname, Integer userNumber, Set tbldispenses) {
       this.dispenserId = dispenserId;
       this.dispenserFirstName = dispenserFirstName;
       this.dispenserSurname = dispenserSurname;
       this.userNumber = userNumber;
       this.tbldispenses = tbldispenses;
    }
   
    public int getDispenserId() {
        return this.dispenserId;
    }
    
    public void setDispenserId(int dispenserId) {
        this.dispenserId = dispenserId;
    }
    public String getDispenserFirstName() {
        return this.dispenserFirstName;
    }
    
    public void setDispenserFirstName(String dispenserFirstName) {
        this.dispenserFirstName = dispenserFirstName;
    }
    public String getDispenserSurname() {
        return this.dispenserSurname;
    }
    
    public void setDispenserSurname(String dispenserSurname) {
        this.dispenserSurname = dispenserSurname;
    }
    public Integer getUserNumber() {
        return this.userNumber;
    }
    
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }
    public Set getTbldispenses() {
        return this.tbldispenses;
    }
    
    public void setTbldispenses(Set tbldispenses) {
        this.tbldispenses = tbldispenses;
    }




}


