package com.vmmc.entities;
// Generated Jul 5, 2021 12:52:57 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupartinitiationcategory generated by hbm2java
 */
public class Tblsetupartinitiationcategory  implements java.io.Serializable {


     private String artInitiationCategoryCode;
     private String artInitiationCategoryDescription;

    public Tblsetupartinitiationcategory() {
    }

	
    public Tblsetupartinitiationcategory(String artInitiationCategoryCode) {
        this.artInitiationCategoryCode = artInitiationCategoryCode;
    }
    public Tblsetupartinitiationcategory(String artInitiationCategoryCode, String artInitiationCategoryDescription) {
       this.artInitiationCategoryCode = artInitiationCategoryCode;
       this.artInitiationCategoryDescription = artInitiationCategoryDescription;
    }
   
    public String getArtInitiationCategoryCode() {
        return this.artInitiationCategoryCode;
    }
    
    public void setArtInitiationCategoryCode(String artInitiationCategoryCode) {
        this.artInitiationCategoryCode = artInitiationCategoryCode;
    }
    public String getArtInitiationCategoryDescription() {
        return this.artInitiationCategoryDescription;
    }
    
    public void setArtInitiationCategoryDescription(String artInitiationCategoryDescription) {
        this.artInitiationCategoryDescription = artInitiationCategoryDescription;
    }




}


