package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupledgerentrytypes generated by hbm2java
 */
public class Tblsetupledgerentrytypes  implements java.io.Serializable {


     private String ledgerEntryTypeCode;
     private String ledgerEntryType;
     private String posOrNeg;

    public Tblsetupledgerentrytypes() {
    }

	
    public Tblsetupledgerentrytypes(String ledgerEntryTypeCode) {
        this.ledgerEntryTypeCode = ledgerEntryTypeCode;
    }
    public Tblsetupledgerentrytypes(String ledgerEntryTypeCode, String ledgerEntryType, String posOrNeg) {
       this.ledgerEntryTypeCode = ledgerEntryTypeCode;
       this.ledgerEntryType = ledgerEntryType;
       this.posOrNeg = posOrNeg;
    }
   
    public String getLedgerEntryTypeCode() {
        return this.ledgerEntryTypeCode;
    }
    
    public void setLedgerEntryTypeCode(String ledgerEntryTypeCode) {
        this.ledgerEntryTypeCode = ledgerEntryTypeCode;
    }
    public String getLedgerEntryType() {
        return this.ledgerEntryType;
    }
    
    public void setLedgerEntryType(String ledgerEntryType) {
        this.ledgerEntryType = ledgerEntryType;
    }
    public String getPosOrNeg() {
        return this.posOrNeg;
    }
    
    public void setPosOrNeg(String posOrNeg) {
        this.posOrNeg = posOrNeg;
    }




}


