package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupstatus generated by hbm2java
 */
public class Tblsetupstatus  implements java.io.Serializable {


     private String status;
     private String statusType;
     private String statusCode;
     private Integer forStandard;
     private String infantStatusCode;
     private String infantStatusDesc;

    public Tblsetupstatus() {
    }

	
    public Tblsetupstatus(String status) {
        this.status = status;
    }
    public Tblsetupstatus(String status, String statusType, String statusCode, Integer forStandard, String infantStatusCode, String infantStatusDesc) {
       this.status = status;
       this.statusType = statusType;
       this.statusCode = statusCode;
       this.forStandard = forStandard;
       this.infantStatusCode = infantStatusCode;
       this.infantStatusDesc = infantStatusDesc;
    }
   
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getStatusType() {
        return this.statusType;
    }
    
    public void setStatusType(String statusType) {
        this.statusType = statusType;
    }
    public String getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }
    public Integer getForStandard() {
        return this.forStandard;
    }
    
    public void setForStandard(Integer forStandard) {
        this.forStandard = forStandard;
    }
    public String getInfantStatusCode() {
        return this.infantStatusCode;
    }
    
    public void setInfantStatusCode(String infantStatusCode) {
        this.infantStatusCode = infantStatusCode;
    }
    public String getInfantStatusDesc() {
        return this.infantStatusDesc;
    }
    
    public void setInfantStatusDesc(String infantStatusDesc) {
        this.infantStatusDesc = infantStatusDesc;
    }




}


