package com.vmmc.entities;
// Generated Jul 5, 2021 12:52:57 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupcervicalcancertreatment generated by hbm2java
 */
public class Tblsetupcervicalcancertreatment  implements java.io.Serializable {


     private String cervicalCancerTreatmentCode;
     private String cervicalCancerTreatmentDescription;

    public Tblsetupcervicalcancertreatment() {
    }

	
    public Tblsetupcervicalcancertreatment(String cervicalCancerTreatmentCode) {
        this.cervicalCancerTreatmentCode = cervicalCancerTreatmentCode;
    }
    public Tblsetupcervicalcancertreatment(String cervicalCancerTreatmentCode, String cervicalCancerTreatmentDescription) {
       this.cervicalCancerTreatmentCode = cervicalCancerTreatmentCode;
       this.cervicalCancerTreatmentDescription = cervicalCancerTreatmentDescription;
    }
   
    public String getCervicalCancerTreatmentCode() {
        return this.cervicalCancerTreatmentCode;
    }
    
    public void setCervicalCancerTreatmentCode(String cervicalCancerTreatmentCode) {
        this.cervicalCancerTreatmentCode = cervicalCancerTreatmentCode;
    }
    public String getCervicalCancerTreatmentDescription() {
        return this.cervicalCancerTreatmentDescription;
    }
    
    public void setCervicalCancerTreatmentDescription(String cervicalCancerTreatmentDescription) {
        this.cervicalCancerTreatmentDescription = cervicalCancerTreatmentDescription;
    }




}


