package com.vmmc.entities;
// Generated Jul 5, 2021 12:52:57 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupcryptococcalinvestigation generated by hbm2java
 */
public class Tblsetupcryptococcalinvestigation  implements java.io.Serializable {


     private String cryptococcalInvestigationCode;
     private String cryptococcalInvestigationDescription;

    public Tblsetupcryptococcalinvestigation() {
    }

	
    public Tblsetupcryptococcalinvestigation(String cryptococcalInvestigationCode) {
        this.cryptococcalInvestigationCode = cryptococcalInvestigationCode;
    }
    public Tblsetupcryptococcalinvestigation(String cryptococcalInvestigationCode, String cryptococcalInvestigationDescription) {
       this.cryptococcalInvestigationCode = cryptococcalInvestigationCode;
       this.cryptococcalInvestigationDescription = cryptococcalInvestigationDescription;
    }
   
    public String getCryptococcalInvestigationCode() {
        return this.cryptococcalInvestigationCode;
    }
    
    public void setCryptococcalInvestigationCode(String cryptococcalInvestigationCode) {
        this.cryptococcalInvestigationCode = cryptococcalInvestigationCode;
    }
    public String getCryptococcalInvestigationDescription() {
        return this.cryptococcalInvestigationDescription;
    }
    
    public void setCryptococcalInvestigationDescription(String cryptococcalInvestigationDescription) {
        this.cryptococcalInvestigationDescription = cryptococcalInvestigationDescription;
    }




}


