package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Tblsetupfamilyplanning generated by hbm2java
 */
public class Tblsetupfamilyplanning  implements java.io.Serializable {


     private String familyPlanningId;
     private String familyPlanningMethod;
     private Integer theOrder;

    public Tblsetupfamilyplanning() {
    }

	
    public Tblsetupfamilyplanning(String familyPlanningId) {
        this.familyPlanningId = familyPlanningId;
    }
    public Tblsetupfamilyplanning(String familyPlanningId, String familyPlanningMethod, Integer theOrder) {
       this.familyPlanningId = familyPlanningId;
       this.familyPlanningMethod = familyPlanningMethod;
       this.theOrder = theOrder;
    }
   
    public String getFamilyPlanningId() {
        return this.familyPlanningId;
    }
    
    public void setFamilyPlanningId(String familyPlanningId) {
        this.familyPlanningId = familyPlanningId;
    }
    public String getFamilyPlanningMethod() {
        return this.familyPlanningMethod;
    }
    
    public void setFamilyPlanningMethod(String familyPlanningMethod) {
        this.familyPlanningMethod = familyPlanningMethod;
    }
    public Integer getTheOrder() {
        return this.theOrder;
    }
    
    public void setTheOrder(Integer theOrder) {
        this.theOrder = theOrder;
    }




}


