package com.vmmc.entities;
// Generated Jul 12, 2021 7:36:41 PM by Hibernate Tools 4.3.1



/**
 * Tblsetuptbinvestigation generated by hbm2java
 */
public class Tblsetuptbinvestigation  implements java.io.Serializable {


     private int tbInvestigationId;
     private String tbInvestigation;

    public Tblsetuptbinvestigation() {
    }

	
    public Tblsetuptbinvestigation(int tbInvestigationId) {
        this.tbInvestigationId = tbInvestigationId;
    }
    public Tblsetuptbinvestigation(int tbInvestigationId, String tbInvestigation) {
       this.tbInvestigationId = tbInvestigationId;
       this.tbInvestigation = tbInvestigation;
    }
   
    public int getTbInvestigationId() {
        return this.tbInvestigationId;
    }
    
    public void setTbInvestigationId(int tbInvestigationId) {
        this.tbInvestigationId = tbInvestigationId;
    }
    public String getTbInvestigation() {
        return this.tbInvestigation;
    }
    
    public void setTbInvestigation(String tbInvestigation) {
        this.tbInvestigation = tbInvestigation;
    }




}


