package com.vmmc.entities;
// Generated Mar 25, 2021 10:43:50 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Tbltests generated by hbm2java
 */
public class Tbltests implements java.io.Serializable {

    private Integer theId;
    private Tblpatients tblpatients;
    private String testTypeId;
    private Date testDate;
    private Date resultDate;
    private Float resultNumeric;
    private String resultNotes;
    private Date recievedDate;

    public Tbltests() {
    }

    public Tbltests(Tblpatients tblpatients, String testTypeId, Date testDate, Date resultDate, Float resultNumeric, String resultNotes, Date recievedDate) {

        this.tblpatients = tblpatients;
        this.testTypeId = testTypeId;
        this.testDate = testDate;
        this.resultDate = resultDate;
        this.resultNumeric = resultNumeric;
        this.resultNotes = resultNotes;
        this.recievedDate = recievedDate;
    }

    public Integer getTheId() {
        return this.theId;
    }

    public void setTheId(Integer theId) {
        this.theId = theId;
    }

    public Tblpatients getTblpatients() {
        return this.tblpatients;
    }

    public void setTblpatients(Tblpatients tblpatients) {
        this.tblpatients = tblpatients;
    }

    public String getTestTypeId() {
        return this.testTypeId;
    }

    public void setTestTypeId(String testTypeId) {
        this.testTypeId = testTypeId;
    }

    public Date getTestDate() {
        return this.testDate;
    }

    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    public Date getResultDate() {
        return this.resultDate;
    }

    public void setResultDate(Date resultDate) {
        this.resultDate = resultDate;
    }

    public Float getResultNumeric() {
        return this.resultNumeric;
    }

    public void setResultNumeric(Float resultNumeric) {
        this.resultNumeric = resultNumeric;
    }

    public String getResultNotes() {
        return this.resultNotes;
    }

    public void setResultNotes(String resultNotes) {
        this.resultNotes = resultNotes;
    }

    public Date getRecievedDate() {
        return this.recievedDate;
    }

    public void setRecievedDate(Date recievedDate) {
        this.recievedDate = recievedDate;
    }
}
