package com.vmmc.entities;
// Generated Jul 12, 2021 5:45:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblvisitsId generated by hbm2java
 */
public class TblvisitsId  implements java.io.Serializable {


     private String patientId;
     private Date visitDate;

    public TblvisitsId() {
    }

    public TblvisitsId(String patientId, Date visitDate) {
       this.patientId = patientId;
       this.visitDate = visitDate;
    }
   
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public Date getVisitDate() {
        return this.visitDate;
    }
    
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblvisitsId) ) return false;
		 TblvisitsId castOther = ( TblvisitsId ) other; 
         
		 return ( (this.getPatientId()==castOther.getPatientId()) || ( this.getPatientId()!=null && castOther.getPatientId()!=null && this.getPatientId().equals(castOther.getPatientId()) ) )
 && ( (this.getVisitDate()==castOther.getVisitDate()) || ( this.getVisitDate()!=null && castOther.getVisitDate()!=null && this.getVisitDate().equals(castOther.getVisitDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientId() == null ? 0 : this.getPatientId().hashCode() );
         result = 37 * result + ( getVisitDate() == null ? 0 : this.getVisitDate().hashCode() );
         return result;
   }   


}


