package com.vmmc.entities;
// Generated Mar 25, 2021 10:55:32 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblvisits generated by hbm2java
 */
public class Tblvisits  implements java.io.Serializable {


     private TblvisitsId id;
     private String visitType;
     private String visitTypeCode;
     private String visitStatusCode;
     private String nowPregnant;
     private String familyPlanningId;
     private String functionalStatusCode;
     private Integer whostage;
     private String tbstatusCode;
     private String iptreasonCode;
     private String typeOfTpt;
     private Integer arvstatusCode;
     private Integer arvreasonCode;
     private Integer arvcode;
     private String notes;
     private Integer staffId;
     private Integer userNumber;
     private Date theTimeStamp;
     private String adverseEventsStatusCode;
     private Integer dispenserId;
     private Date dateOfFirstAnc;
     private Date lnmpdate;
     private Integer tbinvestigationResults;
     private String isIpteligibility;
     private String iptstatusCode;

    public Tblvisits() {
    }

	
    public Tblvisits(TblvisitsId id) {
        this.id = id;
    }
    public Tblvisits(TblvisitsId id, String visitType, String visitTypeCode, String visitStatusCode, String nowPregnant, String familyPlanningId, String functionalStatusCode, Integer whostage, String tbstatusCode, String iptreasonCode, String typeOfTpt, Integer arvstatusCode, Integer arvreasonCode, Integer arvcode, String notes, Integer staffId, Integer userNumber, Date theTimeStamp, String adverseEventsStatusCode, Integer dispenserId, Date dateOfFirstAnc, Date lnmpdate, Integer tbinvestigationResults, String isIpteligibility, String iptstatusCode) {
       this.id = id;
       this.visitType = visitType;
       this.visitTypeCode = visitTypeCode;
       this.visitStatusCode = visitStatusCode;
       this.nowPregnant = nowPregnant;
       this.familyPlanningId = familyPlanningId;
       this.functionalStatusCode = functionalStatusCode;
       this.whostage = whostage;
       this.tbstatusCode = tbstatusCode;
       this.iptreasonCode = iptreasonCode;
       this.typeOfTpt = typeOfTpt;
       this.arvstatusCode = arvstatusCode;
       this.arvreasonCode = arvreasonCode;
       this.arvcode = arvcode;
       this.notes = notes;
       this.staffId = staffId;
       this.userNumber = userNumber;
       this.theTimeStamp = theTimeStamp;
       this.adverseEventsStatusCode = adverseEventsStatusCode;
       this.dispenserId = dispenserId;
       this.dateOfFirstAnc = dateOfFirstAnc;
       this.lnmpdate = lnmpdate;
       this.tbinvestigationResults = tbinvestigationResults;
       this.isIpteligibility = isIpteligibility;
       this.iptstatusCode = iptstatusCode;
    }
   
    public TblvisitsId getId() {
        return this.id;
    }
    
    public void setId(TblvisitsId id) {
        this.id = id;
    }
    public String getVisitType() {
        return this.visitType;
    }
    
    public void setVisitType(String visitType) {
        this.visitType = visitType;
    }
    public String getVisitTypeCode() {
        return this.visitTypeCode;
    }
    
    public void setVisitTypeCode(String visitTypeCode) {
        this.visitTypeCode = visitTypeCode;
    }
    public String getVisitStatusCode() {
        return this.visitStatusCode;
    }
    
    public void setVisitStatusCode(String visitStatusCode) {
        this.visitStatusCode = visitStatusCode;
    }
    public String getNowPregnant() {
        return this.nowPregnant;
    }
    
    public void setNowPregnant(String nowPregnant) {
        this.nowPregnant = nowPregnant;
    }
    public String getFamilyPlanningId() {
        return this.familyPlanningId;
    }
    
    public void setFamilyPlanningId(String familyPlanningId) {
        this.familyPlanningId = familyPlanningId;
    }
    public String getFunctionalStatusCode() {
        return this.functionalStatusCode;
    }
    
    public void setFunctionalStatusCode(String functionalStatusCode) {
        this.functionalStatusCode = functionalStatusCode;
    }
    public Integer getWhostage() {
        return this.whostage;
    }
    
    public void setWhostage(Integer whostage) {
        this.whostage = whostage;
    }
    public String getTbstatusCode() {
        return this.tbstatusCode;
    }
    
    public void setTbstatusCode(String tbstatusCode) {
        this.tbstatusCode = tbstatusCode;
    }
    public String getIptreasonCode() {
        return this.iptreasonCode;
    }
    
    public void setIptreasonCode(String iptreasonCode) {
        this.iptreasonCode = iptreasonCode;
    }
    public String getTypeOfTpt() {
        return this.typeOfTpt;
    }
    
    public void setTypeOfTpt(String typeOfTpt) {
        this.typeOfTpt = typeOfTpt;
    }
    public Integer getArvstatusCode() {
        return this.arvstatusCode;
    }
    
    public void setArvstatusCode(Integer arvstatusCode) {
        this.arvstatusCode = arvstatusCode;
    }
    public Integer getArvreasonCode() {
        return this.arvreasonCode;
    }
    
    public void setArvreasonCode(Integer arvreasonCode) {
        this.arvreasonCode = arvreasonCode;
    }
    public Integer getArvcode() {
        return this.arvcode;
    }
    
    public void setArvcode(Integer arvcode) {
        this.arvcode = arvcode;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Integer getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }
    public Integer getUserNumber() {
        return this.userNumber;
    }
    
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }
    public Date getTheTimeStamp() {
        return this.theTimeStamp;
    }
    
    public void setTheTimeStamp(Date theTimeStamp) {
        this.theTimeStamp = theTimeStamp;
    }
    public String getAdverseEventsStatusCode() {
        return this.adverseEventsStatusCode;
    }
    
    public void setAdverseEventsStatusCode(String adverseEventsStatusCode) {
        this.adverseEventsStatusCode = adverseEventsStatusCode;
    }
    public Integer getDispenserId() {
        return this.dispenserId;
    }
    
    public void setDispenserId(Integer dispenserId) {
        this.dispenserId = dispenserId;
    }
    public Date getDateOfFirstAnc() {
        return this.dateOfFirstAnc;
    }
    
    public void setDateOfFirstAnc(Date dateOfFirstAnc) {
        this.dateOfFirstAnc = dateOfFirstAnc;
    }
    public Date getLnmpdate() {
        return this.lnmpdate;
    }
    
    public void setLnmpdate(Date lnmpdate) {
        this.lnmpdate = lnmpdate;
    }
    public Integer getTbinvestigationResults() {
        return this.tbinvestigationResults;
    }
    
    public void setTbinvestigationResults(Integer tbinvestigationResults) {
        this.tbinvestigationResults = tbinvestigationResults;
    }
    public String getIsIpteligibility() {
        return this.isIpteligibility;
    }
    
    public void setIsIpteligibility(String isIpteligibility) {
        this.isIpteligibility = isIpteligibility;
    }
    public String getIptstatusCode() {
        return this.iptstatusCode;
    }
    
    public void setIptstatusCode(String iptstatusCode) {
        this.iptstatusCode = iptstatusCode;
    }




}


