package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Userrole generated by hbm2java
 */
public class Userrole  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String roleId;

    public Userrole() {
    }

    public Userrole(String userName, String roleId) {
       this.userName = userName;
       this.roleId = roleId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }




}


