package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String middleName;
     private String lastName;
     private String userName;
     private String password;
     private String email;
     private String position;
     private Boolean isActive;
     private Date lastLogIn;
     private Date dateCreated;
     private Date dateModified;
     private Integer provinceId;
     private Integer districtId;
     private Integer facilityId;

    public User() {
    }

    public User(String firstName, String middleName, String lastName, String userName, String password, String email, String position, Boolean isActive, Date lastLogIn, Date dateCreated, Date dateModified, Integer provinceId, Integer districtId, Integer facilityId) {
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.userName = userName;
       this.password = password;
       this.email = email;
       this.position = position;
       this.isActive = isActive;
       this.lastLogIn = lastLogIn;
       this.dateCreated = dateCreated;
       this.dateModified = dateModified;
       this.provinceId = provinceId;
       this.districtId = districtId;
       this.facilityId = facilityId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Date getLastLogIn() {
        return this.lastLogIn;
    }
    
    public void setLastLogIn(Date lastLogIn) {
        this.lastLogIn = lastLogIn;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
    public Integer getProvinceId() {
        return this.provinceId;
    }
    
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }
    public Integer getDistrictId() {
        return this.districtId;
    }
    
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }
    public Integer getFacilityId() {
        return this.facilityId;
    }
    
    public void setFacilityId(Integer facilityId) {
        this.facilityId = facilityId;
    }




}


