package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Visittype generated by hbm2java
 */
public class Visittype  implements java.io.Serializable {


     private int id;
     private String visitName;

    public Visittype() {
    }

	
    public Visittype(int id) {
        this.id = id;
    }
    public Visittype(int id, String visitName) {
       this.id = id;
       this.visitName = visitName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getVisitName() {
        return this.visitName;
    }
    
    public void setVisitName(String visitName) {
        this.visitName = visitName;
    }




}


