package com.vmmc.entities;
// Generated May 25, 2020 3:21:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Visit generated by hbm2java
 */
public class Visit  implements java.io.Serializable {


     private Integer visitId;
     private Long visitPlanId;
     private Date visitDate;
     private String visitInterval;
     private String attendedBy;
     private Boolean visitAdverse;
     private String adverseCode;
     private String adverseSeverity;
     private String staffComent;
     private String visitType;
     private String visitName;
     private Boolean isWoundHealing;
     private Boolean hasResumedSex;
     private String riskReductionPlan;
     private String startDate;
     private String endDate;

    public Visit() {
    }

    public Visit(Long visitPlanId, Date visitDate, String visitInterval, String attendedBy, Boolean visitAdverse, String adverseCode, String adverseSeverity, String staffComent, String visitType, String visitName, Boolean isWoundHealing, Boolean hasResumedSex, String riskReductionPlan, String startDate, String endDate) {
       this.visitPlanId = visitPlanId;
       this.visitDate = visitDate;
       this.visitInterval = visitInterval;
       this.attendedBy = attendedBy;
       this.visitAdverse = visitAdverse;
       this.adverseCode = adverseCode;
       this.adverseSeverity = adverseSeverity;
       this.staffComent = staffComent;
       this.visitType = visitType;
       this.visitName = visitName;
       this.isWoundHealing = isWoundHealing;
       this.hasResumedSex = hasResumedSex;
       this.riskReductionPlan = riskReductionPlan;
       this.startDate = startDate;
       this.endDate = endDate;
    }
   
    public Integer getVisitId() {
        return this.visitId;
    }
    
    public void setVisitId(Integer visitId) {
        this.visitId = visitId;
    }
    public Long getVisitPlanId() {
        return this.visitPlanId;
    }
    
    public void setVisitPlanId(Long visitPlanId) {
        this.visitPlanId = visitPlanId;
    }
    public Date getVisitDate() {
        return this.visitDate;
    }
    
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }
    public String getVisitInterval() {
        return this.visitInterval;
    }
    
    public void setVisitInterval(String visitInterval) {
        this.visitInterval = visitInterval;
    }
    public String getAttendedBy() {
        return this.attendedBy;
    }
    
    public void setAttendedBy(String attendedBy) {
        this.attendedBy = attendedBy;
    }
    public Boolean getVisitAdverse() {
        return this.visitAdverse;
    }
    
    public void setVisitAdverse(Boolean visitAdverse) {
        this.visitAdverse = visitAdverse;
    }
    public String getAdverseCode() {
        return this.adverseCode;
    }
    
    public void setAdverseCode(String adverseCode) {
        this.adverseCode = adverseCode;
    }
    public String getAdverseSeverity() {
        return this.adverseSeverity;
    }
    
    public void setAdverseSeverity(String adverseSeverity) {
        this.adverseSeverity = adverseSeverity;
    }
    public String getStaffComent() {
        return this.staffComent;
    }
    
    public void setStaffComent(String staffComent) {
        this.staffComent = staffComent;
    }
    public String getVisitType() {
        return this.visitType;
    }
    
    public void setVisitType(String visitType) {
        this.visitType = visitType;
    }
    public String getVisitName() {
        return this.visitName;
    }
    
    public void setVisitName(String visitName) {
        this.visitName = visitName;
    }
    public Boolean getIsWoundHealing() {
        return this.isWoundHealing;
    }
    
    public void setIsWoundHealing(Boolean isWoundHealing) {
        this.isWoundHealing = isWoundHealing;
    }
    public Boolean getHasResumedSex() {
        return this.hasResumedSex;
    }
    
    public void setHasResumedSex(Boolean hasResumedSex) {
        this.hasResumedSex = hasResumedSex;
    }
    public String getRiskReductionPlan() {
        return this.riskReductionPlan;
    }
    
    public void setRiskReductionPlan(String riskReductionPlan) {
        this.riskReductionPlan = riskReductionPlan;
    }
    public String getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }




}


