package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VmmcMedicalscreening generated by hbm2java
 */
public class VmmcMedicalscreening  implements java.io.Serializable {


     private Integer id;
     private String opdnumber;
     private Double weight;
     private Double temperature;
     private String bloodPressure;
     private Double pulse;
     private String areKnownAllergies;
     private String allergies;
     private String anyMedications;
     private String medications;
     private String anyOperations;
     private String operations;
     private String hasTestedHiv;
     private String ifTestedLessOneMonth;
     private String ifTestedResult;
     private String proofTestProvided;
     private String isAbnormalBleeding;
     private String familyHistoryabnormalbleeding;
     private Date dateTaken;
     private String hivtestResult;
     private Integer cd4cellCount;
     private Integer whoclinicalStage;
     private String hivtestDone;
     private String vmmcid;
     private String ifTestedOneThreeMonths;
     private String ifTestedMoreThreeMonths;
     private String ifTestedSpecify;

    public VmmcMedicalscreening() {
    }

    public VmmcMedicalscreening(String opdnumber, Double weight, Double temperature, String bloodPressure, Double pulse, String areKnownAllergies, String allergies, String anyMedications, String medications, String anyOperations, String operations, String hasTestedHiv, String ifTestedLessOneMonth, String ifTestedResult, String proofTestProvided, String isAbnormalBleeding, String familyHistoryabnormalbleeding, Date dateTaken, String hivtestResult, Integer cd4cellCount, Integer whoclinicalStage, String hivtestDone, String vmmcid, String ifTestedOneThreeMonths, String ifTestedMoreThreeMonths, String ifTestedSpecify) {
       this.opdnumber = opdnumber;
       this.weight = weight;
       this.temperature = temperature;
       this.bloodPressure = bloodPressure;
       this.pulse = pulse;
       this.areKnownAllergies = areKnownAllergies;
       this.allergies = allergies;
       this.anyMedications = anyMedications;
       this.medications = medications;
       this.anyOperations = anyOperations;
       this.operations = operations;
       this.hasTestedHiv = hasTestedHiv;
       this.ifTestedLessOneMonth = ifTestedLessOneMonth;
       this.ifTestedResult = ifTestedResult;
       this.proofTestProvided = proofTestProvided;
       this.isAbnormalBleeding = isAbnormalBleeding;
       this.familyHistoryabnormalbleeding = familyHistoryabnormalbleeding;
       this.dateTaken = dateTaken;
       this.hivtestResult = hivtestResult;
       this.cd4cellCount = cd4cellCount;
       this.whoclinicalStage = whoclinicalStage;
       this.hivtestDone = hivtestDone;
       this.vmmcid = vmmcid;
       this.ifTestedOneThreeMonths = ifTestedOneThreeMonths;
       this.ifTestedMoreThreeMonths = ifTestedMoreThreeMonths;
       this.ifTestedSpecify = ifTestedSpecify;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    public Double getTemperature() {
        return this.temperature;
    }
    
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }
    public String getBloodPressure() {
        return this.bloodPressure;
    }
    
    public void setBloodPressure(String bloodPressure) {
        this.bloodPressure = bloodPressure;
    }
    public Double getPulse() {
        return this.pulse;
    }
    
    public void setPulse(Double pulse) {
        this.pulse = pulse;
    }
    public String getAreKnownAllergies() {
        return this.areKnownAllergies;
    }
    
    public void setAreKnownAllergies(String areKnownAllergies) {
        this.areKnownAllergies = areKnownAllergies;
    }
    public String getAllergies() {
        return this.allergies;
    }
    
    public void setAllergies(String allergies) {
        this.allergies = allergies;
    }
    public String getAnyMedications() {
        return this.anyMedications;
    }
    
    public void setAnyMedications(String anyMedications) {
        this.anyMedications = anyMedications;
    }
    public String getMedications() {
        return this.medications;
    }
    
    public void setMedications(String medications) {
        this.medications = medications;
    }
    public String getAnyOperations() {
        return this.anyOperations;
    }
    
    public void setAnyOperations(String anyOperations) {
        this.anyOperations = anyOperations;
    }
    public String getOperations() {
        return this.operations;
    }
    
    public void setOperations(String operations) {
        this.operations = operations;
    }
    public String getHasTestedHiv() {
        return this.hasTestedHiv;
    }
    
    public void setHasTestedHiv(String hasTestedHiv) {
        this.hasTestedHiv = hasTestedHiv;
    }
    public String getIfTestedLessOneMonth() {
        return this.ifTestedLessOneMonth;
    }
    
    public void setIfTestedLessOneMonth(String ifTestedLessOneMonth) {
        this.ifTestedLessOneMonth = ifTestedLessOneMonth;
    }
    public String getIfTestedResult() {
        return this.ifTestedResult;
    }
    
    public void setIfTestedResult(String ifTestedResult) {
        this.ifTestedResult = ifTestedResult;
    }
    public String getProofTestProvided() {
        return this.proofTestProvided;
    }
    
    public void setProofTestProvided(String proofTestProvided) {
        this.proofTestProvided = proofTestProvided;
    }
    public String getIsAbnormalBleeding() {
        return this.isAbnormalBleeding;
    }
    
    public void setIsAbnormalBleeding(String isAbnormalBleeding) {
        this.isAbnormalBleeding = isAbnormalBleeding;
    }
    public String getFamilyHistoryabnormalbleeding() {
        return this.familyHistoryabnormalbleeding;
    }
    
    public void setFamilyHistoryabnormalbleeding(String familyHistoryabnormalbleeding) {
        this.familyHistoryabnormalbleeding = familyHistoryabnormalbleeding;
    }
    public Date getDateTaken() {
        return this.dateTaken;
    }
    
    public void setDateTaken(Date dateTaken) {
        this.dateTaken = dateTaken;
    }
    public String getHivtestResult() {
        return this.hivtestResult;
    }
    
    public void setHivtestResult(String hivtestResult) {
        this.hivtestResult = hivtestResult;
    }
    public Integer getCd4cellCount() {
        return this.cd4cellCount;
    }
    
    public void setCd4cellCount(Integer cd4cellCount) {
        this.cd4cellCount = cd4cellCount;
    }
    public Integer getWhoclinicalStage() {
        return this.whoclinicalStage;
    }
    
    public void setWhoclinicalStage(Integer whoclinicalStage) {
        this.whoclinicalStage = whoclinicalStage;
    }
    public String getHivtestDone() {
        return this.hivtestDone;
    }
    
    public void setHivtestDone(String hivtestDone) {
        this.hivtestDone = hivtestDone;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }
    public String getIfTestedOneThreeMonths() {
        return this.ifTestedOneThreeMonths;
    }
    
    public void setIfTestedOneThreeMonths(String ifTestedOneThreeMonths) {
        this.ifTestedOneThreeMonths = ifTestedOneThreeMonths;
    }
    public String getIfTestedMoreThreeMonths() {
        return this.ifTestedMoreThreeMonths;
    }
    
    public void setIfTestedMoreThreeMonths(String ifTestedMoreThreeMonths) {
        this.ifTestedMoreThreeMonths = ifTestedMoreThreeMonths;
    }
    public String getIfTestedSpecify() {
        return this.ifTestedSpecify;
    }
    
    public void setIfTestedSpecify(String ifTestedSpecify) {
        this.ifTestedSpecify = ifTestedSpecify;
    }




}


