package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Vmmc generated by hbm2java
 */
public class Vmmc  implements java.io.Serializable {


     private String vmmcnumber;
     private String typeofFacility;
     private String facilityCode;
     private String comment;
     private String opdnumber;

    public Vmmc() {
    }

	
    public Vmmc(String vmmcnumber) {
        this.vmmcnumber = vmmcnumber;
    }
    public Vmmc(String vmmcnumber, String typeofFacility, String facilityCode, String comment, String opdnumber) {
       this.vmmcnumber = vmmcnumber;
       this.typeofFacility = typeofFacility;
       this.facilityCode = facilityCode;
       this.comment = comment;
       this.opdnumber = opdnumber;
    }
   
    public String getVmmcnumber() {
        return this.vmmcnumber;
    }
    
    public void setVmmcnumber(String vmmcnumber) {
        this.vmmcnumber = vmmcnumber;
    }
    public String getTypeofFacility() {
        return this.typeofFacility;
    }
    
    public void setTypeofFacility(String typeofFacility) {
        this.typeofFacility = typeofFacility;
    }
    public String getFacilityCode() {
        return this.facilityCode;
    }
    
    public void setFacilityCode(String facilityCode) {
        this.facilityCode = facilityCode;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getOpdnumber() {
        return this.opdnumber;
    }
    
    public void setOpdnumber(String opdnumber) {
        this.opdnumber = opdnumber;
    }




}


