package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * VmmcRiskreductionplan generated by hbm2java
 */
public class VmmcRiskreductionplan  implements java.io.Serializable {


     private int id;
     private Integer visitId;
     private Integer riskReductionPlanTypeId;
     private String vmmcid;

    public VmmcRiskreductionplan() {
    }

	
    public VmmcRiskreductionplan(int id, String vmmcid) {
        this.id = id;
        this.vmmcid = vmmcid;
    }
    public VmmcRiskreductionplan(int id, Integer visitId, Integer riskReductionPlanTypeId, String vmmcid) {
       this.id = id;
       this.visitId = visitId;
       this.riskReductionPlanTypeId = riskReductionPlanTypeId;
       this.vmmcid = vmmcid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getVisitId() {
        return this.visitId;
    }
    
    public void setVisitId(Integer visitId) {
        this.visitId = visitId;
    }
    public Integer getRiskReductionPlanTypeId() {
        return this.riskReductionPlanTypeId;
    }
    
    public void setRiskReductionPlanTypeId(Integer riskReductionPlanTypeId) {
        this.riskReductionPlanTypeId = riskReductionPlanTypeId;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }




}


