package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * VmmcCircumcisionmethod generated by hbm2java
 */
public class VmmcCircumcisionmethod  implements java.io.Serializable {


     private Integer id;
     private String vmmcid;
     private String patientType;
     private String informedConsentGranted;
     private String adultsClinicianInitials;
     private String parentSignature;
     private String minorsClinicanInitials;
     private String consentObtainedBy;
     private String circumcisionMethod;
     private String circumcisionChosenByClients;
     private String otherEligibleSpecify;
     private String otherAppropriateSpecify;

    public VmmcCircumcisionmethod() {
    }

    public VmmcCircumcisionmethod(String vmmcid, String patientType, String informedConsentGranted, String adultsClinicianInitials, String parentSignature, String minorsClinicanInitials, String consentObtainedBy, String circumcisionMethod, String circumcisionChosenByClients, String otherEligibleSpecify, String otherAppropriateSpecify) {
       this.vmmcid = vmmcid;
       this.patientType = patientType;
       this.informedConsentGranted = informedConsentGranted;
       this.adultsClinicianInitials = adultsClinicianInitials;
       this.parentSignature = parentSignature;
       this.minorsClinicanInitials = minorsClinicanInitials;
       this.consentObtainedBy = consentObtainedBy;
       this.circumcisionMethod = circumcisionMethod;
       this.circumcisionChosenByClients = circumcisionChosenByClients;
       this.otherEligibleSpecify = otherEligibleSpecify;
       this.otherAppropriateSpecify = otherAppropriateSpecify;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }
    public String getPatientType() {
        return this.patientType;
    }
    
    public void setPatientType(String patientType) {
        this.patientType = patientType;
    }
    public String getInformedConsentGranted() {
        return this.informedConsentGranted;
    }
    
    public void setInformedConsentGranted(String informedConsentGranted) {
        this.informedConsentGranted = informedConsentGranted;
    }
    public String getAdultsClinicianInitials() {
        return this.adultsClinicianInitials;
    }
    
    public void setAdultsClinicianInitials(String adultsClinicianInitials) {
        this.adultsClinicianInitials = adultsClinicianInitials;
    }
    public String getParentSignature() {
        return this.parentSignature;
    }
    
    public void setParentSignature(String parentSignature) {
        this.parentSignature = parentSignature;
    }
    public String getMinorsClinicanInitials() {
        return this.minorsClinicanInitials;
    }
    
    public void setMinorsClinicanInitials(String minorsClinicanInitials) {
        this.minorsClinicanInitials = minorsClinicanInitials;
    }
    public String getConsentObtainedBy() {
        return this.consentObtainedBy;
    }
    
    public void setConsentObtainedBy(String consentObtainedBy) {
        this.consentObtainedBy = consentObtainedBy;
    }
    public String getCircumcisionMethod() {
        return this.circumcisionMethod;
    }
    
    public void setCircumcisionMethod(String circumcisionMethod) {
        this.circumcisionMethod = circumcisionMethod;
    }
    public String getCircumcisionChosenByClients() {
        return this.circumcisionChosenByClients;
    }
    
    public void setCircumcisionChosenByClients(String circumcisionChosenByClients) {
        this.circumcisionChosenByClients = circumcisionChosenByClients;
    }
    public String getOtherEligibleSpecify() {
        return this.otherEligibleSpecify;
    }
    
    public void setOtherEligibleSpecify(String otherEligibleSpecify) {
        this.otherEligibleSpecify = otherEligibleSpecify;
    }
    public String getOtherAppropriateSpecify() {
        return this.otherAppropriateSpecify;
    }
    
    public void setOtherAppropriateSpecify(String otherAppropriateSpecify) {
        this.otherAppropriateSpecify = otherAppropriateSpecify;
    }




}


