package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * VmmcReferredfrom generated by hbm2java
 */
public class VmmcReferredfrom  implements java.io.Serializable {


     private Integer id;
     private String vmmcid;
     private Integer referredFromId;
     private String specifyReferredFrom;
     private String referredFromDescription;

    public VmmcReferredfrom() {
    }

    public VmmcReferredfrom(String vmmcid, Integer referredFromId, String specifyReferredFrom, String referredFromDescription) {
       this.vmmcid = vmmcid;
       this.referredFromId = referredFromId;
       this.specifyReferredFrom = specifyReferredFrom;
       this.referredFromDescription = referredFromDescription;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }
    public Integer getReferredFromId() {
        return this.referredFromId;
    }
    
    public void setReferredFromId(Integer referredFromId) {
        this.referredFromId = referredFromId;
    }
    public String getSpecifyReferredFrom() {
        return this.specifyReferredFrom;
    }
    
    public void setSpecifyReferredFrom(String specifyReferredFrom) {
        this.specifyReferredFrom = specifyReferredFrom;
    }
    public String getReferredFromDescription() {
        return this.referredFromDescription;
    }
    
    public void setReferredFromDescription(String referredFromDescription) {
        this.referredFromDescription = referredFromDescription;
    }




}


