package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * Vmmcservicetype generated by hbm2java
 */
public class Vmmcservicetype  implements java.io.Serializable {


     private int id;
     private String vmmcserviceName;

    public Vmmcservicetype() {
    }

	
    public Vmmcservicetype(int id) {
        this.id = id;
    }
    public Vmmcservicetype(int id, String vmmcserviceName) {
       this.id = id;
       this.vmmcserviceName = vmmcserviceName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getVmmcserviceName() {
        return this.vmmcserviceName;
    }
    
    public void setVmmcserviceName(String vmmcserviceName) {
        this.vmmcserviceName = vmmcserviceName;
    }




}


