package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VmmcPrepexmalecircumcision generated by hbm2java
 */
public class VmmcPrepexmalecircumcision  implements java.io.Serializable {


     private Integer id;
     private Integer circumcisionProcedureId;
     private String deviceSize;
     private String deviceBatchId;
     private Date deviceExpiriyDate;
     private Date deviceExpiryTime;
     private String topicalAnaesthesia;
     private String vmmcid;
     private String topicalAnaesthesiaType;

    public VmmcPrepexmalecircumcision() {
    }

    public VmmcPrepexmalecircumcision(Integer circumcisionProcedureId, String deviceSize, String deviceBatchId, Date deviceExpiriyDate, Date deviceExpiryTime, String topicalAnaesthesia, String vmmcid, String topicalAnaesthesiaType) {
       this.circumcisionProcedureId = circumcisionProcedureId;
       this.deviceSize = deviceSize;
       this.deviceBatchId = deviceBatchId;
       this.deviceExpiriyDate = deviceExpiriyDate;
       this.deviceExpiryTime = deviceExpiryTime;
       this.topicalAnaesthesia = topicalAnaesthesia;
       this.vmmcid = vmmcid;
       this.topicalAnaesthesiaType = topicalAnaesthesiaType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getCircumcisionProcedureId() {
        return this.circumcisionProcedureId;
    }
    
    public void setCircumcisionProcedureId(Integer circumcisionProcedureId) {
        this.circumcisionProcedureId = circumcisionProcedureId;
    }
    public String getDeviceSize() {
        return this.deviceSize;
    }
    
    public void setDeviceSize(String deviceSize) {
        this.deviceSize = deviceSize;
    }
    public String getDeviceBatchId() {
        return this.deviceBatchId;
    }
    
    public void setDeviceBatchId(String deviceBatchId) {
        this.deviceBatchId = deviceBatchId;
    }
    public Date getDeviceExpiriyDate() {
        return this.deviceExpiriyDate;
    }
    
    public void setDeviceExpiriyDate(Date deviceExpiriyDate) {
        this.deviceExpiriyDate = deviceExpiriyDate;
    }
    public Date getDeviceExpiryTime() {
        return this.deviceExpiryTime;
    }
    
    public void setDeviceExpiryTime(Date deviceExpiryTime) {
        this.deviceExpiryTime = deviceExpiryTime;
    }
    public String getTopicalAnaesthesia() {
        return this.topicalAnaesthesia;
    }
    
    public void setTopicalAnaesthesia(String topicalAnaesthesia) {
        this.topicalAnaesthesia = topicalAnaesthesia;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }
    public String getTopicalAnaesthesiaType() {
        return this.topicalAnaesthesiaType;
    }
    
    public void setTopicalAnaesthesiaType(String topicalAnaesthesiaType) {
        this.topicalAnaesthesiaType = topicalAnaesthesiaType;
    }




}


