package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VmmcPostprocedureassessment generated by hbm2java
 */
public class VmmcPostprocedureassessment  implements java.io.Serializable {


     private Integer id;
     private String vmmcid;
     private String bloodPressure;
     private Double pulse;
     private String prePexDevicePlaced;
     private String clientProvideedInstruction;
     private String givenMcclientCard;
     private String analgesiaGiven;
     private String drug;
     private String generalCondition;
     private Date nextVisitDate;
     private String dischargedBy;

    public VmmcPostprocedureassessment() {
    }

    public VmmcPostprocedureassessment(String vmmcid, String bloodPressure, Double pulse, String prePexDevicePlaced, String clientProvideedInstruction, String givenMcclientCard, String analgesiaGiven, String drug, String generalCondition, Date nextVisitDate, String dischargedBy) {
       this.vmmcid = vmmcid;
       this.bloodPressure = bloodPressure;
       this.pulse = pulse;
       this.prePexDevicePlaced = prePexDevicePlaced;
       this.clientProvideedInstruction = clientProvideedInstruction;
       this.givenMcclientCard = givenMcclientCard;
       this.analgesiaGiven = analgesiaGiven;
       this.drug = drug;
       this.generalCondition = generalCondition;
       this.nextVisitDate = nextVisitDate;
       this.dischargedBy = dischargedBy;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }
    public String getBloodPressure() {
        return this.bloodPressure;
    }
    
    public void setBloodPressure(String bloodPressure) {
        this.bloodPressure = bloodPressure;
    }
    public Double getPulse() {
        return this.pulse;
    }
    
    public void setPulse(Double pulse) {
        this.pulse = pulse;
    }
    public String getPrePexDevicePlaced() {
        return this.prePexDevicePlaced;
    }
    
    public void setPrePexDevicePlaced(String prePexDevicePlaced) {
        this.prePexDevicePlaced = prePexDevicePlaced;
    }
    public String getClientProvideedInstruction() {
        return this.clientProvideedInstruction;
    }
    
    public void setClientProvideedInstruction(String clientProvideedInstruction) {
        this.clientProvideedInstruction = clientProvideedInstruction;
    }
    public String getGivenMcclientCard() {
        return this.givenMcclientCard;
    }
    
    public void setGivenMcclientCard(String givenMcclientCard) {
        this.givenMcclientCard = givenMcclientCard;
    }
    public String getAnalgesiaGiven() {
        return this.analgesiaGiven;
    }
    
    public void setAnalgesiaGiven(String analgesiaGiven) {
        this.analgesiaGiven = analgesiaGiven;
    }
    public String getDrug() {
        return this.drug;
    }
    
    public void setDrug(String drug) {
        this.drug = drug;
    }
    public String getGeneralCondition() {
        return this.generalCondition;
    }
    
    public void setGeneralCondition(String generalCondition) {
        this.generalCondition = generalCondition;
    }
    public Date getNextVisitDate() {
        return this.nextVisitDate;
    }
    
    public void setNextVisitDate(Date nextVisitDate) {
        this.nextVisitDate = nextVisitDate;
    }
    public String getDischargedBy() {
        return this.dischargedBy;
    }
    
    public void setDischargedBy(String dischargedBy) {
        this.dischargedBy = dischargedBy;
    }




}


