package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * VmmcComplaints generated by hbm2java
 */
public class VmmcComplaints  implements java.io.Serializable {


     private Integer id;
     private String vmmcid;
     private Integer complaintTypeId;
     private String specifyComplaint;
     private String complaintDescription;

    public VmmcComplaints() {
    }

    public VmmcComplaints(String vmmcid, Integer complaintTypeId, String specifyComplaint, String complaintDescription) {
       this.vmmcid = vmmcid;
       this.complaintTypeId = complaintTypeId;
       this.specifyComplaint = specifyComplaint;
       this.complaintDescription = complaintDescription;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }
    public Integer getComplaintTypeId() {
        return this.complaintTypeId;
    }
    
    public void setComplaintTypeId(Integer complaintTypeId) {
        this.complaintTypeId = complaintTypeId;
    }
    public String getSpecifyComplaint() {
        return this.specifyComplaint;
    }
    
    public void setSpecifyComplaint(String specifyComplaint) {
        this.specifyComplaint = specifyComplaint;
    }
    public String getComplaintDescription() {
        return this.complaintDescription;
    }
    
    public void setComplaintDescription(String complaintDescription) {
        this.complaintDescription = complaintDescription;
    }




}


