package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VmmcSurgicalmalecircumcision generated by hbm2java
 */
public class VmmcSurgicalmalecircumcision  implements java.io.Serializable {


     private Integer id;
     private Integer circumcisionProcedureId;
     private String procedureTypeId;
     private Double lignocaineone;
     private Double lignocainetwo;
     private Double bupivacaine;
     private String diathermyUsed;
     private String diathermySetting;
     private Date procedureStartTime;
     private Date procedureEndtime;
     private String vmmcid;

    public VmmcSurgicalmalecircumcision() {
    }

    public VmmcSurgicalmalecircumcision(Integer circumcisionProcedureId, String procedureTypeId, Double lignocaineone, Double lignocainetwo, Double bupivacaine, String diathermyUsed, String diathermySetting, Date procedureStartTime, Date procedureEndtime, String vmmcid) {
       this.circumcisionProcedureId = circumcisionProcedureId;
       this.procedureTypeId = procedureTypeId;
       this.lignocaineone = lignocaineone;
       this.lignocainetwo = lignocainetwo;
       this.bupivacaine = bupivacaine;
       this.diathermyUsed = diathermyUsed;
       this.diathermySetting = diathermySetting;
       this.procedureStartTime = procedureStartTime;
       this.procedureEndtime = procedureEndtime;
       this.vmmcid = vmmcid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getCircumcisionProcedureId() {
        return this.circumcisionProcedureId;
    }
    
    public void setCircumcisionProcedureId(Integer circumcisionProcedureId) {
        this.circumcisionProcedureId = circumcisionProcedureId;
    }
    public String getProcedureTypeId() {
        return this.procedureTypeId;
    }
    
    public void setProcedureTypeId(String procedureTypeId) {
        this.procedureTypeId = procedureTypeId;
    }
    public Double getLignocaineone() {
        return this.lignocaineone;
    }
    
    public void setLignocaineone(Double lignocaineone) {
        this.lignocaineone = lignocaineone;
    }
    public Double getLignocainetwo() {
        return this.lignocainetwo;
    }
    
    public void setLignocainetwo(Double lignocainetwo) {
        this.lignocainetwo = lignocainetwo;
    }
    public Double getBupivacaine() {
        return this.bupivacaine;
    }
    
    public void setBupivacaine(Double bupivacaine) {
        this.bupivacaine = bupivacaine;
    }
    public String getDiathermyUsed() {
        return this.diathermyUsed;
    }
    
    public void setDiathermyUsed(String diathermyUsed) {
        this.diathermyUsed = diathermyUsed;
    }
    public String getDiathermySetting() {
        return this.diathermySetting;
    }
    
    public void setDiathermySetting(String diathermySetting) {
        this.diathermySetting = diathermySetting;
    }
    public Date getProcedureStartTime() {
        return this.procedureStartTime;
    }
    
    public void setProcedureStartTime(Date procedureStartTime) {
        this.procedureStartTime = procedureStartTime;
    }
    public Date getProcedureEndtime() {
        return this.procedureEndtime;
    }
    
    public void setProcedureEndtime(Date procedureEndtime) {
        this.procedureEndtime = procedureEndtime;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }




}


