package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * VmmcAdverseeventtype generated by hbm2java
 */
public class VmmcAdverseeventtype  implements java.io.Serializable {


     private int id;
     private Integer adverseEventId;
     private Integer adverseEventTypeId;

    public VmmcAdverseeventtype() {
    }

	
    public VmmcAdverseeventtype(int id) {
        this.id = id;
    }
    public VmmcAdverseeventtype(int id, Integer adverseEventId, Integer adverseEventTypeId) {
       this.id = id;
       this.adverseEventId = adverseEventId;
       this.adverseEventTypeId = adverseEventTypeId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getAdverseEventId() {
        return this.adverseEventId;
    }
    
    public void setAdverseEventId(Integer adverseEventId) {
        this.adverseEventId = adverseEventId;
    }
    public Integer getAdverseEventTypeId() {
        return this.adverseEventTypeId;
    }
    
    public void setAdverseEventTypeId(Integer adverseEventTypeId) {
        this.adverseEventTypeId = adverseEventTypeId;
    }




}


