package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * VmmcGenitalexam generated by hbm2java
 */
public class VmmcGenitalexam  implements java.io.Serializable {


     private Integer id;
     private String vmmcid;
     private Integer genitalExamTypeId;
     private String genitalExamDescription;
     private String specifyOtherGenitalExam;

    public VmmcGenitalexam() {
    }

    public VmmcGenitalexam(String vmmcid, Integer genitalExamTypeId, String genitalExamDescription, String specifyOtherGenitalExam) {
       this.vmmcid = vmmcid;
       this.genitalExamTypeId = genitalExamTypeId;
       this.genitalExamDescription = genitalExamDescription;
       this.specifyOtherGenitalExam = specifyOtherGenitalExam;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }
    public Integer getGenitalExamTypeId() {
        return this.genitalExamTypeId;
    }
    
    public void setGenitalExamTypeId(Integer genitalExamTypeId) {
        this.genitalExamTypeId = genitalExamTypeId;
    }
    public String getGenitalExamDescription() {
        return this.genitalExamDescription;
    }
    
    public void setGenitalExamDescription(String genitalExamDescription) {
        this.genitalExamDescription = genitalExamDescription;
    }
    public String getSpecifyOtherGenitalExam() {
        return this.specifyOtherGenitalExam;
    }
    
    public void setSpecifyOtherGenitalExam(String specifyOtherGenitalExam) {
        this.specifyOtherGenitalExam = specifyOtherGenitalExam;
    }




}


