package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VmmcVisits generated by hbm2java
 */
public class VmmcVisits  implements java.io.Serializable {


     private Integer id;
     private String vmmcid;
     private long vipId;
     private Date visitDate;
     private String visitInterval;
     private String anyAdverseEvent;
     private String ifYesAecode;
     private String severity;
     private String woundhealingComplete;
     private Date ifNoAdditionalVisitDate;
     private String resumedSexualActivity;
     private Integer ifResumedWeeks;
     private String counseled;
     private String ifCounseledRiskPlan;
     private String staffComment;

    public VmmcVisits() {
    }

	
    public VmmcVisits(String vmmcid, long vipId) {
        this.vmmcid = vmmcid;
        this.vipId = vipId;
    }
    public VmmcVisits(String vmmcid, long vipId, Date visitDate, String visitInterval, String anyAdverseEvent, String ifYesAecode, String severity, String woundhealingComplete, Date ifNoAdditionalVisitDate, String resumedSexualActivity, Integer ifResumedWeeks, String counseled, String ifCounseledRiskPlan, String staffComment) {
       this.vmmcid = vmmcid;
       this.vipId = vipId;
       this.visitDate = visitDate;
       this.visitInterval = visitInterval;
       this.anyAdverseEvent = anyAdverseEvent;
       this.ifYesAecode = ifYesAecode;
       this.severity = severity;
       this.woundhealingComplete = woundhealingComplete;
       this.ifNoAdditionalVisitDate = ifNoAdditionalVisitDate;
       this.resumedSexualActivity = resumedSexualActivity;
       this.ifResumedWeeks = ifResumedWeeks;
       this.counseled = counseled;
       this.ifCounseledRiskPlan = ifCounseledRiskPlan;
       this.staffComment = staffComment;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }
    public long getVipId() {
        return this.vipId;
    }
    
    public void setVipId(long vipId) {
        this.vipId = vipId;
    }
    public Date getVisitDate() {
        return this.visitDate;
    }
    
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }
    public String getVisitInterval() {
        return this.visitInterval;
    }
    
    public void setVisitInterval(String visitInterval) {
        this.visitInterval = visitInterval;
    }
    public String getAnyAdverseEvent() {
        return this.anyAdverseEvent;
    }
    
    public void setAnyAdverseEvent(String anyAdverseEvent) {
        this.anyAdverseEvent = anyAdverseEvent;
    }
    public String getIfYesAecode() {
        return this.ifYesAecode;
    }
    
    public void setIfYesAecode(String ifYesAecode) {
        this.ifYesAecode = ifYesAecode;
    }
    public String getSeverity() {
        return this.severity;
    }
    
    public void setSeverity(String severity) {
        this.severity = severity;
    }
    public String getWoundhealingComplete() {
        return this.woundhealingComplete;
    }
    
    public void setWoundhealingComplete(String woundhealingComplete) {
        this.woundhealingComplete = woundhealingComplete;
    }
    public Date getIfNoAdditionalVisitDate() {
        return this.ifNoAdditionalVisitDate;
    }
    
    public void setIfNoAdditionalVisitDate(Date ifNoAdditionalVisitDate) {
        this.ifNoAdditionalVisitDate = ifNoAdditionalVisitDate;
    }
    public String getResumedSexualActivity() {
        return this.resumedSexualActivity;
    }
    
    public void setResumedSexualActivity(String resumedSexualActivity) {
        this.resumedSexualActivity = resumedSexualActivity;
    }
    public Integer getIfResumedWeeks() {
        return this.ifResumedWeeks;
    }
    
    public void setIfResumedWeeks(Integer ifResumedWeeks) {
        this.ifResumedWeeks = ifResumedWeeks;
    }
    public String getCounseled() {
        return this.counseled;
    }
    
    public void setCounseled(String counseled) {
        this.counseled = counseled;
    }
    public String getIfCounseledRiskPlan() {
        return this.ifCounseledRiskPlan;
    }
    
    public void setIfCounseledRiskPlan(String ifCounseledRiskPlan) {
        this.ifCounseledRiskPlan = ifCounseledRiskPlan;
    }
    public String getStaffComment() {
        return this.staffComment;
    }
    
    public void setStaffComment(String staffComment) {
        this.staffComment = staffComment;
    }




}


