package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * VmmcGeneralcondition generated by hbm2java
 */
public class VmmcGeneralcondition  implements java.io.Serializable {


     private Integer id;
     private String vmmcid;
     private Integer generalConditionTypeId;
     private String specifyGeneralCondition;
     private String generalConditonDescription;

    public VmmcGeneralcondition() {
    }

    public VmmcGeneralcondition(String vmmcid, Integer generalConditionTypeId, String specifyGeneralCondition, String generalConditonDescription) {
       this.vmmcid = vmmcid;
       this.generalConditionTypeId = generalConditionTypeId;
       this.specifyGeneralCondition = specifyGeneralCondition;
       this.generalConditonDescription = generalConditonDescription;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }
    public Integer getGeneralConditionTypeId() {
        return this.generalConditionTypeId;
    }
    
    public void setGeneralConditionTypeId(Integer generalConditionTypeId) {
        this.generalConditionTypeId = generalConditionTypeId;
    }
    public String getSpecifyGeneralCondition() {
        return this.specifyGeneralCondition;
    }
    
    public void setSpecifyGeneralCondition(String specifyGeneralCondition) {
        this.specifyGeneralCondition = specifyGeneralCondition;
    }
    public String getGeneralConditonDescription() {
        return this.generalConditonDescription;
    }
    
    public void setGeneralConditonDescription(String generalConditonDescription) {
        this.generalConditonDescription = generalConditonDescription;
    }




}


