package com.vmmc.entities;
// Generated Jul 11, 2019 2:29:35 PM by Hibernate Tools 4.3.1



/**
 * VmmcCircumcisionreason generated by hbm2java
 */
public class VmmcCircumcisionreason  implements java.io.Serializable {


     private Integer id;
     private String vmmcid;
     private Integer circumcisionReasonTypeId;
     private String specifyOtherReasons;
     private String reasonsDescription;

    public VmmcCircumcisionreason() {
    }

    public VmmcCircumcisionreason(String vmmcid, Integer circumcisionReasonTypeId, String specifyOtherReasons, String reasonsDescription) {
       this.vmmcid = vmmcid;
       this.circumcisionReasonTypeId = circumcisionReasonTypeId;
       this.specifyOtherReasons = specifyOtherReasons;
       this.reasonsDescription = reasonsDescription;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVmmcid() {
        return this.vmmcid;
    }
    
    public void setVmmcid(String vmmcid) {
        this.vmmcid = vmmcid;
    }
    public Integer getCircumcisionReasonTypeId() {
        return this.circumcisionReasonTypeId;
    }
    
    public void setCircumcisionReasonTypeId(Integer circumcisionReasonTypeId) {
        this.circumcisionReasonTypeId = circumcisionReasonTypeId;
    }
    public String getSpecifyOtherReasons() {
        return this.specifyOtherReasons;
    }
    
    public void setSpecifyOtherReasons(String specifyOtherReasons) {
        this.specifyOtherReasons = specifyOtherReasons;
    }
    public String getReasonsDescription() {
        return this.reasonsDescription;
    }
    
    public void setReasonsDescription(String reasonsDescription) {
        this.reasonsDescription = reasonsDescription;
    }




}


